googleapis/google-cloud-go

.github/ISSUE_TEMPLATE/bug_report.md

These might help resolve package management problems.
e.g., `go env` tells us if they are using modules or not.

.github/ISSUE_TEMPLATE: ask for go version and go env

---

spanner/spannertest/db_test.go
spanner/spannertest/funcs.go
spanner/spansql/keywords.go

These are extremely similar, only differing in order comparison.

spanner/spannertest: support MIN/MAX aggregation functions

---

RELEASING.md

Fix go links that are broken on github and clean up
a few outstanding gerrit references.

all: clean up RELEASING.md

---

.github/blunderbuss.yml

Will re-add once repo-automation-bots#599 is resolved.

.github: remove myself as fallback in blunderbuss

---

pubsub/pstest/fake.go
pubsub/pstest/fake_test.go

Change-Id: Ie25d004a2ae3bc354a4e530db0bad9347c802c4b
Closes #2421

pubsub/pstest: fake time function

---

spanner/cmp_test.go

This was caused by the upgrade of grpc in #2564.
Fixes: #2571

fix(spanner): add extra field to ignore with cmp

---

spanner/statement.go

docs(spanner): clarify parameter naming requirements

---

bigquery/nulls.go
bigquery/nulls_test.go

This is a new PR for closed PR https://github.com/googleapis/google-cloud-go/pull/2574 because you can only allow edits for maintainers on user-forks and NOT organization forks.

bigqueryNullFloat64 add +Inf, -Inf and NaN support

---

spanner/spannertest/db.go

This operation is rejected by the real Cloud Spanner.

spanner/spannertest: return error for Read with no keys

---

storage/writer_test.go

This test passes now that retries on uploads have been
fixed.

test(storage): re-enable skipped write retry test

---

speech/apiv1/Recognize_smoke_test.go
speech/apiv1p1beta1/Recognize_smoke_test.go

test(speech): reference new bucket for audio file

---

spanner/client.go
spanner/client_test.go

fix(spanner): specify credentials with SPANNER_EMULATOR_HOST

---

.github/release-please.yml

Once merged, we can merge the connected PR and then we should
start to see proposed releases for the root module. More work will
need to be done to figure out supporting the sub-modules.
Related: googleapis/release-please#514

chore(.github): add release please config for root module

---

spanner/key.go
spanner/key_test.go

feat(spanner): add custom type support to spanner.Key

---

CONTRIBUTING.md
README.md
internal/gapicgen/cmd/genbot/Dockerfile
internal/kokoro/vet.sh

- Gen and vet against 1.15
- Lay out currently supported versions
- Mention what versions we test against

chore(all): update version information to 1.15

---

spanner/spannertest/inmem.go

The spannertest simulation does not represent multiple databases, and
the names of databases are ignored in requests, so this method merely
reflects the requested name back, along with the spannertest server
initialisation time.
Fixes #2789.

spanner/spannertest: implement GetDatabase

---

spanner/spannertest/db.go

This supports the ALTER TABLE DROP COLUMN statement.
Fixes #2820.

spanner/spannertest: support dropping columns

---

pubsub/integration_test.go

test(pubsub): remove staging endpoint for sub detach

---

spanner/oc_test.go

test: fix race condition in oc_test.go

---

storage/conformance_test.go
storage/internal/test/conformance/v4_signatures.json

This was recently added to conformance-tests to catch the case
that was noticed in #2767. We can remove the skip in the open
PR meant to fix that issue (#2769).

test(storage): update post policy v4 conformance

---

storage/conformance_test.go
storage/internal/test/conformance/v4_signatures.json

Pick up fixes to conformance tests that cover encoding edge
cases and condition ordering for V4 signature and post policy.
This will unblock #2769.

test(storage): copy latest conformance test fixes

---

spanner/spannertest/db_eval.go
spanner/spannertest/integration_test.go

92bfe7f got most things correct, but I relied on the docs, which have an
error and so one case was incorrect.
(Internally filed as b/170436130)

fix(spanner/spannertest): correct handling of NULL AND FALSE

---

spanner/spannertest/db_query.go
spanner/spannertest/integration_test.go

This involves a significant refactor of `joinIter`, which should now be
clearer and simpler, and keep the join condition (ON/USING/none)
orthogonal to the join type (LEFT/RIGHT/INNER/CROSS/FULL).

feat(spanner/spannertest): support USING clause in JOIN

---

spanner/spannertest/INTERNALS.md
spanner/spannertest/README.md
spanner/spannertest/inmem.go

Describe how things work from a high level.

doc(spanner/spannertest): document the implementation

---

spanner/oc_test.go

Compare the underlying Open Census row data, instead of the entire row struct, with the expected value. This prevents the comparison from breaking if new fields are added to the struct.
Fixes #3000 and #3001

test(spanner): compare data instead of struct

---

spanner/spannertest/db_query.go
spanner/spannertest/integration_test.go

These are similar to the existing LEFT JOIN.
Implementing FULL and RIGHT JOIN is harder.

feat(spanner/spannertest): support INNER and CROSS JOIN

---

spanner/spannertest/db_query.go
spanner/spannertest/integration_test.go

Restructure and make a unified JOIN implementation.
FULL JOIN is still not supported, but all other variations of joins now
work.

feat(spanner/spannertest): implement RIGHT JOIN

---

spanner/spannertest/integration_test.go

This now means the entire integration test passes against both real
Spanner and spannertest.
Also, dramatically speed up the integration test when it runs against
real Spanner (from ~137s to ~81s) by dropping existing tables
concurrently.

test(spanner/spannertest): make ARRAY_AGG test work against real Spanner

---

pubsublite/README.md
pubsublite/doc.go

docs(pubsublite): add readme for pubsublite

---

firestore/integration_test.go

test(firestore): fix order by in integration test

---

pubsublite/internal/wire/subscriber_test.go

test(pubsublite): skip TestSubscribeStreamSpuriousSeekResponse

---

RELEASING.md

Make it clear that release-please is now used for all submodules
and do some other minor cleanup in RELEASING.md

docs(all): update automated release instructions

---

.github/workflows/release-submodule.yaml
.github/workflows/release.yaml

Action was throwing error due to a missing `on` stanza.
I've also switched the order of `if` and `uses`, as the script seemed to be executing even when PR output was not set.

build: "on" was missing for action, switch if order

---

pubsublite/integration_test.go

The server now accepts project ids in resource paths. However, it always returns the project number in returned configs, so we have to exclude the project field in comparisons.

test(pubsublite): enable integration tests for admin resource operations

---

bigtable/bigtable.go
spanner/spannertest/db.go

Test submodules2

---

spanner/spansql/sql.go
spanner/spansql/sql_test.go

Fix https://github.com/googleapis/google-cloud-go/issues/3570

fix(spanner/spansql): fix SelectFromJoin behavior

---

logging/logadmin/sinks_test.go

test(logging/logadmin): skip tests causing failure due to permissions

---

profiler/profiler.go
profiler/profiler_test.go

See b/163319181 that this change fixes.

fix(profiler): make sure retries use the most up-to-date copy of the trailer

---

pubsublite/internal/wire/subscriber_test.go

Adds a couple of barriers to ensure that the server has received the expected requests before proceeding with the rest of the test.
Fixes https://github.com/googleapis/google-cloud-go/issues/3645.

test(pubsublite): fix flaky TestAssigningSubscriberIgnoreOutstandingAcks

---

spanner/client.go

fix(spanner): restore removed scopes

---

internal/gapicgen/cmd/genbot/README.md
internal/gapicgen/cmd/genbot/update.go

chore(internal/gapicgen): use -d to download modules

---

bigquery/integration_test.go

BigQuery updated the streaming limits, breaking this test.  Those
limits are now consistent once again, so we re-enable the test in
accordance with new simplified limits.
Fixes: https://github.com/googleapis/google-cloud-go/issues/3612

test(bigquery): update and re-enable a streaming payload limit test

---

pubsublite/internal/wire/assigner_test.go

The fake error response needs to be set before the assigner is started to prevent races.
Fixes https://github.com/googleapis/google-cloud-go/issues/3789.

test(pubsublite): fix flaky TestAssignerHandlePartitionFailure

---

pubsublite/README.md
pubsublite/pscompat/example_test.go
pubsublite/pscompat/publisher.go

Clarified some comments and examples for publishing.

docs(pubsublite): clarifications for publish

---

logging/logging.go

chore(logging): trigger correct release semver

---

.github/blunderbuss.yml

chore(.github): change default assignee to hengfengli for Spanner issues

---

CONTRIBUTING.md

docs: fix link in contib

---

internal/gapicgen/generator/gapics.go

This new data will be parsed and processed from our metadata
pipeline.

chore(internal): add LibraryType to repo-metadata

---

firestore/integration_test.go

Demonstrate no reproduction for #3889

test(firestore): add additional test verifying deleting a map value via update

---

CHANGES.md

chore(all): fix release version

---

.github/workflows/release-submodule.yaml

chore(all): Update release-submodule.yaml

---

internal/gapicgen/generator/config.go
internal/gapicgen/generator/gapics.go

chore(internal/gapicgen): stop bq/storage/v1alpha2 gen
chore(internal/gapicgen): add manifest entry for pubsublite manual

chore(internal/gapicgen): stop bq/storage/v1alpha2 gen

---

pubsublite/internal/wire/publisher_test.go
pubsublite/internal/wire/subscriber_test.go

These are not necessary and covered by the integration tests.
Fixes: https://github.com/googleapis/google-cloud-go/issues/4134

test(pubsublite): remove TestNewSubscriberCreatesCorrectImpl and TestNewPublisherCreatesImpl

---

internal/kokoro/continuous.sh

bigtable requires specific locations for CMEK

test(bigtable): alter keyring location for tests

---

bigquery/README.md

Fixes: https://github.com/googleapis/google-cloud-go/issues/4242

docs(bigquery): indicate provenance of the iterator package in README

---

internal/gapicgen/cmd/genbot/Dockerfile

Updates Go Protobuf import for generated code. #4273

chore(internal/gapicgen): update generator v0.20.4

---

spanner/session.go

docs(spanner): clarify MaxIdle in SessionPoolConfig

---

internal/kokoro/build_samples.sh

Adds Pub/Sub Lite which was missing from the list of modules of handwritten libraries

test: add pubsublite to local modules

---

internal/gapicgen/cmd/genbot/Dockerfile

Carries fix for `EmitUnpopulated` issue in #4380

chore(intenral): update microgen to v0.21.7

---

internal/gapicgen/cmd/genbot/Dockerfile
internal/gapicgen/generator/config.go

Also, use go install in Dockerfile.

chore(internal): fix irregular pathing

---

compute/apiv1/autoscalers_client.go
compute/apiv1/backend_buckets_client.go
compute/apiv1/backend_services_client.go
compute/apiv1/firewalls_client.go
compute/apiv1/health_checks_client.go
compute/apiv1/instances_client.go
compute/apiv1/region_autoscalers_client.go
compute/apiv1/region_backend_services_client.go
compute/apiv1/region_health_checks_client.go
compute/apiv1/region_url_maps_client.go
compute/apiv1/routers_client.go
compute/apiv1/url_maps_client.go

Changes regenerated locally with generator v0.21.8.
This is the fix for https://github.com/googleapis/google-cloud-go/issues/4380#issuecomment-879218739.

fix(compute): properly generate PUT requests

---

internal/generated/snippets/go.mod
internal/generated/snippets/go.sum
internal/godocfx/go.sum

https://github.com/googleapis/google-cloud-go/issues/4434 is related.

chore: go mod tidy

---

spanner/integration_test.go

test(spanner): fix the json integration test

---

firestore/integration_test.go
storage/integration_test.go

test: skip some consistently failing tests

---

accessapproval/CHANGES.md

chore: release accessapproval 1.0.0

---

aiplatform/CHANGES.md

chore: release aiplatform 1.0.0

---

apigateway/CHANGES.md

chore: release apigateway 1.0.0

---

apigeeconnect/CHANGES.md

chore: release apigeeconnect 1.0.0

---

appengine/CHANGES.md

chore: release appengine 1.0.0

---

artifactregistry/CHANGES.md

chore: release artifactregistry 1.0.0

---

asset/CHANGES.md

chore: release asset 1.0.0

---

automl/CHANGES.md

chore: release automl 1.0.0

---

channel/CHANGES.md

chore: release channel 1.0.0

---

cloudbuild/CHANGES.md

chore: release cloudbuild 1.0.0

---

clouddms/CHANGES.md

chore: release clouddms 1.0.0

---

cloudtasks/CHANGES.md

chore: release cloudtasks 1.0.0

---

container/CHANGES.md

chore: release container 1.0.0

---

datacatalog/CHANGES.md

chore: release datacatalog 1.0.0

---

datafusion/CHANGES.md

chore: release datafusion 1.0.0

---

workflows/CHANGES.md

chore: release workflows 1.0.0

---

websecurityscanner/CHANGES.md

chore: release websecurityscanner 1.0.0

---

webrisk/CHANGES.md

chore: release webrisk 1.0.0

---

vpcaccess/CHANGES.md

chore: release vpcaccess 1.0.0

---

vision/CHANGES.md

chore: release vision 1.0.0

---

videointelligence/CHANGES.md

chore: release videointelligence 1.0.0

---

video/CHANGES.md

chore: release video 1.0.0

---

translate/CHANGES.md

chore: release translate 1.0.0

---

trace/CHANGES.md

chore: release trace 1.0.0

---

tpu/CHANGES.md

chore: release tpu 1.0.0

---

texttospeech/CHANGES.md

chore: release texttospeech 1.0.0

---

storagetransfer/CHANGES.md

chore: release storagetransfer 1.0.0

---

speech/CHANGES.md

chore: release speech 1.0.0

---

shell/CHANGES.md

chore: release shell 1.0.0

---

serviceusage/CHANGES.md

chore: release serviceusage 1.0.0

---

servicemanagement/CHANGES.md

chore: release servicemanagement 1.0.0

---

servicedirectory/CHANGES.md

chore: release servicedirectory 1.0.0

---

servicecontrol/CHANGES.md

chore: release servicecontrol 1.0.0

---

securitycenter/CHANGES.md

chore: release securitycenter 1.0.0

---

security/CHANGES.md

chore: release security 1.0.0

---

secretmanager/CHANGES.md

chore: release secretmanager 1.0.0

---

scheduler/CHANGES.md

chore: release scheduler 1.0.0

---

retail/CHANGES.md

chore: release retail 1.0.0

---

resourcesettings/CHANGES.md

chore: release resourcesettings 1.0.0

---

resourcemanager/CHANGES.md

chore: release resourcemanager 1.0.0

---

redis/CHANGES.md

chore: release redis 1.0.0

---

recommender/CHANGES.md

chore: release recommender 1.0.0

---

recaptchaenterprise/CHANGES.md

chore: release recaptchaenterprise 1.0.0

---

policytroubleshooter/CHANGES.md

chore: release policytroubleshooter 1.0.0

---

oslogin/CHANGES.md

chore: release oslogin 1.0.0

---

osconfig/CHANGES.md

chore: release osconfig 1.0.0

---

orgpolicy/CHANGES.md

chore: release orgpolicy 1.0.0

---

networkmanagement/CHANGES.md

chore: release networkmanagement 1.0.0

---

monitoring/CHANGES.md

chore: release monitoring 1.0.0

---

metastore/CHANGES.md

chore: release metastore 1.0.0

---

memcache/CHANGES.md

chore: release memcache 1.0.0

---

managedidentities/CHANGES.md

chore: release managedidentities 1.0.0

---

language/CHANGES.md

chore: release language 1.0.0

---

kms/CHANGES.md

chore: release kms 1.0.0

---

iap/CHANGES.md

chore: release iap 1.0.0

---

gsuiteaddons/CHANGES.md

chore: release gsuiteaddons 1.0.0

---

gaming/CHANGES.md

chore: release gaming 1.0.0

---

functions/CHANGES.md

chore: release functions 1.0.0

---

eventarc/CHANGES.md

chore: release eventarc 1.0.0

---

essentialcontacts/CHANGES.md

chore: release essentialcontacts 1.0.0

---

documentai/CHANGES.md

chore: release documentai 1.0.0

---

dlp/CHANGES.md

chore: release dlp 1.0.0

---

dataproc/CHANGES.md

chore: release dataproc 1.0.0

---

dialogflow/CHANGES.md

chore: release dialogflow 1.0.0

---

storage/integration_test.go

Fixes #4817 while changes for #4890 are merged in

test(storage): skip "unspecified" PAP tests

---

bigtable/integration_test.go

test(bigtable): fix encoding of unique id for bigtable integration tests

---

compute/apiv1/smoke_test.go

This test is a requirement by vchudnov

test(compute): add headers test

---

internal/btree/benchmarks_test.go

test(internal/btree): fix bug in benchmark

---

internal/godocfx/goldmark-codeblock/codeblock.go
internal/godocfx/testdata/golden/index.yml

This makes it so the "click to copy" button shows up.

chore(internal/godocfx): move prettyprint to pre

---

bigtable/integration_test.go

test(bigtable): randomize app profile names to avoid test collision

---

firestore/integration_test.go

test(firestore): partition queries don't return exact partition counts

---

bigtable/integration_test.go
storage/storage.go

test(bigtable): allow multiple tests to create app profiles

---

bigquery/integration_test.go
bigquery/job.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/5080

feat(bigquery): add BI Engine information to query statistics

---

bigtable/integration_test.go

test(bigtable): fix #5046 by segmenting app profile

---

internal/kokoro/continuous.sh

Fixes https://github.com/googleapis/google-cloud-go/issues/5037

test(spanner): fix flaky TestIntegration_StartBackupOperation test

---

bigquery/storage/managedwriter/managed_stream.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/5120

fix(bigquery/storage/managedwriter): correctly copy request

---

internal/gapicgen/generator/genproto.go

Until we're ready to merge https://github.com/googleapis/googleapis/commit/0fd6a324383fdd1220c9a937b2eef37f53764664

chore: temporarily disable generation for bigtable

---

storage/integration_test.go

chore(storage): reenable gRPC integration test

---

bigquery/storage/managedwriter/doc.go

docs(bigquery/storage/managedwriter): augment docs

---

storage/emulator_test.sh

Fixes version checking logic for emulator tests

test(storage): fix version checking logic

---

iam/go_mod_tidy_hack.go

Existing file is causing gofmt to yell during presubmit testing.

fix(iam): run formatter

---

spanner/integration_test.go
spanner/stats.go

test(spanner): move testing helper to a test

---

storage/integration_test.go

Fixes #4720
Once again, we hit the bucket rate limit - did a quick refactor to interleave buckets instead of simply switching over to a new one. I also removed the object for the 2nd bucket - object ops are not a problem so we don't need a second bucket for those.
If we continue to hit rate limits then we may need to configure the retry config to retry on hitting a 429, remove some of the bucket ops from this test, or separate them out into subtests or additional tests.

test(storage): interleave buckets in test (rate limit issue)

---

filestore/CHANGES.md
internal/gapicgen/generator/config.go

feat(filestore): to v1

---

compute/apiv1/smoke_test.go

Removes explicit use of the operation clients and switches to using the operation wrapper helper for `Wait` to work with operations. Also adds some failed test exits where it would cause a weird panic or error if the test continued to execute. LMK if I should use `t.Fatal` instead.

chore(compute): update smoke_tests with operation Wait helper

---

compute/apiv1/smoke_test.go

chore(compute): switch to t.Fatal in smoke_test

---

storage/CHANGES.md

PiperOrigin-RevId: 425656197
Source-Link: googleapis/googleapis@903e011
Dummy commit of changes landing in 8e91ed1f2f2cb7fa77240dabcafcd2dedf97bda3.

feat(storage/internal): Update definition of RewriteObjectRequest to bring to parity with JSON API support

---

storage/doc.go

docs(storage): update Signed URLs and Post Policy to new surface

---

spanner/spannertest/inmem.go

Client code that applies a DDL change and waits for it should get a fast
response. To avoid triggering the standard polling delay, give the LRO a
chance to complete when the first status RPC (GetOperation) occurs on
any particular LRO.
Fixes #5406.

fix(spanner/spannertest): Improve DDL application delay cancellation.

---

internal/gapicgen/gensnippets/model.go

test(internal/gapicgen): add missing header

---

spanner/oc_test.go

Fix: https://github.com/googleapis/google-cloud-go/issues/5871

chore(spanner): fix flaky test in oc_stats.go

---

compute/apiv1/smoke_test.go

test(compute): increase time for flaky test

---

storage/client_test.go
storage/grpc_client.go
storage/http_client.go

This adds DeleteBucketACL and DeleteDefaultObjectACL implementation

chore(storage): implement DeleteBucketACL and DeleteDefaultObjectACL

---

civil/civil.go
civil/civil_test.go

chore(civil): refactor methods to use consistent receiver names

---

logging/logging.go
logging/logging_test.go

retrieve trace information from `traceparent` header.
if both `traceparent` and `x-cloud-trace-context` headers exist in the request, read the info from the `traceparent` header.
do not set traceSampled flag based on the `traceparent` header.

feat(logging): retrieve trace info from traceparent

---

spanner/integration_test.go

chore(spanner): skip a test that seems to cause timeout issues

---

bigquery/CHANGES.md

Picks up #6249, a minor fix to testing

fix(bigquery): release 1.34.1

---

compute/apiv1/smoke_test.go

Operations should be waited on and not just created. This was causing
tests to fail because the operation was finishing silently and then
subsquent delete operations could not find the resulting instance
that had already been deleted.
Fixes: #5988

test(compute): wait on operations and don't retry them

---

bigtable/bigtable.go
bigtable/bigtable_test.go
bigtable/integration_test.go

chore: switched app_profile to app_profile_id

---

.github/workflows/sync_branch.yaml

chore(ci): skip sync job on foks

---

.github/sync-repo-settings.yaml

chore(settings): revert enablement of merge commit

---

storage/storage.go

Migrate Object metadata operations to transport-agnostic interface. Integration tests pass locally
- GetObject
- UpdateObject
- DeleteObject

chore(storage): migrate object metadata operations

---

bigquery/integration_test.go

Followup to contribution: https://github.com/googleapis/google-cloud-go/pull/6256

test(bigquery): add testing for email propagation in job retrieval

---

compute/metadata/metadata.go

feat(compute/metadata): add http timeout to metadata client

---

storage/go.mod
storage/go.sum

Bump dependency to pull in pointer field update for Lifecycle
from googleapis/google-api-go-client#1598
Updates #6204

chore(storage): bump apiary dependency

---

pubsub/streaming_pull_test.go

test(pubsub): fix race condition in streaming pull retry test

---

storage/integration_test.go

Fixes #6579, fixes #6578, fixes #6577, fixes #6576

test(storage): fixes bugs introduced in #6510

---

internal/gapicgen/generator/config.go

Related: internal cl/470834366

chore: update reference to analyticshub service config file

---

datastore/integration_test.go

test(datastore): uncomments in, not-in, and != tests

---

storage/bucket.go

chore(storage): prep RetentionPeriod for proto3 optional

---

storage/integration_test.go

Reverts googleapis/google-cloud-go#6768
This PR broke some tests in the CI, reverting until we have a good fix

Revert "test(storage): add tokensource to GRPC client creation"

---

storage/bucket.go

chore(storage): fix retention_period type change

---

firestore/integration_test.go

chore(firestore): disabled flaky read time test

---

pubsub/subscription.go

docs(pubsub): update subscription retry policy defaults

---

bigtable/integration_test.go

chore(bigtable): fix AdminBackup ... again

---

bigtable/bigtable_test.go
bigtable/bttest/inmem.go

chore(bigtable/bttest): Add read stats to the emulator and a simple test

---

spanner/integration_test.go
spanner/value.go
spanner/value_test.go

This PR adds support for handling null values in array of proto columns.

feat(spanner): add support for handling null values in array of proto columns

---

pubsublite/pscompat/integration_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/7001

test(pubsublite): fix flaky TestIntegration_PublishSubscribeSinglePartition

---

compute/metadata/metadata.go

fix(compute/metadata): switch DNS lookup to an absolute lookup

---

internal/godocfx/go.mod
internal/godocfx/go.sum
internal/godocfx/godocfx_test.go
internal/godocfx/testdata/golden/index.yml
internal/godocfx/testdata/golden/pkg-readme.md

The docs build is failing because of a missing `go.sum` entry.

chore(internal/godocfx): go mod tidy

---

bigtable/integration_test.go

- Allow read stats integration tests to use the emulator.
- Relax the checks for CellsSeenCount and RowsSeenCount.

test(bigtable): improve read stats integration tests

---

spanner/internal/testutil/inmem_spanner_server.go

[Logs](https://source.cloud.google.com/results/invocations/f81a2a96-3b1c-458c-a330-92b5aab42e78/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Flatest-version/log)

fix(spanner): fix integration tests data race

---

.github/.OwlBot.lock.yaml

chore: update docker digest

---

bigquery/dataset_integration_test.go

Resolves flaky tests from https://github.com/googleapis/google-cloud-go/issues/7254

fix(bigquery): create/update an isolated dataset for collation feature

---

.github/.OwlBot.yaml
internal/gapicgen/generator/config.go

chore: disable oslogin owlbot gen

---

longrunning/longrunning.go
longrunning/longrunning_test.go

fix(longrunning): properly parse errors with apierror

---

storage/go.mod
storage/go.sum

chore: revert broken google.golang.org/api to working rev

---

spanner/spansql/parser.go
spanner/spansql/parser_test.go
spanner/spansql/sql.go
spanner/spansql/sql_test.go
spanner/spansql/types.go

feat(spanner/spansql): add support for missing DDL syntax for ALTER CHANGE STREAM

---

.github/.OwlBot.yaml

chore: onboard oslogin/common

---

storage/integration_test.go

These are also doing bucket updates and I missed them in #7476.
Updates #7483
Updates #7484

test(storage): skip 2 more tests for gRPC

---

.github/.OwlBot.yaml

chore: fix syntax in owlbot

---

edgecontainer/CHANGES.md

feat(edgecontainer): promote to GA

---

storage/internal/test/conformance/v4_signatures.json

chore(storage): update signed url conformance test cases

---

run/CHANGES.md

feat(run): promote to GA

---

apikeys/CHANGES.md

feat(apikeys): promote to GA

---

maps/CHANGES.md

feat(maps): promote to GA

---

gkebackup/CHANGES.md

feat(gkebackup): promote to GA

---

baremetalsolution/CHANGES.md

feat(baremetalsolution): promote to GA

---

batch/CHANGES.md

feat(batch): promote to GA

---

.github/.OwlBot.yaml

chore: reenable maps gen

---

.github/.OwlBot.yaml
internal/gapicgen/generator/config.go
internal/postprocessor/config.yaml

Backend changes have been made to fix the package name
Fixes: #7366

chore: reenable eventarc/publishing v1

---

.github/.OwlBot.yaml

chore(ci): fix owlbot config syntax

---

.github/.OwlBot.lock.yaml
internal/postprocessor/main.go

Tested locally and generates fine after changes.

chore(internal/postprocessor): fix version file package

---

alloydb/CHANGES.md

feat(alloydb): promote to GA

---

.github/.OwlBot.lock.yaml

chore(internal/postprocessor): update postprocessor container SHA in OwlBot.lock.yaml

---

storage/integration_test.go

Finishing off these tests for gRPC. One test has to be skipped for gRPC because credential capture logic in the client constructor is not present in the gRPC constructor. I'll file an issue for this if there isn't one already.
Addressed feedback from #6858

chore(storage): migrate SignedURL tests

---

storage/integration_test.go

This method was unused after #7776

chore(storage): clean up unused test func

---

.github/.OwlBot.lock.yaml
.github/.OwlBot.yaml
internal/postprocessor/config.go
internal/postprocessor/config.yaml
internal/postprocessor/main.go

* Fixes post-processor for OwlBot.yaml paths to root dir / for snippets
refs: #7850

chore(internal/postprocessor): add support for root dir OwlBot dest

---

support/CHANGES.md

sources were generated in #7875

feat(support): start generating apiv2

---

internal/postprocessor/execv/gocmd/gocmd.go
internal/postprocessor/main.go

chore(internal/postprocessor): add modEditReplaceInSnippets for new modules

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

This reverts commit 463c59ae9d9b8b92b4f357cf6f12a92fcd169e2c.

chore(maps/places): Revert "chore(maps/places): add config to generate apiv1 (#7909)"

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

restore #7909
This reverts commit 3b50ab2ad832e4f9dc57906fe39a2c88a4ab3176.

chore(maps/places): add config to generate apiv1

---

maps/CHANGES.md

sources were generated in #7918

feat(maps/places): start generating apiv1

---

internal/godocfx/testdata/golden/index.yml

chore(internal/godocfx): update testdata/golden/index.yml

---

.github/workflows/vet.sh

test: fix tidy check to match all mod files

---

internal/gapicgen/cmd/genbot/Dockerfile
internal/gapicgen/cmd/genbot/local.go
internal/gapicgen/cmd/genbot/main.go
internal/gapicgen/generator/generator.go
internal/gapicgen/generator/genproto.go

- Fix error: "Tried to write the same file twice."
- remove some cruft
- skip ai libs until we explicitly onboard
- update some deps

chore: fix genbot

---

rapidmigrationassessment/go.sum
storageinsights/go.sum
support/go.sum

fix(rapidmigrationassessment): fix go.sum
fix(storageinsights): fix go.sum
fix(support): fix go.sum

chore: fix some sums

---

firestore/query.go

chore(firestore): gofmt query.go

---

.github/.OwlBot.lock.yaml

Contains at least the updates from #8101

chore(owlbot): update postprocessor sha

---

internal/postprocessor/manifest.go

chore(postprocessor): fix missing format specifier

---

internal/generated/snippets/go.mod
internal/generated/snippets/go.sum
internal/godocfx/godocfx_test.go

This test always fails on dep bump. In the future lets evaluate if it is worth keeping around at all. But for now lets skip it.

test: skip flaky test

---

ai/CHANGES.md

sources were generated in #8212

feat(ai/generativelanguage): start generating apiv1beta2

---

confidentialcomputing/CHANGES.md

feat(confidentialcomputing): promote to GA

---

gkemulticloud/CHANGES.md

feat(gkemulticloud): promote to GA

---

rapidmigrationassessment/CHANGES.md

feat(rapidmigrationassessment): promote to GA

---

vmwareengine/CHANGES.md

feat(vmwareengine): promote to GA

---

support/CHANGES.md

feat(support): promote to GA

---

discoveryengine/CHANGES.md

feat(discoveryengine): promote to GA

---

.github/.OwlBot.yaml
.release-please-manifest-submodules.json
internal/postprocessor/config.yaml
release-please-config-yoshi-submodules.json

This reverts commit 4d6247bdb5c86afcfcaf12179802dc390649b59f.

chore(netapp): Revert "add config to generate apiv1beta1 (#8300)"

---

commerce/CHANGES.md

sources were generated in #8318,#8320

feat(commerce): start generating apiv1

---

policysimulator/CHANGES.md

sources were generated in #8335,#8337

feat(policysimulator): start generating apiv1

---

netapp/CHANGES.md

sources were generated in #8346

feat(netapp): start generating apiv1

---

bigquery/CHANGES.md

sources were generated in #8426,#8430

feat(bigquery/biglake): start generating apiv1 and apiv1alpha1

---

language/CHANGES.md

sources were generated in #8425,#8430

feat(language): start generating apiv2

---

policytroubleshooter/CHANGES.md

sources were generated in #8436,#8438

feat(policytroubleshooter/iam): start generating apiv3

---

pubsublite/internal/wire/publisher_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/7942

test(pubsublite): fix flaky TestRoutingPublisherUnloadIdlePublisher

---

bigtable/internal/option/option.go

fix(bigtable): add missing veneer header

---

auth/detect/compute.go
auth/detect/example_test.go
auth/detect/internal/externalaccount/aws_provider.go
auth/example_test.go
auth/impersonate/integration_test.go
auth/internal/testutil/testdns/dns.go
auth/internal/testutil/testgcs/storage.go
auth/internal/testutil/testutil.go

fixup various small todos, still more to come

chore(auth): cleanup some small todos

---

alloydb/CHANGES.md

sources were generated in #8636

feat(alloydb): start generating connectors apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(shopping/merchant/inventories): add config to generate apiv1beta

---

spanner/internal/testutil/inmem_spanner_server.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/8590

test(spanner): fix data race issue in inmemory spanner test runs

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(maps/fleetengine): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(maps/fleetengine/delivery): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(securesourcemanager): add config to generate apiv1

---

.release-please-manifest-submodules.json
auth/oauth2adapt/go.mod
auth/oauth2adapt/go.sum
go.work.sum
internal/generated/snippets/go.mod
internal/generated/snippets/go.sum

Also ran go mod tidy, hence the other changes

feat(auth/oauth2adapt): fixup deps for release

---

CHANGES.md
internal/actions/cmd/updateall/main.go

Do not create nested commit for root module

chore(internal/actions): fix updateall

---

internal/godocfx/testdata/golden/index.yml

chore(internal/godocfx): update godocfx golden

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(cloudquotas): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

This reverts commit b3cc26b34bcf8f60f752c4eb313691b8f6947d91.

chore(cloudquotas): Revert "add config to generate apiv1 (#8766)"

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(redis/cluster): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(edgenetwork): add config to generate apiv1

---

.github/workflows/apidiff.yml

Also fix what I believe was a syntax error in if -- at least my editor thought so.
Fixes: #9004

chore: update script to be more secure

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(cloudprofiler): add config to generate apiv2

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(telcoautomation): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(discoveryengine): add config to generate apiv1alpha

---

httpreplay/cmd/httpr/integration_test.go

chore(httpreplay): add retries to Get

---

vertexai/genai/client.go
vertexai/genai/client_test.go

Makes live tests a bit more permissive to model changes

fix(vertexai): set up endpoint and fix test

---

vertexai/genai/aiplatformpb_wrapper.gen.go
vertexai/genai/chat.go
vertexai/genai/client.go
vertexai/genai/client_test.go
vertexai/genai/count_tokens.go

Add support for the CountTokens RPC.

feat(vertexai): add CountTokens

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(ai/generativelanguage): add config to generate apiv1 and apiv1beta

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(shopping/css): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(apps/meet): add config to generate apiv2beta

---

vertexai/README.md
vertexai/genai/example_test.go

Marking this as feat to trigger a release to update examples on pkgsite

feat(vertexai): fix README link and add example comments

---

.github/.OwlBot.lock.yaml

chore(owlbot): update postprocessor version

---

internal/gapicgen/git/git_test.go

chore(internal/gapicgen/git): fix TestFormatChanges

---

spanner/row.go
spanner/row_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/9381

fix(spanner): support time.Time and other custom types using SelectAll

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(parallelstore): add config to generate apiv1beta

---

spanner/row.go
spanner/row_test.go

feat(spanner): SelectAll struct spanner tag annotation match should be case-insensitive

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

This reverts commit 2577611c5d4a000628ea21373039bc652e52ceee.

chore(chat): revert "add config to generate apiv1 (#9480)"

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(cloudcontrolspartner): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(apphub): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(secretmanager): add config to generate apiv1beta2

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(storage/control): add config to generate apiv2

---

secretmanager/CHANGES.md

sources were generated in #9593

feat(secretmanager): new client apiv1beta2

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(cloudcontrolspartner): add config to generate apiv1beta

---

internal/actions/cmd/changefinder/README.md

Add missing `base` flag to example.

chore(internal/actions/cmd/changefinder): update readme

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

feat(backupdr): start generating backupdr v1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(shopping/merchant/reports): add config to generate apiv1beta

---

internal/gapicgen/generator/genproto.go

Build https://github.com/googleapis/googleapis/tree/master/google/apps/card/v1 to [go-genproto](https://github.com/googleapis/go-genproto).

chore(internal/gapicgen): add apps/card/v1 to go-genproto allowlist

---

rpcreplay/rpcreplay.go

fix(rpcreplay): properly unmarshal dynamic message

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(identitytoolkit): onboard apiv2

---

auth/grpctransport/grpctransport.go
auth/grpctransport/grpctransport_test.go
auth/httptransport/httptransport.go
auth/httptransport/httptransport_test.go

fix(auth): add internal opt to skip validation on transports

---

auth/grpctransport/grpctransport.go

fix(auth): set secure flag for gRPC conn pools

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(shopping/merchant/conversions): add config to generate apiv1beta

---

spanner/client_test.go
spanner/sessionclient_test.go

chore(spanner): temporarily skip spanner tests

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(maps/solar): add config to generate apiv1

---

internal/actions/cmd/thirdpartycheck/main.go

chore(thirdparty): remove json-iterator exemption

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(maps/routeoptimization): add config to generate apiv1

---

.release-please-manifest-submodules.json
internal/postprocessor/releaseplease.go
release-please-config-yoshi-submodules.json

Arrange things so that release-please will create a release-bump
PR when the ai module is updated.

chore(internal/postprocessor): add ai to individuallyReleasedModules

---

storage/integration_test.go

test(storage): increase ctx timeout for requesterpays test

---

.github/.OwlBot.lock.yaml

chore(internal/postprocessor): update postprocessor version

---

commerce/CHANGES.md

chore(commerce): promote to GA v1.0.0

---

config/CHANGES.md

chore(config): promote to GA v1.0.0

---

servicehealth/CHANGES.md

chore(servicehealth): promote to GA v1.0.0

---

netapp/CHANGES.md

chore(netapp): promote to GA v1.0.0

---

migrationcenter/CHANGES.md

chore(migrationcenter): promote to GA v1.0.0

---

workstations/CHANGES.md

chore(workstations): promote to GA v1.0.0

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(publicca): start generating v1

---

storage/go.mod
storage/go.sum
storage/integration_test.go

test(storage): fix OC span test

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore: onboard managedkafka client gen

---

internal/fields/fields_test.go

Failure started from this PR: https://github.com/googleapis/google-cloud-go/pull/10223
https://github.com/googleapis/google-cloud-go/pull/10223/files#diff-95bcb082e60afe7a5a57d47380031f659be53207a3d7b522c90d05e2bffa4f71L205-L206

test(internal/fields): fix NoTags test

---

storage/integration_test.go

test(storage): do not fail on precondition failure for bucket updates

---

internal/protoveneer/cmd/protoveneer/protoveneer.go
internal/protoveneer/cmd/protoveneer/testdata/basic/basic.pb.go
internal/protoveneer/cmd/protoveneer/testdata/basic/golden
internal/protoveneer/support/support.go

Automatically convert the durationpb.Duration protobuf
into a time.Duration.

chore(internal/protoveneer): support Duration

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

BEGIN_NESTED_COMMIT
chore(networkservices): add config to generate apiv1
PiperOrigin-RevId: 638948066
END_NESTED_COMMIT
BEGIN_NESTED_COMMIT
chore(shopping/merchant/accounts): add config to generate apiv1beta
PiperOrigin-RevId: 638990704
END_NESTED_COMMIT
BEGIN_NESTED_COMMIT
chore(shopping/merchant/datasources): add config to generate apiv1beta
PiperOrigin-RevId: 638989368
END_NESTED_COMMIT
BEGIN_NESTED_COMMIT
chore(shopping/merchant/products): add config to generate apiv1beta
PiperOrigin-RevId: 638989603
END_NESTED_COMMIT
BEGIN_NESTED_COMMIT
chore(shopping/merchant/promotions): add config to generate apiv1beta
PiperOrigin-RevId: 638990205
END_NESTED_COMMIT

chore(internal/postprocessor): add config to generate networkservices and shopping/merchant clients

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(privilegedaccessmanager): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

This reverts commit 30b25f36e74cf089c8cacee046a714b57a716f68.

chore(privilegedaccessmanager): revert add config to generate apiv1 (#10316)

---

.github/.OwlBot.lock.yaml

Updating lock file to newer image tagging scheme from #10341 
Internal issue http://b/334181347

chore(internal/postprocessor): update to newly tagged image

---

vertexai/genai/chat.go
vertexai/genai/chat_test.go

Followup on review comments in #10355

chore(vertexai): clean up utility function and add tests

---

internal/protoveneer/cmd/protoveneer/config.go
internal/protoveneer/cmd/protoveneer/protoveneer.go
internal/protoveneer/cmd/protoveneer/testdata/basic/basic.pb.go
internal/protoveneer/cmd/protoveneer/testdata/basic/config.yaml
internal/protoveneer/cmd/protoveneer/testdata/basic/golden

Add the ability to customize doc comments for struct fields.

chore(internal/protoveneer): doc for fields

---

internal/protoveneer/cmd/protoveneer/config.go
internal/protoveneer/cmd/protoveneer/converters.go
internal/protoveneer/cmd/protoveneer/internal/support/support.go
internal/protoveneer/cmd/protoveneer/internal/support/support_test.go
internal/protoveneer/cmd/protoveneer/protoveneer.go
internal/protoveneer/cmd/protoveneer/protoveneer_test.go
internal/protoveneer/cmd/protoveneer/testdata/basic/config.yaml
internal/protoveneer/cmd/protoveneer/testdata/basic/golden

Generate the support functions along with the rest of the code,
instead of requiring a separate package.

chore(internal/protoveneer): generate support functions

---

auth/auth.go
auth/auth_test.go

fix(auth): fetch initial token when CachedTokenProviderOptions.DisableAutoRefresh is true

---

spanner/session.go

Internal bug: b/343756862
Previous work: https://github.com/googleapis/google-cloud-go/pull/10449

fix(spanner): healthCheck should not decrement num_in_use sessions

---

storage/transfermanager/integration_test.go

test(storage/transfermanager): add CRC to test

---

vertexai/genai/caching_test.go
vertexai/genai/chat.go
vertexai/genai/client.go
vertexai/genai/client_test.go
vertexai/genai/content.go
vertexai/genai/example_test.go

Similar to the one added to the Google AI SDK

vertexai: add NewUserContent helper function

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(apihub): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(gkeconnect/gateway): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(bigquery/storage): add v1alpha config

---

bigquery/integration_test.go
bigquery/value.go

fix(bigquery): properly handle RANGE type arrays

---

bigtable/bigtable.go

Reverting https://github.com/googleapis/google-cloud-go/pull/10766
Fixes: [b/368446380](b/368446380)

fix(bigtable): Rollback new auth library

---

spanner/metrics.go
spanner/transaction_test.go

Found by staticcheck, related #10779

fix(spanner): handle errors

---

pubsub/topic.go
pubsub/topic_test.go

Adds support for Cloud Storage ingestion in topic create/update.

feat(pubsub): add support for cloud storage ingestion topics

---

spanner/metrics.go
spanner/metrics_test.go

Related PR: https://github.com/googleapis/java-spanner/pull/3357

chore(spanner): generate client_hash metric attribute using FNV

---

doc.go

docs: add missing option link

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(parallelstore): add config to generate apiv1

---

auth/credentials/impersonate/impersonate.go

chore(auth): restore endpoint googleapis.com to user and ID token impersonate

---

internal/kokoro/populate-secrets.sh
internal/kokoro/trampoline.sh

1) support dynamic location for project secrets
2)support docker authorization including artifacy registry

chore: update build scripts to be able to support migration to use release kokoro pool

---

spanner/metrics.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/11080

fix(spanner): skip exporting metrics if attempt or operation is not captured.

---

spanner/metrics_monitoring_exporter.go

Related Java PR: https://github.com/googleapis/java-spanner/pull/3447
Existing behavior
After PR merge

chore(spanner): add details to fix permission error in native metrics

---

firestore/integration_test.go
firestore/query.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/10665

fix(firestore): Allow using != with nil

---

storage/integration_test.go

test(storage): skip direct connectivity test

---

managedkafka/README.md

Aligns with `title` in https://github.com/googleapis/googleapis/commit/e813a85a1455e44c4c93314d8c2fdf3d77516916

docs(managedkafka): update title in README

---

auth/oauth2adapt/oauth2adapt.go

fix(auth/oauth2adapt): copy map in tokenSourceAdapter.Token

---

spanner/test/opentelemetry/test/go.mod
spanner/test/opentelemetry/test/ot_traces_test.go

chore(spanner): remove deprecated usages of internal/trace from tests

---

storage/integration_test.go

test(storage): fix trace span test

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore: start generating memorystore v1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore: start generating memorystore v1beta

---

storage/integration_test.go

https://github.com/googleapis/google-cloud-go/issues/11333

test(storage): skip MetricsEnablementInGCE

---

storage/integration_test.go

test(storage): fix flaky soft delete update

---

storage/trace_test.go

Only run test under emulator environment
Fixes #11480

test(storage): run emulated test only against emulator

---

CHANGES.md

fix: remove OpenCensus dependency

---

storage/grpc_client.go

Fixes #11531
L1706 clones the struct since we are changing it on L1708
Also moved this code since it doesn't need to be done in the loop.

fix(storage): clone the defaultRetry to avoid modifying it directly

---

internal/godocfx/index.go
internal/godocfx/index_test.go
internal/godocfx/main.go

I refactored the index client a bit to use a URL that can be faked out for testing.
I also confirmed this properly queries the index by running it locally.

fix(internal/godocfx): don't save timestamps until modules are successfully processed

---

.github/.OwlBot.lock.yaml

chore(.github): update post-processor image

---

spanner/metrics_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/11178

test(spanner): fix continuous test failure

---

storage/integration_test.go

test(storage): fix flaky SoftDelete integration test

---

spanner/spansql/parser.go

chore: fix failing vet checks

---

internal/kokoro/continuous.sh

chore: skip benchmark for all env

---

spanner/transaction.go
spanner/transaction_test.go

This PR adds support for multiplexed sessions in ReadWriteStmtBasedTransaction

feat(spanner): support multiplexed sessions for ReadWriteStmtBasedTransaction

---

spanner/benchmarks/benchmarks.go

1. Added support for point read
2. Update timer to show hours/minutes/seconds

ci(spanner): Add support for point reads in benchmarking

---

spanner/benchmarks/benchmarks.go

1. Change validation on number of arguments to 6
2. rename transactionType variable to avoid shadowing
3. throw an error if invalid transaction type is passed
4. uppercase transaction type to be passed in command line

ci(spanner): Update benchmarking script with error handling

---

spanner/benchmarks/benchmarks.go

* Supported configuring production and devel environments
* Optimize script to return Duration instead of accessing microseconds everywhere
* Updated the Employees table schema for reference

ci(spanner): Support configuring cloud environment in benchmarking script

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(iam): add config to generate apiv3

---

storage/integration_test.go

This test still works locally but it's blocked from running in kokoro for now.
Updates #11956

test(storage): skip Writer Append test

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(devicestreaming): add config to generate apiv1

---

storage/example_test.go

Add examples for Writer.Flush and
ObjectHandle.NewWriterFromAppendableObject

doc(storage): add examples for appendable writes

---

internal/generated/snippets/go.mod

…
fixes: 11998
fixes: 11999
fixes: 12000
fixes: 12001
fixes: 12002
fixes: 12003

chore(internal/generated/snippets): add dependency on cloud.google.com/go/devicestreaming

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(lustre): add config to generate apiv1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(shopping/merchant/ordertracking): add config to generate apiv1beta

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(chronicle): add config to generate apiv1

---

storage/retry_conformance_test.go

Add a retry conformance test for writer.Flush.

test(storage): retry conformance test for flush

---

spanner/client_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/12084
https://btx.cloud.google.com/invocations/9b8f5234-e6ca-4f4c-a134-3a6d527d6e9e/log

test(spanner): fix flakiness in context timeout error

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(storagebatchoperations): generate library

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(bigquery): generate storage v1beta library

---

bigtable/integration_test.go

Fixes [11825](https://github.com/googleapis/google-cloud-go/issues/11825)

test(bigtable): fix mv data test

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(compute): start generating apiv1beta

---

logging/internal/testing/fake_test.go
logging/logadmin/logadmin_test.go
logging/logging_test.go

chore(logging): replace deprecated grpc.WithInsecure

---

bigquery/v2/CHANGES.md

another minor commit to validate release behavior
Release-As: 2.0.0-alpha1

feat(bigquery/v2): bump to 2.x alpha

---

bigquery/v2/doc.go

feat(bigquery/v2): rev alpha version

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(maintenance/api): add config to generate apiv1beta

---

spanner/row_test.go
spanner/value.go

Decode double pointer custom struct.
FIX #12495

fix(spanner): pointer type custom struct decoder

---

storage/integration_test.go

Fix test case that was broken in previous commit.
Fixes #12584

test(storage): fix Reader integration test

---

.github/.OwlBot.lock.yaml

Update owlbot lock, to pickup changes from PR #12595.

chore: update owlbot lock

---

spanner/integration_test.go
spanner/regression_test.go

**Description:**
1. AFE header is passed for directpath requests
2. Disable Trailers related tests for directpath (b/422916293)

ci(spanner): Fix directpath nightly jobs in spanner

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

PiperOrigin-RevId: 790685328
PiperOrigin-RevId: 790723312
PiperOrigin-RevId: 790723279
PiperOrigin-RevId: 790723245
PiperOrigin-RevId: 790778741
PiperOrigin-RevId: 790778653
PiperOrigin-RevId: 790874101
PiperOrigin-RevId: 742706119

chore(shopping): new libraries

---

compute/metadata/metadata.go
compute/metadata/metadata_test.go

* Enable use of custom logger combined with default internal shared http.Client to support sharing a single TCP connection pool across requests as is done in functions such as GetWithContext.
refs: #11078
The addition of logging capabilities to the metadata client in ([PR #11078](https://github.com/googleapis/google-cloud-go/pull/11078)) introduced two unintended side effects:
1.  Connection proliferation: Client code in `auth` previously used a default shared `http.Client` via the `GetWithContext` function, which efficiently pooled TCP connections to the metadata server. The new `NewWithOptions` function instead creates new, isolated `http.Client` instances by default. While safer from a configuration standpoint, this led to a proliferation of connections, causing resource exhaustion.
2. …

feat(compute/metadata): add Options.UseDefaultClient

---

spanner/go.mod

feat(spanner): release spanner 1.84.1

---

storage/storage.go

This is no longer a requirement (b/331724775#comment39)

doc(storage): remove HNS requirement from MoveObject docs

---

internal/librariangen/librariangen.log
internal/librariangen/request/request.go
internal/librariangen/request/request_test.go
internal/librariangen/testdata/.librarian/state.yaml
internal/librariangen/testdata/librarian/generate-request.json

closes: googleapis/librarian#1515

fix(internal/librariangen): update source_paths to source_roots in generate-request.json

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(managedkafka): onboard schemaregistry v1

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

PiperOrigin-RevId: 791184292
PiperOrigin-RevId: 791185257
PiperOrigin-RevId: 791134255
PiperOrigin-RevId: 791137429
PiperOrigin-RevId: 791137587

chore(shopping): onboard new shopping clients

---

internal/librariangen/Dockerfile
internal/librariangen/testdata/.librarian/state.yaml

* Update state.yaml test fixture to actual Librarian output

fix(internal/librariangen): fix Dockerfile permissions for go mod tidy

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(bigquery/datapolicies): add config to generate apiv2

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(geminidataanalytics): add config to generate apiv1beta

---

bigtable/integration_test.go

Add retries
Fixes: https://github.com/googleapis/google-cloud-go/issues/12381

test(bigtable): Add more retries to verification of AdminBackup test

---

storage/doc.go

doc(storage): clarify direct path docs

---

internal/librariangen/execv/execv_test.go
internal/librariangen/postprocessor/postprocessor.go
internal/librariangen/release/release.go
internal/librariangen/release/release_test.go

fix(internal/librariangen): fix goimports errors

---

release-please-config-individual.json

chore(pubsub): reconfigure pubsub v1 release definition

---

internal/librariangen/main.go
internal/librariangen/main_test.go

Fixes https://github.com/googleapis/librarian/issues/1960

fix(internal/librariangen): test for error path with flags

---

internal/librariangen/release/release.go
internal/librariangen/release/release_test.go

This should only be merged once
https://github.com/googleapis/librarian/pull/2037 is merged - but merged as soon as possible after that...

fix(librariangen): honor original container contract

---

.github/.OwlBot.lock.yaml

chore: bump postprocessor image

---

.github/.OwlBot.yaml
internal/postprocessor/config.yaml

chore(locationfinder): add config to generate apiv1

---

firestore/bulkwriter.go
firestore/bulkwriter_test.go
firestore/mock_test.go

Fixes: https://github.com/googleapis/google-cloud-go/issues/12444
This PR resolves a concurrent map read and map write panic in BulkWriter when it's used from multiple goroutines.
**Problem**
The docUpdatePaths map, which tracks documents already added to the writer, was not protected by a mutex. Concurrent calls to BulkWriter.Create, BulkWriter.Set, etc., would all call checkWriteConditions, leading to simultaneous writes to this map and causing a fatal race condition.
**Solution**
This PR introduces a new docUpdatePathsLock sync.Mutex to the BulkWriter struct.
This new lock is used exclusively within the checkWriteConditions function to wrap the read and write operations on the docUpdatePaths map. This ensures all access to the map is thread-safe.
This approach resolves the race …

fix(firestore): Add dedicated lock to BulkWriter to prevent race

---

bigquery/v2/query/query_integration_test.go

ci(bigquery/v2): fix race condition on query cancel test

---

.github/.OwlBot.lock.yaml

chore(.github): bump owlbot post processor

---

.librarian/state.yaml

* Add exclusion of iam_policy_client to batch.
* Bump last_generated_commit for longrunning to avoid
duplicating a change concurrently applied by OwlBot.

chore(.librarian): special-case fixes in state.yaml
