googleapis/google-cloud-go

examples/storage/appengine/app.yaml
To support the "gcloud app deploy" commands that all the App Engine docs now use (standard and flexible env.). This is the particular document affected:
https://cloud.google.com/appengine/docs/standard/go/googlecloudstorageclient/app-engine-cloud-storage-sample#code_walkthrough
=> Removing "application:" and "version:"

.github/pull_request_template.md
We now accept pull requests. This template is obsolete.
=> .github: remove pull request template

compute/metadata/metadata.go
Tested changes on GCE to make sure this fixed the leak.
Fixes: #2417
=> compute/metadata: pass cancelable context to DNS lookup

spanner/integration_test.go
Fixes #2393 
Suggested by https://github.com/googleapis/google-cloud-go/issues/1964#issuecomment-641170794
=> spanner: fix TestIntegration_StartBackupOperation test

pubsub/integration_test.go
Unflake TestIntegration_All by giving each test run a unique topic/subscription pair. Previously, tests were failing due to issues with overlapping publishes (messages published by one instance of `testPublishAndReceive` were being consumed by another test).
On a local machine, this results in a 2.3x increase in running time, from 30s to 70s but should reduce test flakiness.
Fixes #1840
=> pubsub: unflake TestIntegration_All

internal/gapicgen/cmd/genbot/github.go, internal/gapicgen/cmd/genbot/main.go
Trying to figure out why the pull requests are happening with every
re-generation. I am guessing something is wrong with the time
check, but I don't know what yet. Adding more logging to debug.
Also, fixed a bug where the status of a PR being searched for was
not being accounted for.
=> internal/gapicgen: add more logging and fix pr status bug

pubsub/topic.go
When Topic.ResumePublish is called before Publish,
the underlying scheduler is not initialized yet, leading to a panic.
This patch makes sure the scheduler is initialized by calling initBundler.
=> pubsub: fix panic on Topic.ResumePublish

storage/integration_test.go
Updating the default bucket ACL will only apploy that ACL to
newly created objects. Therefore, the retry here is ineffective
unless the object write is retried as well.
Fixes #2453
=> storage: unflake TestIntegration_ACL

spanner/spannertest/db_eval.go, spanner/spannertest/db_test.go
This was broken for BYTES, DATE and TIMESTAMP types.
Fixes #2458.
=> spanner/spannertest: fix evaluation on IN

compute/metadata/metadata.go
This is partial revert of https://github.com/googleapis/google-cloud-go/commit/7fd52cfe4c3ca33880ed92441d7e6f7a7babe803 when intention there was to add cancelable context, it also changed LookupHost to LookupAddr. It started causing issues for example: https://issuetracker.google.com/issues/159053735
LookupHost : https://golang.org/pkg/net/#Resolver.LookupHost -> DNS lookup
LookupAddr : https://golang.org/pkg/net/#Resolver.LookupAddr -> reverse DNS lookup
=> compute/metadata: Fix detecting metadata server

storage/integration_test.go
This should no longer be necessary to retry now that we have
addressed gaps in retries for the write operation.
Fixes #2395
=> storage: remove retry for write integration test

spanner/emulator_test.sh, spanner/integration_test.go
Changes:
- Skip tests that are supported in emulator 0.8.0. 
- Upgrade the emulator version in presubmit to 0.8.0.
=> spanner: unskip tests for emulator 0.8.0.

spanner/client_test.go, spanner/read.go, spanner/retry.go
Reference: https://github.com/googleapis/java-spanner/blob/f89da6a1f4f8a86c136a23dfd2f5b073dd65407a/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java#L257-L269
Fixes #2443
=> spanner: only retry certain types of internal errors.

spanner/integration_test.go
A read/write transaction should always return any error to the transaction runner and let it determine whether it should be returned to the user application, or it should cause a transaction retry. Failing to do so, can cause the transaction to fail sometimes with an Aborted error.
Fixes #2486
=> test(spanner): return err from tx

internal/gapicgen/cmd/genbot/github.go
Right now #2510 is breaking our automation. Let's try harder to
make sure this does not happen in the future.
=> fix(internal/gapicgen): make PR search more specific

internal/kokoro/vet.sh
This is already in the image. Unblocks #2564.
=> fix(internal/kokoro): remove install of staticcheck

spanner/cmp_test.go, spanner/transaction_test.go
=> fix(spanner): add extra field to ignore with cmp and use testEqual

bigquery/iterator.go
Refines the RowIterator to discard an extra schema reference that
doesn't need to be retained.
=> bigquery: address cached reference in rowiterator

spanner/client.go, spanner/client_test.go, spanner/sessionclient.go, spanner/sessionclient_test.go
Changes included are: 
- Add a field `CallOptions` in `ClientConfig`.
- Add a field `callOptions` in `sessionClient`.
- Add a method `mergeCallOptions` to merge two CallOptions.
- Update `nextClient` in sessionclient.go so that if a custom CallOptions is provided, merge it with the default one. 
Fixes #2594
=> feat(spanner): support of client-level custom retry settings

CONTRIBUTING.md
Adds an explicit mention to enable "Allow edits by maintainers" when
setting up the pull request.  In PR #2574 (external contribution) it was
discovered this cannot be added after the fact for org-based forks, only
user-based.
As there's not a great reference link for this in the github docs that
doesn't descend into a bunch of organization permissions management, I'm
not calling this specific circumstance explicitly.
=> docs: update CONTRIBUTING.md with some PR setup info

pubsub/pubsub.go
Back in February 2020, `google.golang.org/api/transport/grpc` switched to using a single grpc connection for `Dial` starting in [v0.20.0](https://github.com/googleapis/google-api-go-client/blob/v0.20.0/transport/grpc/dial.go#L46). While the publisher client started to use `DialPool`, the subscriber client did not switch to connection pooling. This was causing an issue where number of open streams was being capped at about 100.
This change has the additional effect of separating the previously shared connection between publisher and subscriber, which should have a minimal effect on most uers.
Fixes #2593
=> fix(pubsub): use grpc conn pool option for subscriber client

internal/version/version.go, pubsub/CHANGES.md
This commit will be tagged pubsub/v1.6.0
=> chore: release pubsub/v1.6.0

profiler/proftest/proftest.go, profiler/proftest/proftest_test.go
Without this change,  milliseconds are parsed as minutes.
=> fix(profiler): fix order of units in regexp used to parse backoff duration

internal/version/version.go, pubsub/CHANGES.md
This commit will be tagged pubsub/v1.6.1
=> chore: release pubsub/v1.6.1

spanner/spannertest/db.go, spanner/spannertest/db_test.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
Column options appear in a few different places:
CREATE TABLE
ALTER TABLE ... ADD COLUMN
ALTER TABLE ... ALTER COLUMN
In the first two places, the entire column is being defined, and the
options may appear without a leading "SET". The third place may
explicitly set options using "SET". In all cases, the options
specification is itself the same, so extract that into its own type,
ColumnOptions, and add distinguished ColumnAlteration types so the
`ALTER TABLE ... ALTER COLUMN` form may be correctly parsed and
formatted.
This change is backward incompatible, but should only affect those using
(defining or parsing) column options.
Fixes #2621.
=> spanner/spansql: restructure types and parsing for column options

profiler/profiler.go
We've considered Profiler's go agent to be GA for a while now on Profiler's documentation ([see here](https://cloud.google.com/profiler/docs/about-profiler)). 
This change removes the comment indicating this agent is experimental to match up with docs at cloud.google.com
=> chore(profiler): remove comment indicating profiler library is experimental

storage/integration_test.go
The underlying bug for this has been fixed.
=> test(storage): unskip SignedURL_WithEncryptionKeys

storage/integration_test.go
This test was skipped b/c of a rate limit issue, but we
were able to waive this rate limit for the testing project
via an internal change.
Fixes #1632
=> test(storage): unskip UpdateRetentionPolicy test

profiler/kokoro/continuous_backoff.cfg
I used "build" where I should have used "build_file".
=> chore(profiler): fix Kokoro configurations

speech/apiv1/Recognize_smoke_test.go, speech/apiv1p1beta1/Recognize_smoke_test.go
A bucket that we rely on was accidentally deleted. Until these
assets find a new home, we should skip these tests. This affected
client libraries in other languages as well.
Fixes: #2697
Fixes: #2698
Updates: #2702
=> test(speech): skip tests that rely on deleted bucket

internal/gapicgen/generator/genproto.go
Previously these changes were discarded after generation. Let's
instead not generate them.
Updates: #2711
=> chore(internal/gapicgen): stop frozen APIs from even generating

internal/gapicgen/cmd/genbot/Dockerfile
Bumps Go micro-generator version to v0.14.4. The list of changes between releases include:
* fix godoc link in generated pkg docs (https://github.com/googleapis/gapic-generator-go/pull/412)
* use getters in pagination helper code (https://github.com/googleapis/gapic-generator-go/pull/407)
* add proto3_optional support (https://github.com/googleapis/gapic-generator-go/pull/379)
* fix header request param parsing (https://github.com/googleapis/gapic-generator-go/pull/366)
There are no significant changes to runtime code.
=> chore(internal/gapicgen): update gapic gen version

internal/gapicgen/cmd/genbot/Dockerfile
Go tooling was failing due to inconsistencies between protoc-gen-go
versions. This was caused by #2715.
Tested locally and the Dockerfile now builds.
=> chore(internal/gapicgen): fix genbot

spanner/client_test.go, spanner/internal/testutil/inmem_spanner_server.go, spanner/transaction.go
`Session not found` errors were not retried for read operations on a single-use read-only transaction.
Fixes #2718
=> fix(spanner): retry session not found for read

spanner/session.go
The `cancel()` method should be called once all code that is executing in the given context have finished. In this case, that also means after the stats recording that uses the same context has finished.
Fixes #2660
=> fix(spanner): call ctx.cancel after stats have been recorded

.github/release-please.yml
An alternate CHANGELOG path is now supported by the release tool.
=> build: configure alternate CHANGELOG path

storage/doc.go, storage/storage.go
This is already indicated in the docs for the client type,
but we want to make sure this is emphasized by including it
in the package docs and docs for NewClient as well. This
becomes more important now that the transport is cloned
for each new client.
Updates #2688
=> doc(storage): storage.Client should be reused

storage/integration_test.go, storage/storage.go
This metadata field should be mutable via
ObjectHandle.Update.
One part of the integration test is commented out as part of a bug that @frankyn and I are investigating.
=> feat(storage): allow CustomTime to be updated

internal/gapicgen/cmd/genbot/Dockerfile
This updates the gapic-generator-go to the latest version: v0.15.1
Notable changes include:
- generation of default deadlines from retry/timeout config for non-streaming methods
If specified in the given retry/timeout config, non-streaming methods will have a deadline imposed on the context provided at call-time when there isn't already one present. There is a temporary opt-out for all clients through a common environment variable.
=> chore(internal/gapicgen): update microgen to v0.15.1

pubsub/integration_test.go
Two tests were previously skipped due to repeated test failures.
`TestIntegration_OrderedKeys_JSON` failed due to failure to use regional endpoints.
`TestIntegration_OrderedKeys_ResumePublish` had an issue with setting the read-only field `ID`. In addition, the test message size used to induce failures was too big, causing the machines to run out of memory.
This closes #2811, closes #1833, closes #1834, closes #1835, closes #1836, closes #1837, closes #1838, closes #1839, closes #1841, closes #1842, closes #1843, closes #1844
=> fix(pubsub): fix ordering key integration tests

pubsub/pubsub.go, pubsub/trace.go
It seem that the telemetry options added here predate general
telemetry handling. There is no need to explicitly enable such
options here as it is taken care of grpc.DialPool:
https://pkg.go.dev/google.golang.org/api/transport/grpc?#DialPool.
The stats handler is only added if option.WithTelemetryDisabled is
not passed in.
Fixes: #2751
=> fix(pubsub): honor option.WithTelemetryDisabled

spanner/spansql/types.go
The connection between the interface types and their concrete
implementations is otherwise not visible in the external facing
documentation.
=> spanner/spansql: update docs on TableAlteration, ColumnAlteration

internal/gapicgen/generator/config.go, internal/gapicgen/generator/config_test.go
A recent [change](https://github.com/googleapis/googleapis/commit/48ce8878cd4c54cf247de826ac53c1414b0345bd) has removed some apis from the surface of
apiv1/v2. As this is a breaking change, we need to start generating
sources under a new import path. A future commit will deprecated
the previous package.
=> feat(cloudbuild): Start generating apiv1/v3

spanner/integration_test.go
The problem is that sometimes we got `big.nat(nil)` but want `big.nat{}`. This happens occasionally and I couldn't reproduce it on my local env. 
One of the errors: 
```bash
integration_test.go:1524: 83: col:Numeric val:big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat{}}}, got big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat(nil)}}, want big.Rat{a:big.Int{neg:false, abs:big.nat{0x75bcd15}}, b:big.Int{neg:false, abs:big.nat{}}}
```
So I suspect that we should use `big.Rat.Cmp` for checking equality instead of using `cmp`. 
Fixes #2828
=> fix(spanner): fix flaky numeric tests

internal/gapicgen/generator/config.go, internal/gapicgen/generator/config_test.go
The breaking changes have been rolled back, there is no need to
generate under a new package.
This reverts commit 358a5368da64cf4868551652e852ceb453504f64.
=> revert(cloudbuild): "feat(cloudbuild): Start generating apiv1/v3"

spanner/spansql/parser.go, spanner/spansql/parser_test.go
These should be in separate Comment entries, not combined:
Some INT64,  -- comment #1
-- comment #2
=> fix(spanner/spansql): fix parsing of adjacent inline and leading comments

internal/kokoro/publish_docs.sh
docuploader used to be "calendar" versioned. Now, it's normally versioned. This will work until we get to major version 2019. :wink:
=> fix(internal/kokoro): install the right version of docuploader

internal/kokoro/publish_docs.sh
Before, this would be uploaded as `docfx--go-...`.
=> fix(internal/kokoro): remove extra dash in doc tarball

internal/godocfx/parse.go
After this change, function headers show up as `func Foo` rather than
`func Foo(s string) string`, matching the behavior of pkg.go.dev.
=> fix(godocfx): shorten function names

spanner/spannertest/db_query.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
These type rearrangements make room for JOIN support.
There's no change to what may be parsed, or to what is supported by spannertest, though there is also a minor fix to include the table alias when rendering a SelectFrom via its `SQL()` method.
=> chore(spanner/spansql): restructure FROM, TABLESAMPLE

spanner/spannertest/db.go, spanner/spannertest/db_eval.go, spanner/spannertest/db_query.go, spanner/spannertest/db_test.go, spanner/spannertest/inmem.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
This was a long-planned cleanup, which adds some rigour to the type
definitions, and avoids a bunch of unnecessary casting in various
places.
=> chore(spanner/spansql): use ID type for identifiers throughout

internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
Examples are located in _test.go files, which go/packages parses into a
separate foo_test package. So, this requires an extra step of collecting
all files from the package, including test packages, then parsing them.
That way, the go/doc package can associate types/functions/packages with
the examples for them (rather than an unassociated list).
=> feat(docfx): add support for examples

internal/godocfx/go.sum, internal/godocfx/parse.go
The sort keeps the TOC in a stable order.
=> fix(godocfx): filter out other modules, sort pkgs

spanner/spansql/fuzz.go
This target will be called from a runner managed by the oss-fuzz
project. This target is an experimental test integration with the
oss-fuzz project.
=> test(spanner/spansql): add fuzz target for ParseQuery

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
This parses almost all of the JOIN clause syntax, with the exception of
HASH and hints.
It doesn't support the full range of common joins due to a lack of
support for path expressions, but that will be addressed separately.
Updates #2850.
=> feat(spanner/spansql): parse joins

pubsub/pstest/fake.go, pubsub/pstest/fake_test.go
Add reactor options to pstest server.
This allows users to define customized reactor to a sub command handler. An example is to inject error in topic deletion.
Note: only the DeleteTopic is shown as an example here, after we settle down the naming and formatting, similar reactor will be added to all the functions.
=> feat(pubsub/pstest): Add reactor options to pstest server

pubsub/pstest/fake.go, pubsub/pstest/fake_test.go
A status code is added into errorInjectionReactor, this is necessary
as the retry setting for some calls depends on the error code. Also
the errorInjectionReactor is not exported. Note that the previous
version is same as having an Unknown code as the server will always
wrap the error to a proper status error.
BREAKING CHANGE: this will invalidate the previous exported
`ErrorInjectionReactor` struct and `WithErrorInjection` function.
=> feat(pubsub/pstest)!: Add status code to error injection.

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
These are not properly documented, so this only attempts to support a
limited but widely used subset, which will be sufficient for more fully
supporting aliases and joins.
Updates #2462.
Updates #2463.
Updates #2850.
=> feat(spanner/spansql): parse path expressions

spanner/spannertest/README.md, spanner/spannertest/db.go, spanner/spannertest/db_eval.go, spanner/spannertest/db_query.go, spanner/spannertest/db_test.go
This adds support for aliases in SELECT statements, and in particular
table aliases that can then be referenced from other places in the query
evaluation.
Fixes #2463.
=> feat(spanner/spannertest): evaluate path expressions

internal/godocfx/godocfx_test.go, internal/godocfx/main.go, internal/godocfx/parse.go, internal/godocfx/testdata/golden/README.md, internal/godocfx/testdata/golden/toc.yml
I also changed the return type of parse to be a result type to simplify
passing the... results around.
Related to https://github.com/googleapis/doc-pipeline/pull/39.
=> feat(godocfx): include README in output

bigquery/CHANGES.md, internal/version/version.go
This PR will be tagged as bigquery/v1.11.1.
=> chore: release bigquery/v1.11.1

spanner/spannertest/README.md, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/types.go
This includes both the special case "HASH JOIN" syntax and the "JOIN@{...}" syntax.
Initial work towards #2462.
=> feat(spanner/spansql): parse join hints

bigquery/integration_test.go, bigquery/iterator.go
Iterating query results from the fastpath with an iterator.Pager
forces a cache miss if the pager size is misaligned with the cached
page size.
Logic to reduce the size of the getQueryResults payload by dictating
the projected fields was yielding an empty pageToken and no rows, which
is equivalent to an empty page response.
This PR corrects the projection logic, and adds an integration test to
exercise the use of misaligned paging.
Fixes: #2946
=> fix(bigquery): address fastpath iteration with iterator.Pager

bigquery/CHANGES.md, internal/version/version.go
This PR will be tagged bigquery/v1.11.2
=> chore: release bigquery/v1.11.2

spanner/spannertest/README.md, spanner/spannertest/db_query.go, spanner/spannertest/db_test.go
This lays the groundwork for supporting joins, and this initial subset
is a very common form.
Fixes #2462.
=> feat(spanner/spannertest): support LEFT OUTER JOIN with ON clause

pubsub/pubsub.go, pubsub/streaming_pull_test.go
Fix an issue where calling `client.Close()` will return a "the client connection
is closing" error on subscriber closing. This previously only happened in
non-live service environments (e.g. using the emulator or fake).
Also fix a typo where publisher and subscriber client close errors were swapped.
Fixes #2950
=> fix(pubsub): suppress connection is closing error

bigquery/table.go
In https://github.com/GoogleCloudPlatform/golang-samples/issues/1749
we observed sample tests failing due to ratelimit pushback on the
delete call.
This PR wraps the delete call in a retry, which should help
reduce the probability of this occuring.
=> fix(bigquery): add retries for table deletion

internal/godocfx/go.mod, internal/godocfx/godocfx_test.go, internal/godocfx/parse.go
The TOC is a bit unruly with every package in a single list. So, I added a couple levels of nesting: one for the module and one for the first part after the module. In other words, I split package names into `mod/mid/suffix` and nest shared `mod` and `mid` values. If there would only be one element in the nested list, it isn't nested. This is like a trie with only two levels.
The result looks like this:
```
- uid: cloud.google.com/go/bigquery
name: cloud.google.com/go/bigquery
items:
- name: README
href: README.md
- name: connection
items:
- uid: cloud.google.com/go/bigquery/connection/apiv1
name: apiv1
- uid: cloud.google.com/go/bigquery/connection/apiv1beta1
name: apiv1beta1
- uid: cloud.google.com/go/bigquery/datatransfer/apiv1
name: datatransfer/apiv1
```
=> feat(godocfx): add two levels of nesting to TOC

spanner/spansql/sql.go, spanner/spansql/types.go
Set up a parallel set of SQL-encoding methods called addSQL that build
the SQL result into a strings.Builder.
Fixes #2956.
=> perf(spanner/spansql): make fewer allocations during SQL

internal/godocfx/godocfx_test.go, internal/godocfx/parse.go
The extra level of nesting was too much.
cc @tzero
=> chore(internal/godocfx): remove TOC nesting

spanner/spannertest/inmem.go
spannertest simulates DDL application delays but skips the delay if
there is a waiter. Improve that mechanism so a waiter arriving during
the delay will immediately cancel the delay.
This speeds up the local execution time of spannertest's own tests from
~5s to ~3s.
=> perf(spanner/spannertest): speed up no-wait DDL changes

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
We cannot tokenise numbers with leading signs, because otherwise
`ID+100` is parsed as the identifier `ID` followed by the literal `+100`
instead of an arithmetic operation. This necessitates some rearrangement
of the parsing of int64 literals to accommodate that while also
preserving the ability to parse -INT_MAX.
=> fix(spanner/spansql): fix parsing of unary minus

internal/godocfx/go.sum, internal/godocfx/godocfx_test.go, internal/godocfx/parse.go
This is a minimal change refactoring the package loading into a separate
function. There will be more change in future CLs, but I only changed
what was necessary to create the function.
I'm open to other ways of breaking this up. :smiley: Might make more sense
to do them in a future PR (for example, I don't think we need to re-parse files).
cc @findleyr
=> chore(godocfx): refactor package loading

CONTRIBUTING.md, errorreporting/errors.go, errorreporting/example_test.go, internal/.repo-metadata-full.json, internal/gapicgen/generator/gapics.go
Debrand "Stackdriver" in favor of "Cloud" in Error Reporting. As a follow up to #3007.
It looks like I need to update upstream as well since there are mentions of Stackdriver in `errorreporting/apiv1beta1`
=> refactor(errorreporting): debrand Stackdriver from Error Reporting

storage/integration_test.go
TestIntegration_ReadCRC and TestIntegration_NoUnicodeNormalization
depended on data in a bucket which has seemingly been deleted.
This rewrites them so that they create their own data instead.
Fixes #3016
Fixes #3014
=> test(storage): fix failing integration tests

spanner/integration_test.go
The test did not check whether the query returned an Aborted error. If the transaction was aborted by Spanner, the Aborted error should be propagated to the transaction runner, which will automatically retry the transaction.
Fixes #3029
=> test(spanner): check for Aborted error

spanner/spannertest/README.md, spanner/spannertest/db_query.go, spanner/spannertest/integration_test.go
This was broken due to the ORDER BY implementation that was a bit of a
hack. Replace that hack with a more explicit evaluation of the ORDER BY
sort keys, which also removed a duplicate chunk of row sorting code.
This also required a restructuring of how locking works during an
evaluation, which cleaned up some other code.
Also include a minor revision to README.md.
=> fix(spanner/spannertest): fix ORDER BY combined with SELECT aliases

spanner/spannertest/README.md, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
This results in a minor backward-incompatible change to TableConstraint
to support both Check and ForeignKey appearing as constraints.
=> feat(spanner/spansql): parse CHECK constraints

spanner/spannertest/db_query.go, spanner/spannertest/integration_test.go
=> feat(spanner/spannertest): make SELECT list aliases visible to ORDER BY

internal/gapicgen/cmd/genbot/Dockerfile
Updates `gapic-generator-go` to `v0.15.3`. Notable changes include:
* use DefaultEndpoint and DefaultMTLSEndpoint for default options (https://github.com/googleapis/gapic-generator-go/pull/465)
=> chore(internal/gapicgen): update gapic generator v0.15.3

pubsub/integration_test.go
From #3065, temporarily skipping tests related to geofencing integration test failures due to a recent move of our regression test project.
=> chore(pubsub): skip pubsub geofencing tests

RELEASING.md, internal/godocfx/go.mod, internal/godocfx/go.sum, internal/godocfx/godocfx_test.go, internal/godocfx/index.go, internal/godocfx/index_test.go, internal/godocfx/main.go, internal/godocfx/parse.go, internal/godocfx/timesaver.go, internal/kokoro/publish_docs.sh
This uses index.golang.org to list all modules since a given time. For
example, see
https://index.golang.org/index?since=2019-04-10T19:08:52.997264Z. Each
page is listed in chronological order and is limited to 2000 entries (as
of today).
This stores the last successful time in Datastore. If there is no time in
Datastore, it defaults to 10 days ago.
There is a bit of indirection with interfaces to enable testing.
In the future, we should add the ability to regenerate the YAML for the
latest version of all modules.
cc @julieqiu @katiehockman
=> feat(internal): auto-run godocfx on new mods

logging/logging.go, logging/logging_unexported_test.go
Fixes: #1590 
**Changes according to spec:**
1.  `trace`, `spanID` and `traceSampled` fields in X-Cloud-Trace-Context can be optional (see context/trace_context.proto)
2. TraceSample should default to false (verified with nwang@)
3. Trace/span IDs should still be included in log contexts even when traceSampled is false, because "A non-sampled trace value is still useful as a request correlation identifier." ([LogEntry spec](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry))
**Details:**
[Intended Use case](https://cloud.google.com/trace/docs/setup#force-trace)
The following header specifications by users are now recognized:
=> fix(logging): allow X-Cloud-Trace-Context fields to be optional

internal/gapicgen/cmd/genbot/Dockerfile
github.com/googleapis/gapic-generator-go@v0.15.3 from github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic@v0.15.3 requires github.com/golang/protobuf@v1.4.3
=> chore(internal/gapicgen): update protoc-gen-go

spanner/client.go, spanner/transaction.go
This is a generic api change to support passing options into transactions. This will be used to support a couple of new features.
=> feat(spanner): support rw-transaction with options

spanner/client_test.go, spanner/read.go
Spans should not be ended with iterator.Done as an error. This is not an actual error, but an indication that the iterator reached its end. Setting this as an error on a span pollutes the traces and makes it harder to find actual errors that might occur.
Fixes #3110
=> fix(spanner): do not end span with iterator.Done

RELEASING.md
The cited `go generate` is responsible for updating the repo reference
in internal/version.go, so listing it both explicitly as a manual edit
and a generate command seems redundant.
=> docs: remove redundant step in submodule RELEASING.md guidance

pubsublite/internal/wire/periodic_task.go, pubsublite/internal/wire/periodic_task_test.go
Introduces periodicTask to manage a recurring background task that can be paused and resumed.
=> feat(pubsublite): Periodic background task

pubsublite/internal/test/mock.go, pubsublite/internal/test/util.go, pubsublite/internal/wire/flow_control_test.go, pubsublite/internal/wire/requests_test.go
Adds the remaining Pub/Sub Lite streaming RPCs to the mock server. Adds utilities for crafting requests and responses.
=> feat(pubsublite): Test utils for streams

internal/godocfx/parse.go
Test packages don't have module set, so they aren't filtered out in the
existing check. The order of packages isn't defined as far as I can
tell. So, we may not know to skip a package when we first see it.
=> fix(internal/godocfx): filter out test packages from other modules

spanner/spansql/parser.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
=> feat(spanner/spansql): define structures and parse UPDATE DML statements

spanner/spannertest/README.md, spanner/spannertest/db.go, spanner/spannertest/integration_test.go
=> feat(spanner/spannertest): support UPDATE DML

internal/gapicgen/generator/genproto.go, internal/gapicgen/generator/genproto_test.go
These packages don't have a corresponding client library (in
cloud.google.com/go or another module). They aren't ready for production
use. So, we're going to stop generating them for now and will revisit
in the future when ready.
A go-genproto PR will remove the existing Ads packages.
If needed, these packages can be generated locally or as part of a build
process. However, we're not ready to generate and publish them
automatically.
@anashoommen @aohren
=> chore(internal): stop generating Ads packages in genproto

spanner/spannertest/README.md, spanner/spannertest/db_query.go, spanner/spannertest/integration_test.go
This doesn't fit into the same structure as the other JOINs, but is
approximately implemented as a LEFT JOIN with a catchup phase of
emitting the unmatched RHS rows.
=> feat(spanner/spannertest): implement FULL JOIN

pubsub/message.go, pubsub/topic.go
Rolls back the public functions added in https://github.com/googleapis/google-cloud-go/pull/3200. We have decided not to expose these to users.
=> fix(pubsub): Remove NewMessage and NewPublishResult

logging/logging_test.go
fixes: #3104 
getEntries was optimized with the timestamp filter, from 10m per query to ~10secs. However, this PR still does add <30 seconds to the CI execution time, as we've renabled 3 tests.
=> ci(logging): renabled un-flaked log tests

pubsublite/internal/wire/acks.go, pubsublite/internal/wire/acks_test.go, pubsublite/internal/wire/committer.go, pubsublite/internal/wire/committer_test.go
When stopped, the `committer` now sends the final commit offset only. Acks that arrive after Stop() are discarded to minimize complexity. Acks are best-effort anyway.
=> refactor(pubsublite): committer discards outstanding acks when stopped

pubsublite/internal/wire/periodic_task.go, pubsublite/internal/wire/streams.go, pubsublite/internal/wire/subscriber.go, pubsublite/internal/wire/subscriber_test.go
Motivation: we want to match the Java Lite implementation, that delivers messages for a partition sequentially and block progress if the user's message receiver func blocks.
Messages were previously delivered to the user receiver func from the goroutine that processes the underlying Subscribe gRPC stream. If the Subscribe stream breaks, a new goroutine is started to handle a new stream instance, so the user's receiver func may be invoked while concurrently processing a previous invocation.
`messageDeliveryQueue` uses a channel to ensure that messages are delivered sequentially for a partition.
=> fix(pubsublite): deliver messages sequentially

spanner/read_test.go
Queries will always return at least one partial result set containing the metadata of the query, even if the query does not return any rows. That was not taken into account in one of the test cases.
Fixes #3295
=> test(spanner): queries always return at least one partial result set

pubsublite/internal/wire/partition_count.go, pubsublite/internal/wire/partition_count_test.go, pubsublite/internal/wire/periodic_task.go, pubsublite/internal/wire/publisher.go, pubsublite/internal/wire/publisher_test.go, pubsublite/internal/wire/rpc.go, pubsublite/internal/wire/settings.go
`partitionCountWatcher` polls for updates to the number of topic partitions.
`routingPublisher` routes messages to multiple `singlePartitionPublishers` and handles the topic partition count increasing. Decreases will terminate the routingPublisher.
The initial set of partition publishers must successfully start before the routingPublisher accepts published messages. However, when new partition publishers are added later, messages may be routed to them while they are starting up. The messages are queued in the `publishMessageBatcher` and sent to the server when the Publish stream connects.
The entire `routingPublisher` tree terminates if the `partitionCountWatcher` or any of the `singlePartitionPublishers` terminate.
=> feat(pubsublite): routing publisher implementation

internal/gapicgen/cmd/genbot/Dockerfile
This most notably will start passing a new internaloption in all
apis to enable them to authenticate with self-signed JWTs if
applicable.
=> chore(internal/gapicgen): upgrade gapic generator to v0.16.0

spanner/spannertest/README.md, spanner/spansql/keywords.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
=> feat(spanner/spansql): support for parsing generated columns

internal/gapicgen/cmd/genbot/github.go
This flag was not intended to be commited and was used for
testing.
=> fix(internal/gapicgen): don't create genproto pr as draft

pubsublite/internal/wire/subscriber_test.go
Fixes https://github.com/googleapis/google-cloud-go/issues/3329 and other similar instances.
The subscribeStream transitions to the active state before it terminates, however the state change notifications are sent asynchronously, so they can be received by observers out of order. In these test cases, we expect the subscribeStream to terminate due to fatal error, so it is only necessary to check FinalError().
=> test(pubsublite): fix flaky subscriber stream tests

internal/gapicgen/cmd/genbot/github.go, internal/gapicgen/go.mod, internal/gapicgen/go.sum
(see https://github.com/google/go-github/pull/1660/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6)
This was causing a [CI failure](https://app.circleci.com/pipelines/github/googleapis/gapic-generator/588/workflows/69c7072b-c9f9-4703-bcbc-00a09317793d/jobs/51225) in https://github.com/googleapis/gapic-generator/pull/3312
=> chore(internal/gapicgen): Bump version of go-github library to v33

spanner/spannertest/README.md, spanner/spansql/parser.go, spanner/spansql/sql.go, spanner/spansql/types.go
This adds support for NUMERIC as a column data type in CREATE TABLE and
similar constructions. Its support in spannertest remains a TODO.
Fixes #3395.
=> feat(spanner/spansql): support NUMERIC data type

.github/workflows/release-submodule.yaml
I believe this darn typo is why the step wasn't aborting, the string ')' evaluates to `true`.
=> build: typo on if line was issue

bigquery/integration_test.go, bigquery/job.go
This PR plumbs through reservation usage stats reported per-job.
Also added a small integration test for testing query statistics,
as we didn't have one previously.
=> feat(bigquery): add reservation usage stats to query statistics

pubsub/pullstream.go
A error was made in #3367 when using the default MaxExtensionPeriod of 0 seconds. This also made the default stream ack deadline seconds 0, which means messages will always expire and messages will never be successfully delivered. This PR reverts to the previous default of 60 seconds if MaxExtensionPeriod is disabled.
This issue fixes #3397, fixes #3398, fixes #3399
=> fix(pubsub): fix default stream ack deadline seconds

spanner/spannertest/funcs.go, spanner/spansql/keywords.go
=> feat(spanner/spannertest): implement ANY_VALUE aggregation function

spanner/spannertest/db_query.go, spanner/spannertest/integration_test.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
This does not implement array literals, but now arrays provided as query
parameters may be used as SELECT targets.
Fixes #3296.
=> feat(spanner/spannertest): implement SELECT ... FROM UNNEST(...)

.github/workflows/release-submodule.yaml, .github/workflows/release.yaml
Go uses the name `CHANGES.md` rather than `CHANGELOG.md`.
=> build: use the alternate CHANGELOG name

spanner/spannertest/db_eval.go, spanner/spannertest/integration_test.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
These are relatively easy, and often appear with UNNEST.
=> feat(spanner/spannertest): support array literals

datastore/load_test.go
=> chore(datastore): skip failing test TestLoadCivilTimeInNonUTCZone

datastore/load_test.go
This test causes a race condition and there's no simple way
to get it to work. I'll file another issue to figure out a way
to test this behavior.
Fixes #3402
=> test(datastore): remove flaky timezone test

pubsublite/admin.go, pubsublite/admin_test.go
Minor change to return an error if `UpdateTopic` and `UpdateSubscription` have no fields to update, for consistency with CPS implementation.
=> fix(pubsublite): return an error if no topic or subscription fields were updated

pubsublite/internal/wire/subscriber.go, pubsublite/internal/wire/subscriber_test.go
If the `messageDeliveryQueue` channel buffer is full, adding more messages to the channel will block while holding the `subscriberStream` mutex. The only potential problem is that subscriber client shut down is delayed until the mutex can be acquired.
This can only occur if the user sets MaxOutstandingMessages to be greater than 10000 (default value is 1000). So we'll just remove the clipping of the message buffer size, so that it's guaranteed to hold all MaxOutstandingMessages and not block.
The downside is that if users do set a very large MaxOutstandingMessages value (which is unlikely), channel buffer capacity will be preallocated. Otherwise we can introduce a second mutex, at the cost of additional code complexity.
Also minor: removed a pointless intermediate `ReceivedMessage` slice …
=> refactor(pubsublite): remove messageDeliveryQueue buffer limit

internal/gapicgen/cmd/genbot/Dockerfile
This most notably will allow RPCs that have all of the normal pagination fields, but no repeated field, to be treated as normal RPCs instead of creating an error.
=> chore(internal/gapicgen): upgrade gapic generator to v0.17.0

internal/kokoro/continuous.sh
This now correctly tracks significant changes from the latest PR merged into master.
=> ci(all): turn on testing significant changes since last merge

README.md
Remove traces of reference to mirror
=> docs: remove reference to Github being a mirror

internal/kokoro/continuous.sh
Now nightly jobs can accommodate the following Kokoro directory/naming structures: 
- /nightly/JOB_NAME
- /nightly/[OPTIONAL_MODULE_NAME]
- /nightly/[OPTIONAL_MODULE_NAME]/[OPTIONAL_JOB_NAMES...]
Sorry, for the multiple small fix PRs!
=> ci(all): extend nightly submodule run to allow sub jobs

internal/kokoro/continuous.sh
I caught my error with this test: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fnightly%2Flogging%2Fgo115?search_pattern=google-cloud-go%2Fnightly&include_inactive_projects=false
I updated the script to reference the correct kokoro job name. 
Thanks for all the PR reviews on this! I appreciate the patience on this :)
=> ci(all): fix incorrect reference to job name in nightly

spanner/spannertest/README.md, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
This parses a reasonable subset, and renders in a reasonable format.
Future work will be required to support this in spannertest, as well as
correctly supporting the full range of valid layouts.
Fixes #3548.
=> feat(spanner/spansql): support DATE and TIMESTAMP literals

pubsublite/admin.go, pubsublite/admin_test.go, pubsublite/integration_test.go
For consistency with the Java and Python libraries.
=> fix(pubsublite)!: rename TopicPartitions to TopicPartitionCount

spanner/apiv1/spanner_client_options.go, spanner/client.go
Sources the default client options from the generated client instead of the hand-written client. This makes sure that new default options that are introduced in the future will automatically be picked up by the Spanner client.
Fixes #3532
=> chore(spanner): source default opts from gapic client

logging/logadmin/logadmin.go, logging/logadmin/logadmin_test.go
Fix #3588 
Changes: 
- Turned integration test back on for `logadmin`. According to previous comments, this may be flakey so I will closely monitor and debug. 
- Added fields LocalIP, CacheLookup, and CacheFillBytes back to httprequest conversion from proto to logging.httprequest
=> feat(logging): add localIP and Cache fields to HTTPRequest conversion from proto

spanner/spannertest/db.go
Separate out validation from the alteration so that validation failures
won't leave a corrupted table. This will also permit other schema
changes to be more easily added in the future.
Permit adding and removing NOT NULL for column types other than
string/bytes, and enforce that it isn't permitted on primary key columns
or array-typed columns.
=> feat(spanner/spannertest): restructure column alteration implementation

bigquery/integration_test.go
Looks like streaming insert row size is changing, disable this test
while the limits converge to new value.
Related: https://github.com/googleapis/google-cloud-go/issues/3612
=> test(bigquery): skip a limit test while backend limits in flux

spanner/spansql/keywords.go
This doesn't implement them, but only declares them for accurate
parsing.
Fixes #3618.
=> feat(spanner/spansql): add complete set of string functions

.github/CODEOWNERS
This will allow anyone on the storage-dpe team to approve PRs for
storage.
=> chore(.github): add storage-dpe group as owner

.github/workflows/release-submodule.yaml, .github/workflows/release.yaml
This will make cutting a v1.0.0 a more explicit process rather
than default to bump to v1.0.0 if a breaking change occurs.
=> chore: have release please bump minor pre major

internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml, third_party/pkgsite/print_type.go
The changes to `pkgsite` are mostly copied and pasted. I modified it a little to make the API easier to use. I also added the explanatory comment at the top of `PrintType` because it took a while for me to wrap my head around it.
=> feat(internal/docfx): full cross reference linking

internal/godocfx/parse.go, third_party/pkgsite/print_type.go
Here is a resulting diff from the `firestore` package:
```
-    content: var MergeAll <a href="#setoption">SetOption</a> = <a href="#merge">merge</a>{/*
-      contains filtered or unexported fields */}
+    content: var MergeAll <a href="#setoption">SetOption</a> = merge{/* contains filtered
+      or unexported fields */}
```
Note that `merge` should not be linked. This PR fixes that.
=> fix(internal/godocfx): use exact list of top-level decls

pubsublite/internal/wire/subscriber.go, pubsublite/internal/wire/subscriber_test.go, pubsublite/pscompat/integration_test.go, pubsublite/pscompat/message.go, pubsublite/pscompat/message_test.go, pubsublite/pscompat/settings.go, pubsublite/pscompat/subscriber.go, pubsublite/pscompat/subscriber_test.go, pubsublite/publish/example_test.go, pubsublite/publish/metadata.go
This mirrors the Java implementation: https://github.com/googleapis/java-pubsublite/pull/482. If the user's custom message transformer sets the `pubsub.Message.ID`, the `SubscriberClient` will terminate with error. The internal wire subscriber needs to pass the partition number to the CPS subscriber shim via `ReceivedMessage`.
Updated tests and documentation. Changed the comments for `publish.ParseMetadata` to inline documentation examples.
=> fix(pubsublite): change pubsub.Message.ID to an encoded publish.Metadata

pubsublite/internal/wire/assigner_test.go
Checks only the final error to ensure the test is deterministic.
Fixes https://github.com/googleapis/google-cloud-go/issues/3667.
=> test(pubsublite): fix flaky TestAssignerHandlePartitionFailure

storage/integration_test.go
Rarely a wrapped context.Cancel error can be returned from the
writer, so the current check will fail. We have to resort to string
matching for now, but for Go >= 1.13 errors.Is should work.
Fixes #3688
=> test(storage): unflake TestIntegration_CancelWrite

pubsub/flow_controller.go, pubsub/flow_controller_test.go, pubsub/subscription.go, pubsub/trace.go
This PR adds two more views that reports the number of outstanding messages/bytes that are held by the flow controller. The aim is to allow deeper insight into the number of inflight messages that have been acquired by the client but not yet processed. In addition, this also starts tracking outstanding bytes (`bytesRemaining`) in `flow_controller.go`
This feature is experimental and subject to change.
/cc @lahuang4
=> feat(pubsub): add opencensus metrics for outstanding messages/bytes

internal/gapicgen/cmd/genbot/Dockerfile, internal/gapicgen/generator/config.go, internal/gapicgen/generator/gapics.go
* add metadata flag to configs
* update gapic-generator-go to v0.18.2
* gen code changes include:
* generation of gapic_metadata.json
* removal of stuttering import aliases for `*pb` packages like `structpb`
=> chore(internal/gapicgen): enable metadata gen

internal/gapicgen/cmd/genbot/Dockerfile
Includes a small fix for gapic_metadata generation.
=> chore(internal/gapicgen): update generator to v0.18.3

spanner/spansql/parser.go, spanner/spansql/parser_test.go
The parsing of comparison operators was erroneously capturing any NOT
token assuming it would be followed by a LIKE or BETWEEN. Instead,
change that code to explicitly look ahead for the limited combinations
allowed, and do the same for parsing IN and NOT IN.
Fixes #3715.
=> fix(spanner/spansql): fix parsing of NOT IN operator

internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
This works by pre-processing the package and generating all of the correct anchor links. Then, when converting an ID to a link, we check if the ID is listed in the map of anchors.
It's possible there will be some duplication between IDs. But, that is already an issue because there is no way to know which one is correct to link to. An alternative would be to set the anchor for any duplicated links to `""` so they don't link at all. In practice, I don't think this is an issue. So, I left it as-is and we can revisit later if needed.
Fixes #3737.
=> fix(internal/godocfx): use correct anchor links

pubsublite/internal/test/verifier.go
Helps debugging failed unit tests.
=> test(pubsublite): print proto type in verifier error messages

internal/gapicgen/generator/config.go
Use proper API Service Config file for area120/tables GAPIC.
=> fix(tables): use area120tables_v1alpha1.yaml as api-service-config

internal/kokoro/check_incompat_changes.sh
* reenables `apidiff`
* update `go version` to target to be 1.16.x
* makes it compare against the new GitHub SoT
* tweaks it to only need a single execution of the incompat check by dumping the output to a file and checking if the file has content
=> chore(internal/kokoro): enable apidiff

bigquery/schema.go, bigquery/schema_test.go
BigQuery documents aliases DECIMAL for NUMERIC, and BIGDECIMAL for BIGNUMERIC.  Add them to the alias list.
=> feat(bigquery): support type alias names for numeric/bignumeric schemas

internal/godocfx/godocfx_test.go, internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
The magic of this PR (that took me way too long to figure out) comes from adding `| packages.NeedDeps` to the `packages.Load` `Config`. That lets us get the `Fset` and `Syntax` of all packages the current package imports. We can then use that information to pull out the anchors for every element we link to.
This also fixes an issue where we were handling some packages that didn't have the Module field set -- we can ignore them. It appears to be a new package gets returned with the ID of the glob you asked for. For example, `cloud.google.com/go/...`. We don't seem to need that.
Fixes #3739.
=> feat(internal/godocfx): keep some cross links on same domain

internal/gapicgen/generator/gapics.go
There is an entry for a manual `trace` client in the `.repo-metadatafull.json`, but there is no such package. There are two generated clients, however, `apiv1` & `apiv2` which are included in the manifest when generated.
=> chore(internal/gapicgen): remove manual trace from manifest

pubsublite/config.go
Fixes https://github.com/googleapis/google-cloud-go/issues/3766.
=> docs(pubsublite): specify ranges for TopicConfigToUpdate values

internal/kokoro/publish_docs.sh
Eventually, we'll want to be able to easily regenerate every version of every module. For now, this adds the ability to regenerate a single module.
=> feat(internal): add ability to regenerate one module's docs

storage/integration_test.go
These tests rely on public data in the Landsat bucket
(https://cloud.google.com/storage/docs/public-datasets/landsat).
The data under PRE/ has been removed, so I shifted these to instead
use another prefix which should be stable.
Already done for dotnet here: googleapis/google-cloud-dotnet#6025
Fixes #3800
Fixes #3801
=> test(storage): fix unauthenticated access tests

pubsublite/internal/wire/settings.go, pubsublite/pscompat/settings.go
The default is currently 1 minute, which may be too short and causes publishers and subscribers to permanently shut down.
=> fix(pubsublite): increase default timeouts for publish and subscribe stream connections

internal/godocfx/goldmark-codeblock/codeblock.go, internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
=> feat(internal/godocfx): add prettyprint class to code blocks

internal/apidiff/apidiff.go
Enables `apidiff` for all release levels as all breaking changes should be approved.
=> chore(internal/apidiff): enable apidiff for all release levels

internal/apidiff/apidiff.go, internal/apidiff/apidiff_test.go
Allow breaking changes when either of the conventional commit breaking change indicators are available: `!` or `BREAKING CHANGE:`.
An example of the former is: `fix!(dialogflow): remove rpc or fields that are unintended to release`
=> chore(internal/apidiff): check for bang breaking change indicator

internal/gapicgen/generator/config.go, internal/gapicgen/generator/config_test.go
This fixes some generation configs that I noticed were using the GAPIC yaml for the `apiServiceConfig` param. These are actually different yaml files and the generator silently accepted them (gonna fix this https://github.com/googleapis/gapic-generator-go/issues/573). The Go microgenerator doesn't use the GAPIC yamls at all.
=> chore(internal/gapicgen): use API Service Config not gapic config

examples_test.go
Updated a few URLs to point to current locations (as opposed to redirect URLs).
In the Service Account URLs case, it was pointing to a non-existant cloud console page.
=> docs: update a few URLs in example documentation

bigquery/external.go, bigquery/load.go, bigquery/load_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/3876
=> feat(bigquery): export HivePartitioningOptions in load job configurations

bigquery/integration_test.go
Now that we have a v1 PolicyTagManager client, we can test the policy tag integration
with column ACLs.
This also plumbed in a new PTM client as part of the integration testing
setup, much like we make a cloud storage client available.
=> test(bigquery): add integration test for Column ACLs

internal/godocfx/parse.go, internal/godocfx/pkgload/load.go
I'd like to be able to reuse the package loading function for example
generation. So, to make it importable, I refactored it into another package.
There are no changes to the code beyond exporting necessary identifiers
(and, you know, moving the code).
I copied the `hasPrefix` utility because it's useful. :smile: 
This is all internal, so there are no concerns about exporting identifiers and
keeping compatibility over time.
Updates #3916.
=> refactor(internal/godocfx): move pkg loading to separate package

internal/gensnippets/main.go
=> fix(internal/gensnippets): run goimports

internal/gapicgen/cmd/genbot/Dockerfile
protoc 3.11.X is no longer the default on stable.
=> chore(internal/gapicgen): use protoc 3.12.2

.gitignore
I accidentally merged this file, but only needed it locally and it breaks our CI if merged in master :[
=> chore(all): un-gitignore file not in repo

internal/kokoro/build_samples.sh
See: https://github.com/GoogleCloudPlatform/golang-samples/pull/2052
=> test: check mod version when no Go files in root

internal/kokoro/vet.sh
=> chore(internal): ignore staticcheck in internal/generated/snippets

spanner/batch.go, spanner/client_test.go, spanner/internal/testutil/inmem_spanner_server.go
BREAKING CHANGE: Removes `BatchReadOnlyTransaction.PartitionReadUsingIndexWithOptions` and `BatchReadOnlyTransaction.PartitionReadWithOptions`
Reverts googleapis/google-cloud-go#3905
=> Revert "feat(spanner): enable request options for batch read"

spanner/client.go, spanner/client_test.go, spanner/pdml.go, spanner/pdml_test.go, spanner/transaction.go
BREAKING CHANGE:
This removes the following exported functions and fields:
- `TransactionTag(tag string) ApplyOption`
- `TransactionOptions.TransactionTag`
- `QueryOption.RequestTag`
- `ReadOption.RequestTag`
Reverts googleapis/google-cloud-go#3233
=> Revert "feat(spanner): support request and transaction tags"

pubsub/integration_test.go
Due to new internal org level policies, we don't have a consistent set of initial message storage policy regions. This PR refactors tests to make them not dependent on any initial region set.
In addition, cleans up the update labels test by removing the check for the unrelated message storage policy field.
Fixes #3065
=> fix(pubsub): fix failing message storage policy tests

internal/gapicgen/cmd/genbot/local.go, internal/gapicgen/cmd/genbot/main.go, internal/gapicgen/generator/gapics.go, internal/gapicgen/generator/generator.go
Adds a `regen-only` flag to local mode that disables generation version updates, manifest updates, and vetting/compilation. This is useful for iterating on generator changes or just fiddling. 
This also makes `gensnippets` respect the `only-gapics` flag, disabling snippet regen when that flag is enabled.
Finally, it optionally supplies the `release-level` option to the generator depending on if it is empty or not in the `microgenConfig`, and uses the flag name `api-service-config` instead of `gapic-service-config`, because that is the more accurate name.
=> chore(internal/gapicgen): add regen-only flag

.github/workflows/release.yaml
`go` was an alias to the `GoYoshi` release strategy (https://github.com/googleapis/release-please/blob/c80f8a096178fcf355579a3e70a255aac82c725a/src/releasers/index.ts#L54-L55). `GoYoshi` is also available via the `go-yoshi` release type config.
We will be replacing `go` with a generic golang releaser that only updates the `CHANGES.md` and handles tagging.
=> build: switch release-please type to go-yoshi

internal/gapicgen/generator/gapics.go, internal/gapicgen/generator/generator.go, internal/gapicgen/generator/genproto.go
=> fix(internal): make sure formatting is run on snippets

bigquery/bigquery.go, bigquery/bigquery_test.go, bigquery/go.mod
Based on similar refactor in storage:
https://github.com/googleapis/google-cloud-go/pull/4019
Fixes: https://github.com/googleapis/google-cloud-go/issues/4021
=> feat(bigquery): augment retry predicate to support additional errors

spanner/spannertest/README.md, spanner/spansql/parser.go, spanner/spansql/parser_test.go
This handles the most important parts of the parser as it relates to
case insensitivity, namely permitting the lexical tokens for the grammar
(as opposed to elements like table/column names) to have arbitrary case.
This includes a complete audit of the parser to check all the lexical
token handling, and cleaned up a few places that were particularly
ancient.
The rendered output remains canonically uppercase.
Fixes #4032.
=> feat(spanner/spansql): case insensitive parsing of keywords and functions

spanner/spannertest/db_query.go, spanner/spannertest/integration_test.go
Support multiple aggregations in one query.
Split from #3937
=> feat(spanner/spannertest): support multiple aggregations

profiler/integration_test.go
This change switches to using go modules consistently and switches to pulling profiler agent from https://github.com/googleapis/google-cloud-go.git rather than https://code.googlesource.com/gocloud.
TESTED= When running e2e test with go1.12, there were failures before this change and no failure with this change.
=> profiler: fix integration test

pubsublite/internal/test/verifier.go, pubsublite/internal/wire/subscriber.go, pubsublite/internal/wire/subscriber_test.go
Ensure that we send flowControlBatcher.RequestForRestart immediately after a new Subscribe stream is connected, before any batched flow control tokens are sent.
This hasn't been detected by tests or observed, but theoretically can occur via onAckAsync().
=> fix(pubsublite): prevent subscriber flow control token races

internal/kokoro/environment.sh
Fixes broken GAE env test. 
One has to manually add `gcloud components install app-engine-go` now
=> test(logging): install app-engine-go component in env test

pubsublite/internal/wire/periodic_task_test.go
Two executions of the task can run before the first call to `Stop`. So we stop the task immediately after receiving the value. This doesn't guarantee no flakes in the future. If it occurs again, we can increase `pollInterval`.
Fixes: https://github.com/googleapis/google-cloud-go/issues/4064
=> test(pubsublite): fix flaky TestPeriodicTask

internal/apidiff/apidiff.go
Fixes a typo (using the wrong flag) on the incompatibility check retry attempt.
Adds a `-gapic` flag to enable running this differ against just one package.
=> chore(internal/apidiff): fix incompat check retry

bigtable/admin.go, bigtable/integration_test.go
=> fix(bigtable): Guard for nil EncryptionConfig in Clusters, GetCluster

internal/gapicgen/cmd/genbot/Dockerfile
Introduces a number of documentation/comment fixes as well a refactor of the generated code that moves the transport specific (i.e. gRPC) client implementation behind a generated interface used within a generic client. This results in a few breakages to manual code that reference internal attributes. The following diff represents the changes that should be made to fix the build:
```
diff --git a/secretmanager/apiv1/iam.go b/secretmanager/apiv1/iam.go
index e3d78a54c..948ffe3cd 100644
--- a/secretmanager/apiv1/iam.go
+++ b/secretmanager/apiv1/iam.go
@@ -22,5 +22,10 @@ import (
// indicated by the given resource path. Name should be of the format
// `projects/my-project/secrets/my-secret`.
func (c *Client) IAM(name string) *iam.Handle {
-	return iam.InternalNewHandleGRPCClient(c.client, …
```
=> chore(internal/gapicgen): update microgen to v0.20.0

spanner/session.go
The default value in the Godoc had not been updated to reflect a recent change that updated the actual default value to 50 minutes.
=> docs(spanner): fix godoc for default value of health check interval

spanner/session_test.go
The refactoring of the generated gapic client had broken a test case that used reflection to get an internal value. This fixes the test
by first getting the (new) internalClient, and then getting the value from the internal client.
Fixes #4156
=> test(spanner): fix test case using reflection

spanner/integration_test.go
In spanner integration tests, an instance will be created before the test. Currently, the instance is created with the first instance config. However, for staging environment the instance config is shared among GCP projects and can run out of resources. So this PR tries to solve this issue by allowing users to custom the instance config by adding an environment variable GCLOUD_TESTS_GOLANG_SPANNER_INSTANCE_CONFIG.
=> feat(spanner): add custom instance config to tests

bigtable/bttest/inmem.go, bigtable/bttest/inmem_test.go
Fixes #2600.
After this change running `go test -race .` passes cleanly. Before this change running with `go test -race` I got:
```
==================
WARNING: DATA RACE
Write at 0x00c001112b98 by goroutine 243:
cloud.google.com/go/bigtable/bttest.(*server).DropRowRange()
/usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:264 +0x7b1
cloud.google.com/go/bigtable/bttest.TestTableRowsConcurrent.func3()
/usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem_test.go:331 +0x14c
Previous read at 0x00c001112b98 by goroutine 237:
cloud.google.com/go/bigtable/bttest.(*table).mutableRow()
/usr/local/google/home/coryan/go-develop/bigtable/bttest/inmem.go:1222 +0x21d
cloud.google.com/go/bigtable/bttest.(*server).MutateRow() …
```
=> fix(bttest): fix race condition in SampleRowKeys

pubsublite/internal/wire/publisher.go, pubsublite/internal/wire/rpc.go, pubsublite/internal/wire/service.go, pubsublite/internal/wire/subscriber.go
* Ensure that `NewSubscriber` and `NewPublisher` constructors close all created API clients if they partially fail.
* Added an `apiClientService` base class to handle closing clients when startup fails, as well as after shutdown.
=> fix(pubsublite): ensure api clients are closed when startup fails

internal/kokoro/build_samples.sh
Currently, the work to go mod replace doesn't account for dependency
changes in head.  This adds an explicit step to download modules to
reflect differences in the latest released google-cloud-go vs head.
=> testing: add an explicit module download step to build_samples.sh

internal/godocfx/go.sum, internal/godocfx/index.go, internal/godocfx/index_test.go, internal/godocfx/main.go, internal/godocfx/parse.go
I chose to process all modules at the same time, rather than in separate
invocations of godocfx, so we wouldn't have to make duplicate requests
to the module index.
The docs.metadata generation will probably need to be updated in a
future PR to support different final URL destinations.
=> feat(internal/godocfx): add support for other modules

internal/godocfx/go.mod, internal/godocfx/godocfx_test.go, internal/godocfx/main.go
I refactored the writing of the metadata into a separate function so it can be tested directly.
=> feat(internal/godocfx): different metadata for different modules

pubsublite/internal/wire/partition_count.go, pubsublite/internal/wire/partition_count_test.go, pubsublite/internal/wire/publisher_test.go, pubsublite/internal/wire/rpc.go
* When refreshing topic partition counts in the background for Publishers, retry slowly upon resource exhausted errors. The last `gax.Retryer` found in call options is used, so we introduce a `compositeRetryer` for error codes with different backoff params.
* `partitionCountWatcher` ignores errors after the first update. This is consistent with implementations in the Lite Java and Python client libraries.
=> fix(pubsublite): fixes for background partition count updates

firestore/client.go
=> fix(firestore): return error from NewClient if projectID is not set

internal/gapicgen/cmd/genbot/generate.go, internal/gapicgen/cmd/genbot/local.go, internal/gapicgen/cmd/genbot/main.go, internal/gapicgen/generator/generator.go, internal/gapicgen/generator/genproto.go
Hardcodes go-genproto generation for google/cloud/compute/v1 from googleapis-discovery. We will need to figure out how we support other protos in that repo in the future.
Note: This **deos not** add gapic gen for compute yet.
Note: `compute.pb.go` is approximately 158k LoC 😮 .
cc: @vchudnov-g @software-dov
=> chore(internal): gen googleapis-discovery compute genproto

pubsublite/pscompat/integration_test.go, pubsublite/pscompat/publisher.go, pubsublite/pscompat/subscriber.go, pubsublite/pscompat/subscriber_test.go
Passes the context provided for `New(Publisher|Subscriber)Client` through to gapic clients. This will allow users to pass through a cancelable context, which they can use to quickly terminate the publisher and subscriber clients. This will give users more options to handle various scenarios (e.g. force immediate shutdown, hanging clients).
It was originally not passed through to ensure that we can perform graceful shutdown (e.g. flush pending published. messages, commit cursors, etc), but there are situations where attempts to connect to the server can have long delays. 
All other libraries just pass the context provided to the NewClient constructors through to the gapic clients, so we'll be consistent.
=> fix(pubsublite): wire user context to api clients

bigquery/integration_test.go
More backend changes appear to be inducing two forms of error message,
depending on which component intercepts the error first.  This test
captures both outcomes (we always get an error).
Fixes: https://github.com/googleapis/google-cloud-go/issues/4285
=> fix(bigquery): update streaming insert error test

pubsublite/internal/wire/partition_count.go, pubsublite/internal/wire/partition_count_test.go, pubsublite/internal/wire/publisher_test.go, pubsublite/internal/wire/request_timer.go, pubsublite/internal/wire/request_timer_test.go, pubsublite/internal/wire/streams.go, pubsublite/internal/wire/streams_test.go
Fixes to ensure `PublisherSettings.Timeout` and `ReceiveSettings.Timeout` are respected.
* Adds `requestTimer` for imposing timeouts on requests.
* Sets a limit of 2 min (or less if a lower timeout is provided by the user in settings) for stream initializations to mitigate stuckness. If this duration expires, stream initialization is retried with backoff.
* Sets a timeout for the first update of `partitionCountWatcher` from user-provided settings. This can stall publisher start up.
Minor refactor:
* Changes `retryableStream.setCancel()` to `retryableStream.newStreamContext()`.
=> fix(pubsublite): ensure timeout settings are respected

spanner/client.go, spanner/client_test.go, spanner/pdml.go, spanner/pdml_test.go, spanner/transaction.go
Adds support for request and transaction tags.
After merging this, we should also revert #3987
Reverts googleapis/google-cloud-go#3989 (Reverts the revert of #3233)
=> feat(spanner): support request and transaction tags

pubsublite/admin.go
Since the `createSubscriptionSettings` struct is not exposed, hide the `apply()` func.
=> fix(pubsublite)!: hide CreateSubscriptionOption.apply

internal/gapicgen/cmd/genbot/Dockerfile
* Fixes REST gapic go 1.11 compat
* Stabilizes GAPIC metadata JSON output
Manual regen of compute passed CI: https://github.com/googleapis/google-cloud-go/pull/4364
=> chore(internal): update microgen to v0.21.5

pubsublite/internal/wire/rpc.go
Sets the same grpc keepalive params as the [Java client](https://github.com/googleapis/java-pubsublite/blob/70749d8f4c9cc23937fbb332a5fd168be4ac0d2f/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java#L52).
=> fix(pubsublite): lower grpc keepalive timeouts

pubsub/service.go
The previous iteration of this PR, #4313, only retried GOAWAY in conjunction with an EOF string, which doesn't capture all GOAWAY errors. Now, all error messages with `GOAWAY` and error code `UNKNOWN` are retried.
Fixes #4257
=> fix(pubsub): retry all goaway errors

pubsublite/pscompat/settings.go
Not recommended for timeout to be less than 2 min.
=> docs(pubsublite): recommendation for timeout settings

bigquery/go.mod, bigquery/go.sum, bigquery/storage/managedwriter/flow_controller.go, bigquery/storage/managedwriter/flow_controller_test.go
This PR basically cribs the flow controller code from pubsub, modulo
some minor changes.  Managed writer needs to do the same management
of traffic on a streaming rpc channel, though in this case we'll be
dealing with row appends / responses, whereas in pubsub its messages
and acknowledgements.
Toward: https://github.com/googleapis/google-cloud-go/issues/4366
=> feature(bigquery/storage/managedwriter): add flow controller

bigquery/integration_test.go, bigquery/job.go
This adds the new DMLStats submessage, which indicates the number of
rows inserted/updated/deleted by a DML statement.
It also makes a change to test utility functions to pass back query
statistics.
=> feat(bigquery): add more dml statistics to query statistics

internal/gapicgen/cmd/genbot/Dockerfile
Carries a fix to properly handle `PUT` RPCs in the generator.
=> chore(internal): update microgen to v0.21.8

storage/bucket.go
This call is fully idempotent and retryable according to
go/gcs-api-retry-guidance.
Fixes #4437
=> fix(storage): retry LockRetentionPolicy

spanner/emulator_test.sh
Emulator tests were overwritting the results of the main test
run which can cause errors that occured in main test run not
to be reported when the emulator tests pass. Now emulator tests
append to the test log.
Updates: #4450
=> test(spanner): fix errors not reporting when emulator test passes

spanner/row_test.go
=> test(spanner): fix the failed TestColumnTypeErr test

bigtable/bttest/inmem.go, bigtable/bttest/inmem_test.go
This is a second race condition in SampleRowKeys. As SampleRowKeys
iterates over the rows it needs to grab a lock before using the row, as
the contents of the row may be changed by another thread.
Fixes #2600 (again).
=> fix(bigtable): emulator crashes in SampleRowKeys

pubsub/pstest/examples_test.go, pubsub/pstest/fake.go, pubsub/pstest/fake_test.go
In some of our tests we handle port allocations manually and would prefer to pass in an allocated port for our pstest Server dependency rather than having the `pstest.NewServer` call allocate an available port.
=> feat(pubsub/pstest): add ability to create a pstest server listening on a specified port

pubsublite/internal/wire/rpc.go
To ensure most users don't hit the limit of 100 streams per connection, if they have a high number of topic partitions.
=> fix(pubsublite): set a default grpc connection pool size of 8

internal/.repo-metadata-full.json, internal/gapicgen/execv/gocmd/gocmd.go, internal/gapicgen/generator/gapics.go
=> fix(internal): detect module for properly generating docs URLs

spanner/spansql/sql.go
https://github.com/googleapis/google-cloud-go/pull/4457 made unstable SQL string, and fail test sometimes like this.
```
--- FAIL: TestSQL (0.00s)
sql_test.go:410: {{false [A] [{Table  map[FORCE_INDEX:Idx GROUPBY_SCAN_OPTIMIZATION:TRUE]}] {4 B b <nil>} [] [] []} [] <nil> <nil>}.SQL() wrong.
got SELECT A FROM Table@{GROUPBY_SCAN_OPTIMIZATION=TRUE,FORCE_INDEX=Idx} WHERE B = @b
want SELECT A FROM Table@{FORCE_INDEX=Idx,GROUPBY_SCAN_OPTIMIZATION=TRUE} WHERE B = @b
```
Because map range result is unstable.
This PR makes the SQL output stable by sorting the Hints keys.
=> fix(spanner/spansql): fix unstable SelectFromTable SQL

bigquery/integration_test.go, bigtable/integration_test.go, firestore/integration_test.go, pubsub/integration_test.go
Trying to get our buils back to green. Skipping tests, they should
be unskipped before closing the flaky bot issues.
Updates: #4325
Updates: #4173
Updates: #4418
Updates: #3626
=> test: skip tests that are known to be failing

spanner/integration_test.go, spanner/statement.go, spanner/statement_test.go
Removes the restriction that nil valued parameters must be typed. The current restriction prevents the usage of DML statements with one or more untyped nil parameter values to be used to insert/update a value to NULL. Cloud Spanner does not require all parameters to be typed, only when it would otherwise be ambiguous what type should be used (e.g. non-NULL STRING/BYTES values).
This restriction also prevents the usage of the go/sql driver with gorm, as gorm will generate statements with untyped nil parameter values.
Fixes #4481
=> feat(spanner): allow untyped nil values in parameterized queries

pubsublite/pscompat/integration_test.go
The error may not have propagated to the top-level publisher yet. Ran the test 100 times without error.
Fixes: https://github.com/googleapis/google-cloud-go/issues/4492
=> test(pubsublite): fix flaky TestIntegration_PublishSubscribeSinglePartition

bigquery/storage/managedwriter/appendresult.go, bigquery/storage/managedwriter/appendresult_test.go, bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/integration_test.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
This adds a flow controller to the managed stream, guarding AppendRows.
This change puts the release responsibility for the flow controller in
the markDone() method of the pendingWrite.  Flow controller code is
already well tested via unit tests, so this doesn't add any additional
tests.
Towards: https://github.com/googleapis/google-cloud-go/issues/4366
=> feat(bigquery/storage/managedwriter): wire in flow controller

.github/CODEOWNERS
api-bigtable should be an owner for all bigtable areas.
=> chore(bigtable): update codeowners for bigtable

bigquery/storage/managedwriter/integration_test.go
This PR adds testing to support all stream types, and refactors the
integration test to support parallel testing and reduce some of the
boilerplate code.
Towards https://github.com/googleapis/google-cloud-go/issues/4366
=> test(bigquery/storage/managedwriter): test all stream types

internal/gapicgen/execv/command.go, internal/gapicgen/git/git.go, internal/gapicgen/tools.go
This error was occuring because stdout was being set by some
calling locations which violates Command.Output usage. This
refactors code to never set stdout. I also added some more debug
info of logging the command output which can be useful in the case
of failures.
=> fix(internal/gapicgen): exec Stdout already set

bigquery/storage/managedwriter/appendresult.go, bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/client_test.go, bigquery/storage/managedwriter/doc.go, bigquery/storage/managedwriter/integration_test.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go, bigquery/storage/managedwriter/writer_option.go, bigquery/storage/managedwriter/writer_option_test.go
Minor changes:
WithTracePrefix -> WithTraceID for the option and accompanying downstream usage
exported TableParentFromStreamName to aid users of BatchCommit.
The rest of the PR represents docstring improvements.
Towards https://github.com/googleapis/google-cloud-go/issues/4366
=> feat(bigquery/storage/managedwriter): naming and doc improvements

internal/gapicgen/execv/gocmd/gocmd.go, internal/gapicgen/git/github.go, internal/generated/snippets/go.mod, internal/generated/snippets/go.sum, internal/godocfx/go.sum
=> fix(internal/gapicgen): tidy all after dep bump 

bigquery/storage/managedwriter/integration_test.go
We're now doing enough work that we caught a context deadline in the
managedwriter tests.  Bump the timeout to 30s.
Towards https://github.com/googleapis/google-cloud-go/issues/4366
Fixes: https://github.com/googleapis/google-cloud-go/issues/4523
=> test(bigquery/managedwriter/storage): bump integration test timeout

internal/godocfx/godocfx_test.go, internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
A separate PR will update the template to use this new field.
A future PR here may include a `status` for the overall package and in the TOC.
=> feat(internal/godocfx): mark status of deprecated items

bigquery/storage/managedwriter/integration_test.go
Test was out of sync with comments.  Moved the append out of the loop.
=> test(bigquery/storage/managedwriter): address flakiness

internal/godocfx/parse.go, internal/godocfx/pkgload/load.go, internal/godocfx/pkgload/load_test.go, internal/godocfx/testdata/golden/toc.yml
Follow up from https://github.com/googleapis/google-cloud-go/pull/4525.
=> feat(internal/godocfx): add status to packages and TOCs

bigtable/integration_test.go
Fixes #4503 
Don't require zero backups be present to execute this test.
=> test(bigtable): Allow bigtable backup test to operate in parallel

bigtable/integration_test.go
casting byte vals to string was causing some chars to be (randomly) invalid for identifiers
=> test(bigtable): print hex using %x, sprintf to be valid utf-8

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/integration_test.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
Additional internal context: b/185842996
Request routing relies on a metadata header being present, but because of the bidi nature
library generators don't automatically attach the write stream metadata
into x-goog-request-headers.
For this API, the stream ID is constant for the whole stream so we
inject it when opening the stream, which is when routing needs the
information.
This causes some minor changes to how we do stream (re)open because
we need to pass in the stream ID as part of the function.  This change
also updates integration testing so that we're testing in an explicit,
non-default region (us-east1).
Towards: https://github.com/googleapis/google-cloud-go/issues/4366
=> fix(bigquery/storage/managedwriter): support non-default regions

internal/kokoro/environment.sh
Related to https://github.com/googleapis/google-cloud-go/pull/4561. It looks like the GAE test is also failing for a similar reason.
This PR removes the `gcloud components install` line to install using `apt-get` instead. It also adds a ` | cat` so that the script will continue if installtion fails, in case the package ends up being unnecessary.
Note that this impacts the `environment.sh` test script only currently used by the logging library.
=> chore(tests): fix google-cloud-sdk-app-engine-go installation in test script

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/instrumentation.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/writer_option.go, bigquery/storage/managedwriter/writer_option_test.go
This PR adds a bytes metric to the list of defined instrumentation
metrics, and adds an additional key to track data origin.  Ability
for users to set the data origin comes a new WithDataOrigin option
that can be passed to the managed stream constructor.
This also does some minor refactoring of how opencensus view creation
is handled.
Towards: https://github.com/googleapis/google-cloud-go/issues/4366
=> feat(bigquery/storage/managedwriter): more instrumentation support

pubsub/subscription.go
We use `sync.once.Do(s.checkOrdering)` to perform one config check for a subscription's message ordering field when a message with an ordering key is received. This way, we know if we should deliver messages in order. However, since `sub.Receive` generates multiple goroutines, `s.enableOrdering` is not guaranteed to be read after the first invocation of `s.checkOrdering`. This PR makes this race happen less often by making the config check closer to when the message is received.
This cannot be fully eliminated without making the config call at the start of every single `Receive`. This behavior is less desirable, as we want to make the config call only when we have to, that is when we receive a message with an ordering key. 
Fixes #3626
=> fix(pubsub): mitigate race in checking ordering config

internal/kokoro/environment.sh
Related to https://github.com/googleapis/google-cloud-go/pull/4561
I had attempted to add manual kubectl installation to the environment test script, but there were a couple issues, and the test was still failing. I fixed the issues, and confirmed it works this time by finding and and running the changes inside the `gcr.io/cloud-devrel-kokoro-resources/go111` test container
Note that this impacts the environment.sh test script only currently used by the logging library.
@codyoss, you mentioned we should consider making these changes in the base image. Do you know where I could submit that change?
=> chore(tests): fix kubectl installation in environment test script

storage/storage.go, storage/writer.go
Variable seems to be duplicating information which led to a bug.
This was tested locally against an emulator to ensure other operations on the client now work after an upload. Automated testing for this to come.
=> fix(storage): remove unnecessary variable

pubsub/subscription.go
In the previous iteration of this PR, #4602, the assumption was made that making the config check earlier will prevent race conditions in the test, which turned out to be incorrect. In addition, although previously ruled out as a solution, this PR makes it so that a config check is always made on the first call to `Receive`. I originally thought this would result in a poor experience for those users who don't have the `roles/pubsub.viewer` permission, but we default `enableOrdering` to `true` anyway if the config call fails due to lack of permissions. Using a default of `true` only negatively impacts those who don't want ordering on their subscription, and this behavior is [already documented](https://github.com/googleapis/google-cloud-go/blob/pubsub/v1.14.0/pubsub/subscription.go#L235-L23 …
=> fix(pubsub): always make config check to prevent race

bigquery/bigquery.go
Switches from a local implementation to the logic in internal/detect.
=> feat(bigquery): switch to centralized project autodetect logic

compute/metadata/metadata.go, compute/metadata/retry.go, compute/metadata/retry_linux.go, compute/metadata/retry_linux_test.go, compute/metadata/retry_test.go
This was reported internally to be causing issues. This package is
used by some of our auth flows so it should be good to make this
package more resilient to transient failures. Implementation inspired
by what we do for some of our http based services.
Because this package is currently not context aware I needed to add
attempts so retrying does not happen forever. Five attempts was
arbitrarily chosen.
Fixes: #4642
Release-As: 0.94.0
=> feat(compute/metadata): retry error when talking to metadata service

internal/gapicgen/cmd/genbot/Dockerfile
Updates Go GAPIC generator to v0.23.0. This carries a breaking change for 4 Compute RPCs, switching them back to the raw proto Operation type instead of the wrapped operations. This is intended.
This update also includes several example and pkg doc updates.
=> chore(gapicgen): update Go microgen to v0.23.0

storage/integration_test.go, storage/reader.go
Correctly sets the size to the size of the whole object and
remain to the number of bytes to be read. Adds checks for
Size and Remain to the integration tests.
I used "chore" because this is still experimental, non-exported
code.
=> chore(storage): fix gRPC reader size/remain logic

spanner/spannertest/db_eval.go, spanner/spannertest/funcs.go, spanner/spannertest/integration_test.go, spanner/spansql/parser_test.go
- Adds support for the STARTS_WITH function.
- Adds an example for how further functions can be implemented.
Fixes #4661
=> feat(spanner/spansql): add support for STARTS_WITH function

compute/apiv1/global_operations_client.go, compute/apiv1/region_operations_client.go, compute/apiv1/zone_operations_client.go, internal/gapicgen/cmd/genbot/Dockerfile
Updates microgen to v0.23.1. This incorporates a breaking change for compute that is intended. The heuristics for custom operation wrapping changed to exclude more RPCs (`Wait` RPCs). 
BREAKING_CHANGE_ALLOWED: intended breaking change to alpha client.
=> chore(gapicgen)!: update microgen to v0.23.1

storage/acl.go, storage/hmac.go, storage/notifications.go, storage/storage.go
Certain non-idempotent operations were being retried by the
library, and certain idempotent operations were not. This
fixes the following operations:
Add retry: notifications.delete, service_account.get
Remove retry: bucket_acl.delete, bucket_acl.update,
default_object_acl.delete, default_object_acl.update,
object_acl.delete, object_acl.update, hmacKey.create
Additional PR on conditionally idempotent operations to come.
=> fix(storage): align retry idempotency (part 1)

bigquery/storage/managedwriter/appendresult.go, bigquery/storage/managedwriter/appendresult_test.go, bigquery/storage/managedwriter/integration_test.go, bigquery/storage/managedwriter/managed_stream.go
Previously, AppendRows() on a managed stream would return one
AppendResult per data row.  This change instead switches the
behavior to return a single AppendResult for tracking the behavior
of the set of rows.
The original per-row contract was done in expectation that we'd
consider making batching decisions at a very granular level. However,
at this point it seems reasonable to consider only batching multiple
appends, not dividing individual batches more granularly.
From stress testing, we know we're able to push 50k RPS on a single stream
currently, issuing batches at roughly 1.5 batches per sec.  This change means
that rather than creating 50k AppendResults per sec (and associated channels etc)
that we're instead creating only a single appendresult every 1.5 secs.  Early numbers …
=> refactor(bigquery/storage/managedwriter): change AppendRows behavior

internal/gapicgen/cmd/genbot/Dockerfile, internal/gapicgen/generator/config.go
Updates the microgenerator to v0.23.2 containing a small change to diregapic error wrapping.
Promotes `compute` to `beta` as all breaking changes should be complete.
=> chore(gapicgen): update microgen and promote compute to beta

compute/apiv1/doc.go, go.mod
The new compute beta makes use of xerrors which is causing regen
to fail since we don't depend on this yet. This change will be
blown away by regen, which is intended.
=> fix(internal/gapicgen): add a temporary import

bigquery/integration_test.go, bigquery/iterator.go, bigquery/iterator_test.go
RowIterator can currently come from calling Read() on a Table,
Read() on a Job, and Read() directly from a Query.  The third invocation
is used for fast path queries and doesn't return a query identifier
suitable for gathering statistics.
This PR exposes a SourceJob() method on RowIterator to address this
issue.  Users still get the benefits of optimized query execution, but
can get the reference to a Job for looking up additional statistics
should they need it.
Fixes: https://github.com/googleapis/google-cloud-go/issues/4745
=> feat: expose the query source of a rowiterator via SourceJob()

datastore/doc.go
Previously the documentation said that omitempty omits "zero values"
(linking to the spec), and then says structs aren't (but I didn't find
that part clear the first 5 times I read it).  I found this pretty
unclear, especially since it's burying the fact that it differs from
`encoding/json` in its special handling of `time.Time`.  Hopefully being
more explicit is clearer.
=> docs(datastore): clarify documentation of omitempty

storage/integration_test.go
Skips test mentioned in #4772 and improves logging in the test.
=> chore(storage): skip CancelWriteGRPC test

bigquery/storage/managedwriter/adapt/protoconversion.go, bigquery/storage/managedwriter/adapt/protoconversion_test.go, bigquery/storage/managedwriter/adapt/schemaconversion.go, bigquery/storage/managedwriter/adapt/schemaconversion_test.go, bigquery/storage/managedwriter/appendresult.go, bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/doc.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
This PR updates the managedwriter to use the v1 endpoint of
bigquerystorage for interactions with the BigQueryWriteClient.
Towards: https://github.com/googleapis/google-cloud-go/issues/4366
=> feat: migrate managedwriter to v1 write from v1beta2

internal/godocfx/pkgload/load.go, internal/godocfx/pkgload/load_test.go
See b/197007831.
I added unit tests. But, I also confirmed this works on `google.golang.org/appengine/v2` (`status: preview` shows up in the output YAML).
=> feat(internal/godocfx): detect preview versions

bigtable/integration_test.go
=> test(bigtable): randomize instance name to avoid collision

firestore/document_test.go, firestore/from_value.go
Fixes #4722 by preferring the best matches in pb value to struct code.
=> fix(firestore): prefer exact matches when reflecting fields

storage/reader.go
Simplifies management of leftover bytes from a read message by just reusing the sub-slice of unread content as the `leftovers` instead of maintaining a copy of it. gRPC will allocate the memory to deserialize a message no matter what, so we should just keep referencing that block until we've read it all. Doing some simple profiling shows that this reduces memory allocations even in simple cases because the Reader now longer allocates a new block for leftovers.
=> chore(storage): reuse grpc buffer for leftovers

.github/renovate.json
In the latest version of gRPC the library is no longer compatible
with 1.11. v1.41.0 of gRPC is currently compatible with 1.14+.
Until our versions align we should freeze updating this dependency.
=> chore: freeze gRPC version

bigquery/integration_test.go, bigquery/job.go
Adds a `JobfromProject()` method to allow users to get metadata from a
job that was created within another project.
Fixes: https://github.com/googleapis/google-cloud-go/issues/4228
=> feat(bigquery): allow construction of jobs from other projects

internal/godocfx/parse.go, internal/godocfx/testdata/golden/index.yml
Sometimes, the DocFX Markdown interpreter interprets `*` as `<em>`.
=> fix(internal/godocfx): replace * with HTML code

bigquery/job.go
As part of the changes for
https://github.com/googleapis/google-cloud-go/pull/5048 one callsite of
getJobInternal was missed.  Normally this would easily get identified
due to the change in signature, but getJobInternal has a set of expected
string arguments, followed by variadic string args.  This got picked up
by integration testing, but I failed to recall that presubmit doesn't run
integration tests so it was caught after submit.
Mostly this one's a cautionary tale for having a mix of mandatory and
variadic functions that share the same type.
Fixes: https://github.com/googleapis/google-cloud-go/issues/5058
=> fix(bigquery): address issue from job construction feature

bigtable/integration_test.go
=> test(bigtable): randomize table name to avoid collisions

bigtable/integration_test.go
ctx timeout is the same as the time we wait for a status to propagate. It needs to be larger to not prematurely terminate.
=> test(bigtable): fix #4173, increase ctx timeout

internal/gapicgen/cmd/genbot/Dockerfile
Changes include:
* remove disable service config dial option
* ensure that mix-in protos present in the input file set aren't generated as separate clients when only present for mix-in generation
* dependency updates
=> chore: update microgen to v0.23.4

storage/integration_test.go
This is blocked on an internal change which will take a while
to roll out.
Updates #5124
=> chore(storage): skip gRPC resumable upload test

spanner/integration_test.go
Added logs to debug configName used for integration tests
Fixes: https://github.com/googleapis/google-cloud-go/issues/5037
=> test(spanner): add logs to debug the configName used for TestIntegration_StartBackupOperation test

storage/invoke.go, storage/storage.go, storage/storage_test.go
Adds configurability for how/whether the library will retry
operations. This PR is limited to ObjectHandle methods and
configuration only of backoff timing; however I plan on expanding
this to additional settings (using the same RetryOption framework)
and to all methods which make network calls (via adding Retryer
methods to BucketHandle, etc).
=> feat(storage): add retry configurability

storage/invoke.go, storage/storage.go, storage/storage_test.go
Adds idempotency options to ObjectHandle.Retryer. This allows
users to choose whether only idempotent operations are retried
(default), all operations are retried, or nothing is retried.
In addition, change ObjectHandle.Update and ObjectHandle.Delete
to retry only when idempotency conditions are present by default.
=> feat(storage): add retry idempotency configs

storage/invoke.go, storage/storage.go, storage/storage_test.go
Allows users to supply a custom ErrorFunc which will be used
to determine whether the error is retryable.
=> feat(storage): allow retry ErrorFunc configs

spanner/spannertest/db.go, spanner/spannertest/db_test.go, spanner/spannertest/funcs.go, spanner/spannertest/integration_test.go, spanner/spansql/keywords.go, spanner/spansql/parser_test.go
Adds support for the JSON_VALUE function. The function always returns an empty string,
as there is no XPath query engine available in the Spanner client library. This does
however enable the usage of computed columns that use the function.
This change also fixes the TODO that generated columns cannot be added to non-empty
tables.
Fixes #5167
=> feat(spanner/spannertest): support JSON_VALUE function

storage/copy.go
retry `objects.compose` and `objects.rewrite` on idempotent conditions
=> feat(storage): retry copy funcs on idempotent conds

internal/gapicgen/generator/genproto.go
Reverts googleapis/google-cloud-go#5149
=> chore: re-enable generation for bigtable

bigquery/doc.go
I believe the intention of this example is to show how to introspect errors for more information (such as the error code). This updates the example to use the equality operator instead of assignment operator.
=> docs(bigquery): use equality operator in Errors example

spanner/spannertest/db_eval.go, spanner/spannertest/funcs.go, spanner/spannertest/integration_test.go, spanner/spansql/keywords.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
This adds support for EXTRACT func and similar constructions
Fixes: https://github.com/googleapis/google-cloud-go/issues/5209
=> feat(spanner/spansql): support EXTRACT

storage/writer_test.go
This test fails with the updated version of the apiary library,
but it will be re-enabled with a fix in #5210.
=> chore(storage): skip TestErrorOnObjectsInsertCall

profiler/proftest/proftest.go, profiler/proftest/proftest_test.go
Some structured log messages included unrelated substrings which matched the back off duration regexp, leading to backoff integration tests to fail. This change refines the regexp so that will not happen.
=> fix(profiler): refine regular expression for parsing backoff duration in e2e tests

spanner/internal/benchwrapper/README.md
Update port in SPANNER_EMULATOR_HOST from 8080 to 9010, to have it consistent across client libraries.
=> chore(spanner): update README file for benchwrapper

.github/CODEOWNERS
Now @telpirion is the official owner of these libraries.
=> chore(.github): remove enocom from CODEOWNERS

storage/doc.go
Add more information to package docs about retry strategy, and
give a short example. This will appear in the docs at
https://pkg.go.dev/cloud.google.com/go/storage
=> doc(storage): improve retry package docs

.github/workflows/release-submodule.yaml, .github/workflows/release.yaml
With the big refactor the logic to selectively filter commits on
scope was removed. Until that logic is reinstated we will move
back to v2.
=> chore(.github): revert to v2 of release-please

internal/gapicgen/generator/genproto.go
After running regen locally with `--forceAll`, regen succeeded and `go build ./...` of `go-genproto` succeeded. I think it is safe to enable protobuf/gRPC stub generation for grafeas and containeranalysis.
Note: This **does not** enable gapic generation for these APIs per #2711
=> chore(gapicgen): unfreeze grafeas and containeranalysis stub gen

storage/retry_conformance_test.go
Fixes #5309 which started failing due to the testbench now checking if the bucket exists: https://github.com/googleapis/storage-testbench/commit/4725a24b20ced9ae19037f43126f6949e2a131d7
Made the name unique to be consistent as we are not deleting any resources used in the tests.
=> test(storage): use unique name for bucket insertion to avoid collisions

storage/reader.go
GetObjectChecksums() can return nil if no checksums are present,
so we need to check for nil.
This might just be an emulator artifact but it's probably not a bad idea
to have this check regardless.
=> fix(storage): fix nil check in gRPC Reader

bigquery/bigquery.go, bigquery/bigquery_test.go, bigquery/job.go
https://google.aip.dev/194 guidance is that INTERNAL errors are
considered non-retryable.  This PR deviates from that slightly,
allowing internalError to be retried for job insertion and polling
cases, as the BigQuery backend has an expectation that such work
will be retried.  All other retries continue to use the same retry
predicate.
=> feat(bigquery): augment retry predicate

internal/gapicgen/cmd/genbot/Dockerfile
The only changes that are relevant are for `compute`, including use of `gax.Invoke`, support for header injection via context metadata, and support for URIs with template variables. [Release notes](https://github.com/googleapis/gapic-generator-go/releases/tag/v0.24.0).
=> chore(internal/gapicgen): update microgenerator to v0.24.0

storage/integration_test.go
These tests no longer include upload retries because of the new
idempotency defaults. Changed them to retry regardless of
idempotency.
Fixes #5372
=> test(storage): fix gRPC integration test flakes

compute/metadata/metadata.go
Initialize a resolver and http.Client locally in function to force
GC to cleanup background resources such as cached connections. This
can falsely report as leaked goroutines otherwise. This kind of issue
will still persist for calling methods like ProjectID, but we are
intentionally caching a client and its connections for these occasions
today. If this ends up causing users issues in the future we can
reevaluate at that time.
Fixes: #5430
=> fix(compute/metadata): init a HTTP client in OnGCE check

bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
An exhausted flow controller will emit error rather than block.  When
this occured, we were marking the write done, but allowing the append to
proceed, getting us into another double-close situation, which yields a
panic.
Fixes: https://github.com/googleapis/google-cloud-go/issues/5428
=> fix(bigquery/storage/managedwriter): possible panic due to flowcontrol

pubsub/integration_test.go
The max timeout for `TestIntegration_All` is 1 minute, which is occasionally too short for pulling all required messages for a test to pass. Increasing this timeout to 3 minutes will make synchronous pull tests a lot less likely to flake.
Fixes #5257
=> test(pubsub): increase TestIntegration_All timeout for Pull flakiness

internal/gapicgen/git/git.go, internal/gapicgen/git/git_test.go
This was discovered processing 8e91ed1f2f2cb7fa77240dabcafcd2dedf97bda3.
If a scope is present to be compliant with conventional commits the bang
must be after the scope.
=> fix(internal/gapicgen): move breaking change indicator if present

README.md
In the coming days we will have some more docs and updates around
this change. In general though going forward we will support the
three latest versions of Go. The infrastructure changes around this
will land after more of our documentation does.
=> chore: update supported versions of Go runtime

release-please-config.json
This should open the root component as a separate PR that looks like: https://github.com/googleapis/google-cloud-go/pull/5349 (no expanding sections)
=> build: separate main component

bigtable/doc.go
=> fix(bigtable): use internal.Version that is auto-updated for UA

bigquery/storage/managedwriter/doc.go
Update the package guidance to make it clearer about the current status of the library.
=> docs(bigquery/storage/managedwriter): clarify experimental status

internal/gapicgen/generator/gapics.go
This is currently blocking regen.
=> fix(internal/gapicgen): don't gen version files for longrunning and debugger

bigquery/copy.go, bigquery/copy_test.go, bigquery/extract.go, bigquery/extract_test.go, bigquery/load.go, bigquery/load_test.go, bigquery/query.go, bigquery/query_test.go
This feature allows callers to configure a job timeout.  If a BigQuery
job runs longer than this duration, BigQuery may cancel the job.
We expose JobTimeout in each of the job config types, given the existing pattern.
Fixes: https://github.com/googleapis/google-cloud-go/issues/3613
=> feat(bigquery): add job timeout support

pubsub/doc.go
For more information, see https://github.com/GoogleCloudPlatform/golang-samples/issues/2456
=> docs(pubsub): clarify ack/nack cannot be called from goroutine

spanner/integration_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/5709
=> test(spanner): skip TestIntegration_StartBackupOperation test with PG dialect because of timeouts

internal/gapicgen/generator/config.go
We should disable generation of GAPIC retries for Storage as the GAPIC will be used inside of the Veneer that will instead handle the retry of API calls in a uniform way between transports.
=> chore(internal/gapicgen): disable storage gapic retry

storage/client.go
Adds a `userProject string` field to the transport-agnostic client settings and a `withUserProject` `storageOption` to modify it at either the client init or per-call level.
=> chore(storage): add withUserProject internal setting option

storage/integration_test.go
- Increases the context deadline for the test, 10s seems to have been too short - fixes #4720
- Changes the formatting to print error so the error is in the first line
- Removes check and attempts to delete copy and compose objects even on failure (it's okay if the deletion fails as the test has already failed in that case). The objects may be created even if there was a reported failure.
=> test(storage): increase context deadline for RequesterPays

compute/apiv1/smoke_test.go
=> test(compute): longer timeout for flaky test

storage/integration_test.go
This test is taking more than 40 minutes to run, causing the storage tests to timeout and failing in progress tests
Fixes #5786, #5787, #5788, #5789
Fixes #5780, #5781, #5782, #5783
=> test(storage): skip ObjectReadGRPC integration test that causes timeout

storage/integration_test.go
Buckets will be cleaned up anyway, so I added the error check back to the cleanup
=> test(storage): use t.Cleanup for requesterpays test

bigquery/integration_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/5809
=> test(bigquery): make policy tag setup use unique display names

spanner/integration_test.go
Spanner databases with no rows creates backup of size 0 now, this PR will insert row in the table before creating the backup
Fixes: https://github.com/googleapis/google-cloud-go/issues/5804
=> test(spanner): fix backup spanner test failing because of zero sizeBytes

storage/bucket.go, storage/client_test.go, storage/grpc_client.go
Resolve TODOs around use of predefined ACL strings in proto-based code.
Refactor emulator tests to run as sub-tests, and push boilerplate code into helper function.
=> chore(storage): refactor emulator tests, resolve some TODOs

internal/gapicgen/cmd/genbot/Dockerfile
v0.28.0:
- regapic automatic header injection
- regapic gax.WithPath override support
- regapic handle url.Parse errors
v0.27.0:
- dependency updates
- bazel workspace refactor
- regapic server streaming support
=> chore(internal/gapicgen): update microgenerator to v0.28.0

pubsub/pstest/fake.go, pubsub/pstest/fake_test.go
**Client**
PubSub
**Go Environment**
go version go1.17.1 linux/amd64
**Description**
The testing fake pubsub implementation does not yet support the new enable_exactly_once_delivery field in the UpdateSubscription method.
**Expected behavior**
When a Subscription is updated to set EnableExactlyOnceDelivery with UpdateSubscription, the RPC should not return an error and the subscription should be modified.
**Actual behavior**
The RPC returns InvalidArgument with: unknown field name "enable_exactly_once_delivery"
=> fix(pubsub): enable updating enable_exactly_once_delivery in fake pubsub

pubsublite/go.mod, pubsublite/internal/test/util.go, pubsublite/internal/wire/errors.go, pubsublite/internal/wire/partition_count.go, pubsublite/internal/wire/publish_batcher.go, pubsublite/internal/wire/publish_batcher_test.go, pubsublite/internal/wire/streams.go, pubsublite/pscompat/example_test.go
Remove usages of `xerrors` in `pubsublite` now that the minimum supported Go version has increased.
=> refactor(pubsublite): remove usages of xerrors

spanner/integration_test.go, spanner/oc_test.go
Fix: https://github.com/googleapis/google-cloud-go/issues/5871
For PG dialect support there was no change made in open-census stats flow, hence no need to run separate test with PG dialect, since the test run in parallel so it's causing flaky issues when checking common tags. This PR will skip the not needed tests.
=> test(spanner): skip flaky test for oc_stats  with PG dialect.

storage/client_test.go, storage/grpc_client.go, storage/http_client.go
This adds ListBucketACLs and ListDefaultObjectACLs implementation
=> chore(storage): implement ListBucketACLs and ListDefaultObjectACLs

profiler/profiler.go, profiler/profiler_test.go
With this change, profiling agents can be run with App Engine applications whose service names start with number.
=> fix(profiler): relax service name regexp to allow service name to start with number

datastore/query.go, datastore/query_test.go
Reverts googleapis/google-cloud-go#5975 
Feature not ready for release yet
=> Revert "feat(datastore): adds in, not-in, and != query operations"

.github/renovate.json
Switching the group name should make changes come from a new branch on the renovate fork I believe. This may fix the issue that we are no longer getting PRs from our current branch.
=> chore: try to get renovate working

storage/go.mod, storage/go.sum, storage/grpc_client.go
=> fix(storage): bump genproto, remove deadcode

logging/logging.go, logging/logging_test.go, logging/logging_unexported_test.go
auto-populate the ingest log entry with the source location of the calling code including file name, function name and code line number.
provide designated logger option: `SourceLocationPopulation` to control source population logic. The option can be initiated with the following values:
* `SourceLocationPopulation(DoNotPopulateSourceLocation)` - continue with existing behavior when the source location field of the log entry is not populated automatically (default)
* `SourceLocationPopulation(PopulateSourceLocationForDebugEntries)` - the source location is auto-populated for log entries with Debug severity
* `SourceLocationPopulation(DoNotPopulateSourceLocation)` - the source location is auto-populated for all log entries
=> feat(logging): implement auto-population of the calling source location

logging/resource_test.go
Adding a benchmark test to measure execution time for detectResource() to address #5855.
Current implementation uses cloud.google.com/go/compute/metadata package to read Google Cloud metadata server attributes. The package implements retrying mechanism to cover on occasional problems of miscommunication with the metadata server. When a new Logger instance is being created, it calls detectResource() to read the monitored resource object. The resource detection algorithm is invoked once per process (regardless of how many Logger instances is created). The algorithm checks whether the environment runs the metadata server as a first step and to avoid further validations. Due to the retrying mechanism, this call may take between 6 to 7 seconds which composes the overall delay of creating a …
=> chore(logging): add detectResource benchmark

logging/logging.go, logging/logging_test.go
Add PartialSuccess option to set partialSuccess flag in WriteLogEntries calls to true
Implements #3824
=> feat(logging): support partialSuccess flag for batched ingestions

bigquery/bigquery.go, bigquery/intervalvalue.go, bigquery/job.go, bigquery/routine.go, bigquery/schema.go, bigquery/standardsql.go, bigquery/storage/managedwriter/adapt/error.go, bigquery/storage/managedwriter/adapt/protoconversion.go, bigquery/storage/managedwriter/client.go
Did a quick audit to check for error formatters where we could potentially
wrap errors and were not currently.
This PR also added an explicit unwrapper to the custom error type exposed in bigquery/storage/managedwriter/adapt
Explicitly did not audit/update test code.
=> chore(bigquery): switch existing formatters to enable error wrapping

pubsub/topic.go
Should fix compatibility with 32-bit architectures.
Closes #6112.
=> fix(pubsub): use MaxInt instead of MaxInt64 for BufferedByteLimit

pubsub/iterator.go, pubsub/iterator_test.go
The new method `addToDistribution` added to support `MinExtensionPeriod` incorrectly sets the bounds (needed to reverse min/max duration).
Fixes #6123
=> fix(pubsub): fix iterator distribution bound calculations

internal/gapicgen/generator/config.go
Similar reasons to https://github.com/googleapis/go-genproto/pull/824
=> chore: adjust assuredworkload yaml file name

bigquery/internal/version.go, bigquery/storage/managedwriter/integration_test.go, bigquery/storage/managedwriter/managed_stream_test.go
This PR addresses linter/tricorder errors surfaced when importing this
library internally.  See cl/454723109 for examples.
=> chore(bigquery): cleanup some lint errors

internal/gapicgen/cmd/genbot/Dockerfile
Update GAPIC generator to v0.31.0. Changes _since the last update_ include:
* generator support for protobuf-go `go_package` cli option `-Mproto=importpath`
* REGAPIC retry support
* REGAPIC encode enums as numbers
* REGAPIC fix path param parsing to remove duped query param
* REGAPIC LRO support
=> chore(internal/gapicgen): update generator to v0.31.0

pubsublite/internal/wire/rpc.go, pubsublite/internal/wire/rpc_test.go, pubsublite/internal/wire/version.go, pubsublite/internal/wire/version_test.go
The major and minor versions should be sent as struct number values, rather than string values.
=> fix(pubsublite): fixed version in stream headers

bigquery/integration_test.go
in the first, the integration tests running too long came into conflict
with a expiration time that was too short.  Lengthened the expiration used
in the test to something more accomodating.
In the second, cleanup some usages of xerrors in testing that can be moved to
errors as we're now no longer supporting older go versions.
Fixes: #6198
Fixes: #6199
=> test(bigquery): address minor test issues

bigquery/storage/managedwriter/integration_test.go
Ironically, the test to do more concurrent things to trigger a specific
kind of race condition itself added a new kind of concurrency data race.
This switches from using shared variables for checking results to
goroutine-local versions.
Fixes: #6171
=> test(bigquery/storage/managedwriter): address data race

logging/README.md, logging/doc.go, logging/instrumentation.go, logging/internal/common.go, logging/internal/environment.go, logging/loggeroption.go, logging/logging.go, logging/logging_test.go, logging/logging_unexported_test.go, logging/resource.go, logging/resource_test.go
Align resource detection with heuristics in logging libraries for other languages (PR #6022)
Adds automatic population of the source location for ingested log entries with severity = Debug (PR #6043)
Adds benchmark for detectResource() to validate the long delays of the logger creation in non-GCP environments (PR #6084)
Adds PartialSuccess logger option to set the partialSuccess flag in all write log entries calls to true (PR #6092)
Adds support for W3C trace context header: `traceparent` in addition to X-Cloud-Trace-Context (PR #6101)
Adds RedirectToStderr and RedirectToStdout logger options to enable printing Jsonified log entries to STDOUT or STDERR instead of ingesting them directly to Cloud Logging (PR #6130)
Adds sending instrumentation info about the package on each use (one time …
=> feat(logging): support structured logging functionality

.github/release-please.yml
This setting is not read from the manifest config today so it is best for us to set it here for now as well. This guidance was given in https://github.com/googleapis/repo-automation-bots/issues/4032
Fixes: #5964
=> chore: add releaseType to config

pubsub/iterator.go
Increase modack deadline timeout to align with ack timeout of 60s. The default of 2 seconds can be too low for environments with higher network latency and can cause messages to be redelivered frequently.
Internal only, see guidance for internal deadlines of ModAckDeadline: screen/B68KaMcqgPbmg4u
=> fix(pubsub): increase modack deadline RPC timeout

spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go
#6148 introduced a bug in the way `INSERT` statements are produced.
Currently, INSERT statements produced by the parser are invalid, for example:
```
INSERT Singers INTO ...
```
Where the [correct form](https://cloud.google.com/spanner/docs/reference/standard-sql/dml-syntax#insert-statement) should be:
```sql
INSERT INTO Singers ...
-- or
INSERT Singers ...
```
The first form (INSERT INTO) has been chosen as it aligns with the [documented examples](https://cloud.google.com/spanner/docs/reference/standard-sql/dml-syntax#insert_examples).
This PR addresses the issue and adds necessary tests.
=> fix(spanner/spansql) Add tests for INSERT parsing, fix INTO bug

pubsub/iterator.go, pubsub/iterator_test.go, pubsub/message.go, pubsub/service.go, pubsub/subscription.go
This PR corresponds with the 6th point in the PR sequencing doc. Logic is derived from Python's `process_requests` function.
=> feat(pubsub): add helper method for parsing ErrorInfos

bigtable/admin.go, bigtable/admin_test.go, bigtable/go.mod, bigtable/go.sum
Exposes the [`StorageUtilizationGibPerNode`](https://pkg.go.dev/google.golang.org/genproto/googleapis/bigtable/admin/v2#AutoscalingTargets) field for Bigtable autoscaler.
=> feat(bigtable): adds autoscaling target storage per node

internal/gapicgen/generator/config.go
This is currently blocking generation.
Fixes: #6363
=> chore: fix config pass for assuredworkloads

bigquery/storage/managedwriter/integration_test.go
When a user issues a large request, the response from the
backend is a bare "InvalidArgument".  This PR removes additional
validation on information that is only attached when interrogating
the backend from a known client; it's stripped in the normal case.
Internal issue 239740070 was created to address the unactionable
nature of the response.
Fixes: https://github.com/googleapis/google-cloud-go/issues/6361
=> test(bigquery/storage/managedwriter): relax error checking

storage/integration_test.go
Few minor changes to make sure potentially flaky and/or
eventually consistent operations for ACLs are retried appropriately.
Fixes #6379
=> test(storage): unflake TestIntegration_ACL

firestore/bulkwriter.go, firestore/bulkwriter_test.go
=> chore(firestore): add missing license headers

storage/client.go, storage/copy.go
This takes out a few lines of boilerplate that will be
present in all top-level methods.
=> chore(storage): add makeStorageOpts helper

storage/hmac.go
Migrate HMAC operations to transport-agnostic interface.
Integration tests pass locally for HMAC operations.
=> chore(storage): migrate HMAC operations

storage/client.go, storage/copy.go, storage/grpc_client.go, storage/http_client.go, storage/integration_test.go
Migrate Copier to use the new transport-agnostic interface.
I found one additional piece of data that needs to be passed back
through the interface in the process (object size).
I removed one integration test. This test is old and currently
calls rewriteObject in a way that an external library user could
not accomplish. I don't think this test adds any value.
=> chore(storage): migrate Copier

storage/bucket.go, storage/client.go, storage/client_test.go, storage/grpc_client.go, storage/http_client.go, storage/storage.go, storage/storage_test.go
Migrate few top-level methods to transport-agnostic interface.
- GetServiceAccount
- ListBuckets
- CreateBucket*
*Interface refactoring
Shown in the [current implementation](https://github.com/googleapis/google-cloud-go/blob/main/storage/bucket.go#L91), bucketName is referenced from `BucketHandle`, so proposing to include `bucket string` as an arg for method `CreateBucket()`
Integration tests pass locally
=> chore(storage): migrate top-level methods

storage/iam.go
Migrate IAM operations to transport-agnostic interface
- GetIamPolicy
- SetIamPolicy
- TestIamPermissions
This PR adds `*Client` to `iamClient` so we can access the transport-agnostic interface
Integration tests pass locally for IAM
=> chore(storage): migrate IAM operations

internal/kokoro/presubmit.sh
Code is built when testing it, but some type of build failures are
not properly translated by the junit converter we use. Adding this
extra build will catch this previously missed failures and should
affect test time minimally as builds will have been cached.
Fixes: #6439
=> test: start building all code

storage/acl.go
Migrate ACL ops to the new transport agnostic interface. No
interface changes were necessary for this one and tests pass.
=> chore(storage): migrate ACL operations

storage/integration_test.go, storage/notifications.go
Migrates the Notification APIs to the transport agnostic surface. Integration tests passed and added a check to ensure that AddNotification returns a Notification with a non-empty ID.
=> chore(storage): migrate Notification methods

internal/kokoro/continuous.sh
We only need this for continuous builds so I only updated this shell script.
Reviewed repository for kokoro job name: 
```
git grep "github/google-cloud-go"
internal/kokoro/build_samples.sh:gcwd=$PWD/github/google-cloud-go
internal/kokoro/continuous.sh:cd github/google-cloud-go
internal/kokoro/environment.sh:    PROJECT_ROOT="github/google-cloud-go"
internal/kokoro/environment.sh:cd "${KOKORO_ARTIFACTS_DIR}/github/google-cloud-go/internal/"
internal/kokoro/presubmit.sh:cd github/google-cloud-go
internal/kokoro/publish_docs.sh:cd github/google-cloud-go/internal/godocfx
```
Manually triggered test
```
https://fusion2.corp.google.com/invocations/5224e509-df4f-413e-9f43-9d0b35ead566/targets
```
=> test: update continuous.sh for storage-refactor

storage/bucket.go, storage/bucket_test.go, storage/storage_test.go
Migrate Bucket operations to transport-agnostic interface. Integration tests pass locally
- DeleteBucket
- GetBucket
- UpdateBucket
- LockBucketRetentionPolicy
- ListObjects
Part of the migration
- removed Bucket helpers `new{Get/Delete/Patch}Call`
- similar to ListBuckets, removed internal fetch method that is no longer used by the iterator
=> chore(storage): migrate bucket methods

pubsub/doc.go
As part of discussion in #6129, the section on streams management needs to be updated.
=> docs: fix incorrect connection pool documentation

storage/grpc_client.go, storage/internal/apiv2/metadata.go
For gRPC, include the `bucket` ID (not resource name) in the `x-goog-request-params` header with the key `bucket` on the initial WriteObject RPC. All other RPCs, which are Unary on the client-side, are handled by the GAPIC layer for this. 
Instead of writing yet-another-header-injection helper, I exported the one form the GAPIC layer to reuse in the Veneer.
Fixes http://b/238793493 for Go.
=> chore(storage): gRPC inject bucket ID in header for write

pubsub/go.mod, pubsub/go.sum, pubsub/iterator.go, pubsub/iterator_test.go, pubsub/message.go, pubsub/streaming_pull_test.go, pubsub/subscription_test.go
Pipe the output of Ack/Modack operations to AckResult that are returned when users call Ack/NackWithResult. This involves removing a callback and makes `sendAck` and `sendModAck` have repeated code. However, removing the callback also makes it more readable. In addition, we don't infinitely retry these methods until they fail anymore, since that will be handled by a later PR.
To support this, this PR also includes
1. Switching `processResults` back to using a map[string]string for ackID->error strings (since that's what apiError metadata field returns)
2. Changing the output of `processResults` and `pending` maps to use a new struct that contains both ackIDs and AckResult (for retrying later on)
3. Capping the max number of ackIDs per ack/modack to 2500 (which is in line with Python) …
=> feat(pubsub): complete AckResult for exactly once

storage/grpc_client.go, storage/http_client.go, storage/storage_test.go, storage/writer.go
Migrate Writer to use the transport-agnostic interface. A few
minor fixes:
* Pass in retry, idempotency and user project via settings rather
than determining below interface.
* Use default generation since this can't be sent for this call.
=> chore(storage): migrate Writer

storage/client.go, storage/grpc_client.go, storage/http_client.go, storage/reader.go, storage/reader_test.go
Migrate the Reader to use the new transport-agnostic interface.
A few minor fixes were required:
* Move validations above interface
* Add settings for call and fix up userProject for gRPC
* Add param for sending with accept-encoding: gzip (HTTP only)
* Fix up reader resumption test
=> chore(storage): migrate Reader

pubsub/integration_test.go, pubsub/iterator.go, pubsub/iterator_test.go, pubsub/pstest/fake.go, pubsub/service.go, pubsub/streaming_pull_test.go, pubsub/subscription.go, pubsub/subscription_test.go
This PR adds the logic for retrying temporary ack/modack (including nack) failures for exactly once delivery.
Some other changes captured in this PR
1. Updating `subscription_test.go` and `integration_test.go` to support exactly once delivery for publish/subscribing.
(Git diff is not great here, but a lot of changes just  involves moving a lot of the publish/receive test code into a sub-test function so they can be invoked in parallel. Not much logic change.)
3. Reverted all `ackResultWithID` to just be `AckResult`. Passing around the map of ackID->AckResult works best and we just needed to be consistent.
=> feat(pubsub): retry temporary failures for ack/modacks

internal/gapicgen/cmd/genbot/Dockerfile, internal/gapicgen/generator/config.go, internal/gapicgen/generator/gapics.go
Update Go GAPIC generator to v0.32.0 ([notes](https://github.com/googleapis/gapic-generator-go/releases/tag/v0.32.0)).
Also adds support for new generator option to the `MicrogenConfig` to toggle generation of the numeric enum encoding parameter.
cc @vchudnov-g @vam-google
=> chore(internal/gapicgen): update microgen v0.32.0

bigquery/storage/managedwriter/integration_test.go
The integration testing for instrumentation can suffer from races, and
the failure mode here induces panic which incorrectly implicates other
tests run as part of the test group.
This small change avoid the indexing problem so that future failures
only implicate the instrumentation test.
Fixes: #6535
Fixes: #6534
Fixes: #6533
Fixes: #6532
Fixes: #6531
Fixes: #6530
Fixes: #6529
Fixes: #6528
Fixes: #6527
=> test(bigquery/storage/managedwriter): improve instrumentation testing

bigquery/storage/managedwriter/integration_test.go
We've caught more than one instance of a race failure.  Add retries
for the opencensus metrics test to reduce the likelihood of this
failures.
Fixes: #6535
=> testing(bigquery/storage/managedwriter):  instrumentation retries

storage/bucket_test.go
When https://github.com/googleapis/google-api-go-client/pull/1598 is released; these tests will break due to the breaking change. This is a preemptive PR to skip these tests which will be reenabled once the break is released.
=> test(storage): skip tests using OLM Age condition

internal/kokoro/environment.sh, internal/kokoro/publish_docs.sh
These will be backed directly into the image.
Related: https://github.com/googleapis/testing-infra-docker/pull/222
=> chore: remove installing python deps

pubsub/go.mod, pubsub/go.sum, pubsublite/go.mod, pubsublite/go.sum
In #6506 changes to internal were made that are not apart of the
pubsub module. The pubsub module was released before the internal
changes were released resulting in build errors for those that
pulled the latest pubsub version.
Fixes: #6555
=> fix(pubsub): up version of cloud.google.com/go

pubsub/subscription_test.go
Sometimes a nacked message in the subscription test will cause the message to be redelivered right away. Since the context is cancelled after the first nack, this causes a race condition with the test. The simple solution is to just use a different context that is not affected by the by calling `cancel()`.
Closes #6561
=> test(pubsub): use background context for nack test

internal/kokoro/continuous.sh, internal/kokoro/presubmit.sh
Our tools are only expected to run with the latest go version we
support. So for those directories skip running tests on old Go
versions.
=> chore: don't test tools with earliest

doc.go
This doc addition is required for an upcoming PR for snippets comments that:
> should include a link to documentation that describes how to set a regional endpoint for that language's service clients. For instance, the .NET link is: https://cloud.google.com/dotnet/docs/reference/help/client-configuration#endpoint.
See b/240118976
=> docs: add client options endpoint to doc.go

internal/gapicgen/cmd/genbot/Dockerfile
This allows the replace statements in the go.mod to work properly
=> chore(internal/gapicgen): rescope genbot context to include repo

bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/retry.go, bigquery/storage/managedwriter/retry_test.go
This PR augments the reconnection logic to include the grpc transport
stream drain error as a condition where we should force reconnect,
rather the waiting for the io.EOF of the connection fully closing.
Related: https://github.com/googleapis/google-cloud-go/issues/6595
=> feat(bigquery/storage/managedwriter): augment reconnection logic

spanner/spannertest/db_test.go, spanner/spansql/sql.go
=> feat(spanner/spansql): add backticks when name contains a hypen

internal/aliasfix/aliasfix.go
- Use os.Create to truncate existing file if needed
- Use named imports to capture error
- Create a bak incase anything goes wrong. We don't want to delete peoples code :)
- Bubble up error if any from WalkDir
=> chore(internal/aliasfix): properly truncate and backup files

storage/grpc_client.go, storage/integration_test.go
Ensures that when using gRPC an attempt to read an object that does not exist returns the `ErrObjectNotExist` error, like it does in HTTP.
=> chore(storage): fix Object Read not exist error

bigquery/integration_test.go, bigquery/params.go
Timestamps on BigQuery have a [format similar to RFC3339](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#canonical_format_for_timestamp_literals). 
When creating a Query Job via the API, users can pass a timestamp with string `2020-10-15T00:00:00Z`, which is a valid parameter.  But if a given Job was created with a `TIMESTAMP` following that format and is read back using this library, it fails (as reported on https://github.com/googleapis/google-cloud-go/issues/6651 ) because we expect `TIMESTAMPS` to have only [this format](https://github.com/googleapis/google-cloud-go/blob/5de75ddd406c0f1506a3f5ab835c0cae1f5f4b7a/bigquery/params.go#L33): `"2006-01-02 15:04:05.999999-07:00"`
This PR also tries to parse `TIMESTAMPS` using Go `RFC3339Nano`, similarly on how the …
=> fix(bigquery): parse timestamp query parameter with RFC3339

internal/gapicgen/cmd/genbot/Dockerfile
Includes fix for well-known types in query parameters of Paginated methods for REGAPICs https://github.com/googleapis/gapic-generator-go/issues/1132
=> chore: update generator to v0.33.1

internal/gapicgen/generator/genproto.go
We had a false negative show up today where change for: "google.golang.org/genproto/googleapis/storagetransfer" were not generated when they should have been.
=> fix(internal/gapicgen): add slashes to be more strict with matching
