googleapis/google-cloud-go

spanner/client_test.go, spanner/retry.go, spanner/transaction.go
* Clients need to retry the Spanner transactions in case of RST_STREAM error returned from the backend
=> feat(spanner): retry spanner transactions and mutations when RST_STREAM error

internal/gapicgen/generator/gapics.go
- Add a tidy after replace. The genproto dependency is getting more complex as it now associates with many aliases. A tidy is now requried.
- Since we are tidying we can no longer just simply drop the replace as there would have been dependency updates because of the tidy. Instead we can achive the same effect by using git restore.
=> chore: update how we handle mod replacements

internal/aliasgen/aliasgen.go
Some clients, like aiplatform, have a nested folder structure under the client directory. In these cases we only are generating aliases for a specific dir, so we should only remove the files associated to said dir, and not the recursive dir structure as a whole.
=> chore(internal/aliasgen): only remove files when cleaning dir

bigquery/storage/managedwriter/retry.go
Per guidance from backend team, include FailedPrecondition as part of the allowed retry.
=> feat(bigquery/storage/managedwriter): retry on FailedPrecondition

storage/grpc_client.go
I missed a case where the shouldRetry function could be nil in #6754, which causes a panic in integration tests.
Fixes #6760 (this is the actual failure)
Fixes #6757
Fixes #6758
Fixes #6759
=> chore(storage): fix retry propagation for gRPC

.release-please-manifest-submodules.json, certificatemanager/CHANGES.md, certificatemanager/internal/version.go
<details><summary>certificatemanager: 1.1.0</summary>
* **certificatemanager:** added support for Private Trust to Certificate Manager API ([92b2f99](https://github.com/googleapis/google-cloud-go/commit/92b2f991244687c662e9e07801e1fae9bcea9a8b))
</details>
=> chore: release certificatemanager 1.1.0

storage/writer.go
https://github.com/googleapis/google-cloud-go/issues/6816
`w.monitorCancel()` -> `w.CloseWithError()` reads the values of `w.opened` and `w.pw` concurrently with the calling routine initializing them; if the incoming context is cancelled before or during initialization.
The fix is simply to deploy starting the monitor until all fields are initialized.  The older `open()` code from previous releases did this in the right order:
https://github.com/googleapis/google-cloud-go/blob/storage/v1.24.0/storage/writer.go#L130-L134
=> fix(storage): fix read-write race in Writer.Write

storage/copy.go
This fixes infinite retry issues.
Will follow up with tests to catch this behaviour.
Fixes #6857
=> fix(storage): fix request token passing for Copier.Run

pubsub/message.go
=> docs(pubsub): fix comments on message for exactly once delivery

internal/generated/snippets/go.mod, internal/generated/snippets/go.sum, storage/go.mod, storage/go.sum, storage/grpc_client.go, storage/integration_test.go
Adds content type sniffing to the gRPC Writer implementation. This uses the newly copied to gax `DetermineContentType` API, originally from google.golang.org/api/internal/gensupport.
This upgrades some dependencies to do so.
=> chore(storage): add content type sniffing to gRPC writer

.github/workflows/apidiff.yml
Only apidiff directories with `.go` file changes.
Note: `*/internal/version.go` files will not trigger it.
=> chore(ci): only apidiff directories with go file changes

datastore/doc.go
=> docs(datastore): adds emulator instructions

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
Previously, we needed to inject a routing header when opening the bidi AppendRows connection to successfully route traffic to the correct region.  Routing no longer needs this explicit hint, and works by examining the requests on the stream.
This change removes the header injection, and also simplifies the open contract we use to no longer include a stream ID, which was in place solely for the injection.
Related internal issue: 185842996
=> fix(bigquery/storage/managedwriter): remove old header routing

bigtable/internal/testproxy/proxy.go
This PR applies the perOperationTimeout setting to the context object for each client call.
=> chore(bigtable): add timeouts to proxy methods

storage/integration_test.go
=> test(storage): add gRPC error code to retry to fix flaky PAP test

bigtable/internal/testproxy/proxy.go, bigtable/internal/testproxy/proxy_test.go
This PR:
* Changes how table IDs are passed to `Client.Open()`
* Changes the error returned to the caller for a closed client.
=> chore(bigtable): more text proxy tune-up

storage/grpc_client.go, storage/integration_test.go, storage/storage.go
Enables use of customer provided encryption for Object media operations (Read, Rewrite, Write (including resumable), etc.).
Enables both `TestIntegration_Encryption` and `TestIntegration_KMS` for gRPC.
=> chore(storage): gRPC support customer encryption

spanner/integration_test.go, spanner/value.go, spanner/value_test.go
This PR contains implementation changes to add support for handling null values in Proto Messages and Proto Enum type columns. Also the PR has changes to get `protoTypeFqn` for nil types.
=> feat(spanner): add support for handling null value in Proto columns

internal/gapicgen/cmd/genbot/Dockerfile
Upgrade version of base image to sufficiently new version. This gets us on a newer version of Alpine Linux (`3.16.2`) which gets us on a newer version of `protoc` (`3.18.1`). This is not the newest version of `protoc`, but it includes the necessary `go_package` annotation updates to the common protos that protobuf maintains to upgrade our dependency to the "new" protobuf-go repo distributions.
`docker:20.10`
Alpine Linux: `3.16.2`
Protobuf: `3.18.1-rc3`
Fixes #7031
=> chore(genbot): upgrade base image and protoc

spanner/integration_test.go, spanner/value.go, spanner/value_test.go
This PR contains implementation changes to add support for handling array of Proto Messages and Proto Enum type columns.
To run integration tests, set the below environment variables:
```
GCLOUD_TESTS_GOLANG_PROJECT_ID=span-cloud-testing
GCLOUD_TESTS_GOLANG_SPANNER_HOST=staging-wrenchworks.sandbox.googleapis.com:443
```
=> feat(spanner): add support for Array of Proto columns

spanner/integration_test.go, spanner/key.go, spanner/key_test.go
This PR has the following changes,
1. Adds support for Enum columns in primary key and indexes.
2. Integration tests for Parameter Binding.
3. Integration tests for Proto fields and Enum columns as Primary keys.
4. Integration tests for Proto fields and Enum columns as Indexes.
=> feat(spanner): support for enum columns as keys, index and integration tests

.github/renovate.json, bigtable/go.mod, bigtable/go.sum, logging/go.mod, logging/go.sum, profiler/go.mod, profiler/go.sum, pubsub/go.mod, pubsub/go.sum, storage/go.mod, storage/go.sum
Although the way we rely on these modules today is compatible with 1.15 the whole module itself is not at these revisions. This makes our dependency on them quite fragile and error prone. To be safe I am downgrading and freezing some dependencies until we support a min version of 1.17
Changes:
fix(bigtable): downgrade some dependencies
fix(profiler): downgrade some dependencies
fix(logging): downgrade some dependencies
fix(pubsub): downgrade some dependencies
fix(storage): downgrade some dependencies
=> chore: downgrade some dependencies

bigtable/bttest/inmem.go
Correct how CellsSeenCount and CellsReturnedCount are calculated in the CBT emulator. The current implementation retrieves the length of the wrong map. It gives incorrect results (compared to production) for certain integration tests when emulator use is allowed.
The emulator and production still disagree on CellsSeenCount for some tests. This could be due to optimizations in production that would be out of scope for the emulator. I'll make the tests a bit more lenient in a follow-up PR.
=> fix(bigtable/bttest): correct CellsSeenCount and CellsReturnedCount calculations

internal/gapicgen/cmd/genbot/Dockerfile, internal/gapicgen/generator/config.go
fix(osconfig/agentendpoint/v1beta1): disable REST transport generation
fix(mediatranslation/v1beta1): disable REST transport generation
chore(internal/gapicgen): update microgenerator to v0.33.5
As a result of updating the generator, when `rest` is a selected transport for a package, proto services lacking a REST-enabled method will not get a REST client type generated. This will break `videointelligence/v1p3beta1` as a result. The aforementioned fixes are also breaking changes for those packages, but being in beta it is allowable.
=> fix(internal/gapicgen): disable rest for non-rest APIs

spanner/session.go
This will make the SessionNotFound check similar to [C++](https://github.com/googleapis/google-cloud-cpp/blob/21bad1fc7c22d472f8ba8d9194dfe54342c29e2b/google/cloud/spanner/internal/status_utils.cc#L28-L50) and [NodeJS](https://github.com/googleapis/nodejs-spanner/blob/main/src/session-pool.ts#L226) client libraries.
=> fix(spanner): fallback to check grpc error message when ResourceType nil

profiler/integration_test.go, profiler/kokoro/integration_test.sh
Update the Go cloud profiler agent to be able to run in the new Kokoro VMs.
=> fix: update test to be compatible with new containers

profiler/kokoro/integration_test.sh
Contains the safe directory git issue fix to resolve - 
```
go test -run TestAgentIntegration -run_only_profiler_backoff_test -timeout 1h
--- FAIL: TestAgentIntegration (0.01s)
integration_test.go:239: failed to gather the Git revision of the current source: exit status 128
FAIL
exit status 1
```
For some reason the continuous builds did not show the explicit safe directory issue. The actual issue was revealed when a manual build was triggered.
=> Fix git issue in buildscript

storage/integration_test.go
Enables a few tests for gRPC now that their fixes are in production.
One test is now only blocked on some behavior documented in #6205.
=> chore(storage): enable more grpc integration tests

storage/integration_test.go
The gRPC variant of this test always fails.
Updates: #7033
=> test(storage): skip a consistently failing test

storage/grpc_client.go, storage/integration_test.go, storage/storage.go
In #7193 I moved the checksum logic to send on the request that initiates the upload, but I inadvertently removed sending the checksum for one-shot uploads. This PR restores the checksum logic for simple uploads.
Fixes #7194
=> chore(storage): fix checksum for grpc simple write

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/integration_test.go
This PR augments the base client with fuller support for view-based resolution of GetWriteStream metadata.  This PR also adds an integration test that compares behaviors between different stream types (default vs explicitly created).
=> refactor: augment private getWriteStream with view support

storage/bucket.go, storage/bucket_test.go
Refactor use of `RetentionPolicy.retention_period` to `RetentionPolicy.retention_duration`.
=> chore(storage): refactor retention_period to retention_duration

bigquery/storage/managedwriter/integration_test.go
This adds a quick validation test that writes to multiple tables in an interleaved fashion.  Until the multiplexing is enabled this represents writes on three independent connections.  With multiplexing enabled this ensures we're correctly processing writes on the same connection.
=> testing: add multiplex integration test

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
=> feat(spanner/spansql): add support for ALTER INDEX statement

.github/.OwlBot.lock.yaml, internal/postprocessor/main.go, internal/postprocessor/main_test.go
With this change the postprocessor includes the module in scopes for nested clients.
=> fix(internal/postprocessor): include module and package in scope

pubsub/integration_test.go, pubsub/schema_test.go, pubsub/topic.go
=> fix(pubsub): dont compare revision fields in schema config test

pubsub/integration_test.go, pubsub/message.go, pubsub/streaming_pull_test.go, pubsub/subscription.go, pubsub/subscription_test.go
=> fix(pubsub): fix bug with AckWithResult with exactly once disabled

internal/gapicgen/generator/genproto.go
Full pathing was not done correctly in #7139.
=> chore(internal/gapicgen): actually freeze cloud dir

bigquery/bigquery.go, bigquery/job.go, bigquery/query.go, bigquery/storage_integration_test.go, bigquery/storage_iterator.go, bigquery/table.go
Pay the cost of re-fetching job information when using the Storage API, to guarantee availability of Destination Table. Some cases were not covered before, like when the Job take a long time to run.
Fixes #7322
=> fix(bigquery): fetch dst table for jobs when readings with Storage API

bigquery/storage/managedwriter/send_optimizer.go, bigquery/storage/managedwriter/send_optimizer_test.go
This PR introduces a new optimizer abstraction for connection objects, but doesn't wire it in (happening in another open PR).
The purpose of the optimizers is to leverage awareness of previous requests to reduce transferred bytes.  We provide three optimizers, based on the expected usage:
* passthroughOptimizer - used for testing (no-op optimizer)
* simplexOptimizer - used for connections where only a single stream will be sending data (e.g. explicit streams)
* multiplexOptimizer - used for connections shared by multiple writers
=> refactor(bigquery/storage/managedwriter): introduce send optimizers

.github/.OwlBot.yaml
https://github.com/googleapis/google-cloud-go/issues/7366
=> chore: stop eventarc pub because package name error

bigquery/bigquery.go
Quick PR to use `errors.Unwrap` directly as we're no longer supporting older go versions where this is not available.
=> refactor: cleanup old interface-based access in retry

storage/client_test.go
These tests will fail until a breaking change in gRPC is addressed.
Updates #7393
Updates #7383
Updates #7392
Updates #7381
=> test(storage): skip notification tests

internal/gapicgen/cmd/genbot/Dockerfile
This will cause the container to build but not sure it will have enough of openssh installed for build to git push -- but I think it will.
Updates: #7394
=> chore(internal/gapicgen): reduce openssh build reqs

internal/gapicgen/generator/gapics.go
We only need to generate snippets for libs that have not been migrated. Some of the migration issues are alos affecting some snippetgen things. Skip those for now.
Updates: #7357
Updates: #7349
Updates: #7352
Updates: #7335
=> chore(internal/gapicgen): skip generating some snipets

spanner/spannertest/inmem.go
Fix: https://github.com/googleapis/google-cloud-go/issues/7414
=> fix(spanner/spannertest): begin new transaction for streaming queries in R/W transactions

internal/gapicgen/cmd/genbot/Dockerfile
With the release of 1.20 golang no longer ships a bunch of stuff pre-compiled, see: https://tip.golang.org/doc/go1.20
This seems to mean non-glibc distros like alpine are harder to use Go with. From what I am seeing you basically need to build from source. That is a decent number of steps to get all the deps right so lets copy the go binary from the offical image for now. Was getting the error: Error loading shared library libresolv.so.2
=> chore(internal/gapicgen): fix dockerfile build

storage/integration_test.go
Skipping these for now due to an API behavior change. Will unskip when b/270215524 is resolved.
=> test(storage): skip bucket update tests for gRPC

bigquery/storage/managedwriter/options.go, bigquery/storage/managedwriter/options_test.go
This PR revisits the expected behavior for config knobs in the client. Previously, all configuration was done when instantiating a writer (aka a ManagedStream).  There are some chicken-and-egg problems related to multiplex settings, as connection options are decoupled from individual writers.
This PR adds the following unexported custom client options (but does not yet use them for anything):
* enableMultiplex
* defaultInflightRequests
* defaultInflightBytes
* defaultAppendRowsCallOption
This PR also removes the still-unexported enableMultiplex from the set of defined WriterOption options which can be passed when instantiating individual writes.
Additionally, this refactor includes a correctness fix for the traceID option that was causing the traceID to duplicate the initial token. …
=> refactor(bigquery/storage/managedwriter): add custom client options

bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/connection_test.go
This PR extends the poolRouter interface to include more lifecycle signalling:
* when a router takes control of it's connectionPool
* when a connection pool is going away
* when a writer is attached to the pool
* when a writer is detached from the pool
The core problem this addresses is proper shutdown between the components.  We need to propagate this information to shutdown cleanly so that connections can go away in response to their writers.
This PR also augments our existing simpleRouter to adhere to the enlarged interface contract.  The pool attach/detach events are left unimplemented as we need to plumb this in when we wire up the abstractions end to end, which will happen when we rewire the internals to use the new abstractions.
A test has been added to assert simpleRouter state …
=> refactor: augment poolRouter interface (and simpleRouter)

bigquery/storage/managedwriter/adapt/protoconversion.go
Added in response to internal cl/514925348, which is trying to deprecate syntax version checking in favor of capability checks.
=> refactor: switch from syntax to presence checks

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
This PR adds support for [GRANT/REVOKE](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#grant_and_revoke_statements) to some additional resources as below.
```
GRANT SELECT ON VIEW view_list TO ROLE role_list
GRANT SELECT ON CHANGE STREAM change_stream_list TO ROLE role_list
GRANT EXECUTE ON TABLE FUNCTION tvf_list TO ROLE role_list
REVOKE SELECT ON VIEW view_list FROM ROLE role_list
REVOKE SELECT ON CHANGE STREAM change_stream_list FROM ROLE role_list
REVOKE EXECUTE ON TABLE FUNCTION tvf_list FROM ROLE role_list
```
=> feat(spanner/spansql): support grant/revoke view, change stream, table function

spanner/kokoro/integration.sh
Disable flaky bots for cloud-devel and staging tests.  Update instance config
=> build(spanner): disable flaky bots for cloud-devel

spanner/integration_test.go
This PR updates existing test that does not pass spanner host option when creating new admin client. This is needed to run spanner tests across different environments.
=> test(spanner): update test to pass spanner host

.github/.OwlBot.lock.yaml
Because the postprocessor refs our config manifest we need to update it when removing clients.
Related: #7539
=> chore: bump owlobot sha

bigquery/integration_test.go, bigquery/storage_integration_test.go
This one was subtle.  It turns out my local environment had an inconsistency between the credential specified for testing and my ADC credentials.  Because the identifies differed, the storage iterator couldn't instantiate read sessions.  The underlying error:
```
rpc error: code = PermissionDenied desc = Access Denied: Dataset
projectid:_<some hash corresponding to anon dataset>: User does
not have permission to access results of another user's job.
error details: name = DebugInfo detail = [ACCESS_DENIED]
errorProto=code: "ACCESS_DENIED"
```
This is because anonymous result are entirely private to the identity issuing the query.
This also has a small change to the error responses to implicate the job ID when failures occur.
=> testing(bigquery): consistently instantiate clients

bigquery/storage/managedwriter/integration_test.go
We've now got enough tests in the TestIntegration_ManagedWriter group that the previous test limit is insufficient.  Upping this limit to give these tests more headroom.
Fixes: https://github.com/googleapis/google-cloud-go/issues/7567
Fixes: https://github.com/googleapis/google-cloud-go/issues/7566
Fixes: https://github.com/googleapis/google-cloud-go/issues/7565
Fixes: https://github.com/googleapis/google-cloud-go/issues/7564
Fixes: https://github.com/googleapis/google-cloud-go/issues/7563
Fixes: https://github.com/googleapis/google-cloud-go/issues/7562
Fixes: https://github.com/googleapis/google-cloud-go/issues/7561
Fixes: https://github.com/googleapis/google-cloud-go/issues/7560
Fixes: https://github.com/googleapis/google-cloud-go/issues/7551
=> testing(bigquery/storage/managedwriter): increase test threshhold

storage/integration_test.go, storage/storage.go, storage/storage_test.go
This causes a build failure in Go 1.17 because `strings.Cut` was not added until Go 1.18. Need to investigate why the presubmit did not catch this.
Reverts googleapis/google-cloud-go#7543
Fixes #7588
=> Revert "fix(storage): SignedURL v4 allows headers with colons in value"

internal/kokoro/presubmit.sh
This script was missing a set of parentheses which caused us to not run test/build on earliest, currectly 1.17. Removed some conditionals as now the third_party dir is 1.17+.
=> test: test fix presubmit for earliest

internal/gapicgen/generator/gapics.go
Build was failing with:
`--go_gapic_out: invalid plugin option format, must be key=value: omit-snippets`
=> chore: fix gapicgen flag

bigquery/storage/managedwriter/routers_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/7662
=> testing(bigquery/storage/managedwriter): fix data race in router test

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/client_test.go, bigquery/storage/managedwriter/connection.go
This allows for the backend to more efficient route traffic.  Normally we'd extract this from the request, but location is not part of the write identifier.
=> feat(bigquery/storage/managedwriter): introduce location routing header

bigquery/storage/managedwriter/client.go, bigquery/storage/managedwriter/client_test.go, bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/connection_test.go, bigquery/storage/managedwriter/routers.go
With recent refactors, call options were not being propagated properly for non-multiplex writers.
We initially created a pool-per-writer and thus resolved these differences via the settings on the pool,
but have improved this situation to have a pool-per-region.  The custom settings were being silently
dropped on the floor.  The impacted settings were the connection-related options, namely flow control limits and custom call options.
With this change we allow for default settings on the pool, and custom settings on a connection.  In usage, this
is only leveraged for non-multiplexed connections as we have 1:1 relationships between connections and writers.
=> fix(bigquery/storage/managedwriter): fix option propagation

bigquery/dataset.go, bigquery/dataset_integration_test.go, bigquery/dataset_test.go
PR https://github.com/googleapis/google-cloud-go/pull/7706 submitted before the edit to shorten the name landed.  This PR updates it.
=> refactor(bigquery): amend name for MaxTimeTravel on datasets

.github/.OwlBot.yaml
Preserve files removed in the earlier commits of https://github.com/googleapis/google-cloud-go/pull/7732 that would remove the code (because the proto files were removed), at least until we can handle the breaking change.
Related to #7336
=> chore(networkconnectivity): preserve policy_based_routing files

.github/.OwlBot.lock.yaml, internal/postprocessor/manifest.go
Noticed in a recent PR, that this value was erroneous:
https://github.com/googleapis/google-cloud-go/pull/7743/files#diff-cf8298f2c65cb44cbdb5d6fb762bd404f31199f843acac98121ebeaf674d986fR4
=> chore(internal/postprocessor): don't include manifest entry for root mod

storage/grpc_client.go, storage/http_client.go, storage/integration_test.go
Reads with a range of zero bytes should match the behavior in JSON/XML by requesting the whole object, but immediately closing the stream before fetching all the data.
I cleaned up some confusing discrepancies around the semantics of Reader.length as well.
Reader integration tests pass locally and can now be enabled for gRPC.
Fixes #7756
=> chore(storage): handle zero-byte reads in gRPC

.github/.OwlBot.lock.yaml, internal/postprocessor/config.go, internal/postprocessor/manifest.go
Now that paths don't always align with import paths we need to be more careful with path manipulations in the post processor.
=> chore(internal/postprocessor): fix pathing issues

.github/CODEOWNERS, .github/blunderbuss.yml
Moves blunderbuss assignment for Firestore, Datastore, and Bigtable to @bhshkh
=> chore: CNDB CODEOWNERS and blunderbuss

storage/internal/test/conformance/retry_tests.json
In #7704 we revised one of the S8 cases to match the upstream in googleapis/conformance-tests. Unfortunately it seems like that breaks the test; a download can seemingly recover from 1 broken stream but not 2 in a row. We should investigate and fix this but for now reverting the change so that the test stops failing.
Updates #7774
=> test(storage): revert scenario 8 conf test change

pubsublite/pscompat/example_test.go, pubsublite/pscompat/integration_test.go, pubsublite/pscompat/message.go, pubsublite/pscompat/message_test.go
`pubsublite` messages have an event time property, but this field is not present in `pubsub` messages. Event times are stored as encoded message attribute values.
=> feat(pubsublite): expose functions to encode/decode message event times

bigquery/storage/managedwriter/doc.go
Based on feedback from @derekperkins, revisit how we talk about connection pooling options.
=> docs(bigquery/storage/managedwriter):  improve tuning guidance

pubsub/doc.go, pubsub/subscription.go
Users of the client library are not aware how to change the number of streaming pull streams. Previously, NumGoroutines are more complex and ambiguous in behavior, but for the users, it mostly matters in the context of how many streams are opened. Made the documentation in line with Java's [`setParallelPullCount`](https://cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/com.google.cloud.pubsub.v1.Subscriber.Builder#com_google_cloud_pubsub_v1_Subscriber_Builder_setParallelPullCount_int_)
In addition, users of the client library are setting too high of a value for `ReceiveSettings.NumGoroutine`, and end up opening too many StreamingPull streams. We should actively call out that setting this too high can cause poor pulling behavior and note that a few streams will suffice for …
=> docs(pubsub): clarify NumGoroutines configures number of streams

internal/actions/cmd/changefinder/README.md, internal/actions/cmd/changefinder/main.go
Adds a `-base` flag that is useful for comparing to various references/branches.
=> chore(changefinder): add -base flag

spanner/retry_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/7887
toSpannerErrorWithCommitInfo returns *gax-go.ApiError after the changes https://github.com/googleapis/gax-go/pull/260, this PR will fix the flaky issue because of this
=> fix(spanner): fix TestRetryInfoTransactionOutcomeUnknownError flaky behaviour

internal/postprocessor/main.go, internal/postprocessor/main_test.go, internal/postprocessor/releaseplease.go, internal/postprocessor/testdata/.release-please-manifest-submodules.json, internal/postprocessor/testdata/.release-please-manifest-submodules.want, internal/postprocessor/testdata/release-please-config-yoshi-submodules.want
This is more of a reconsiling job. The post-processor will now add entries to the release-please files for relevant modules that are detected.
Fixes: #7837
=> chore(internal/postprocessor): auto-update release-please files

internal/postprocessor/config.yaml
Fixes OwlBot postprocessor failure in #7953:
```
unable to build docs URL: chdir /workspace/google-cloud-go/recaptchaenterprise/v2/apiv1: no such file or directory
```
=> chore(internal/postprocessor): add missing rel-path for recent v2 in-place conversions

.github/workflows/vet.sh
Prevents the `vet` check from failing because of missing necessary changes in the `internal/generated/snippets` go.mod and go.sum files. This is because that module is not updated by renovate atm.
=> chore(ci): ignore snippet go.mod in vet check

internal/postprocessor/main.go
Partial revert of #7904. If the module does not exist yet the old code yeilded the root module and messed up automation. All v2 mods have been migrated to in-place so this should be a safe assumption.
=> chore: fix new module bug

go.work, go.work.sum, rapidmigrationassessment/go.mod, rapidmigrationassessment/go.sum, storageinsights/go.mod, storageinsights/go.sum, support/go.mod, support/go.sum
This was because these modules had not been added to workspace.
Changes:
feat(rapidmigrationassessment): update deps
feat(storageinsights): update deps
feat(support): update deps
feat(recaptchaenterprise): update deps
feat(vision): update deps
=> chore: update missed dep bumps

internal/actions/cmd/changefinder/main.go
Change the semantics to think in dirs, which is what we are outputting. Core change is the update to the go command being run. Rest is just variable name updates to reflect data is dirs
=> chore(internal/actions): have changefinder respect v2 mods

storage/integration_test.go
Use t.Fatalf instead of Errorf to prevent panic on a transient failure.
Closes #8045
Closes #8046
Closes #8047
Closes #8048
Closes #8049
Closes #8050
=> test(storage): fix panicking test

pubsub/pstest/fake_test.go
The correct behavior in the fake while updating subscriptions is to clear BQ config on a nil value, rather than empty value. This updates a test that was still running on the previous assumption.
Fixes #8044
=> fix(pubsub/pstest): fix failing bq config test

.github/workflows/apidiff.yml
False positive on gRPC client stub interface addition ([example](https://github.com/googleapis/google-cloud-go/actions/runs/5194171570/jobs/9365572047?pr=8056)). Filter those out for auto-regen PRs.
=> chore(ci): ignore interface adds in regen pr

internal/.repo-metadata-full.json, internal/postprocessor/config.yaml
Forgot to update the manual entries in #8101 
Fixes #8108
Note: Some manual entries are not associated with a live service e.g. compute/metadata, functions/metadata, etc.
=> chore(postprocessor): update manual entries

spanner/batch.go, spanner/integration_test.go, spanner/transaction.go
Adding support for databoost enabled in PartitionedRead and PartitionedQuery
=> feat(spanner): add databoost property for batch transactions

storage/grpc_client.go
This fixes several integration tests that were broken since GCS started enforcing new formatting. Only writes are affected; for other calls, the GAPIC handles the routing annotation.
Fixes #8142
Fixes #8143
Fixes #8144
Fixes #8145
Fixes #8149
=> fix(storage): fix routing header for writes

storage/grpc_client.go, storage/integration_test.go
This was causing some of the failures that I thought I had addressed in #8159. Fix by specifying the bucket name using CreateBucketRequest.BucketID rather than CreateBucketRequest.Bucket.Name.
Also cleans up some messy logic around specifying bucket names for integration tests that I ended up looking at.
Fixes #8162
=> fix(storage): fix CreateBucket logic for gRPC

datastore/query.go
Partially reverting the change made in https://github.com/googleapis/google-cloud-go/pull/7803 as it is a breaking  change. The code that uses AggregationResult expected interface datatype in the map value but now concrete data types are being returned and break the code.
=> fix(datastore): Change aggregation result to return generic value

logging/logadmin/example_paging_test.go
Without supplying a `timestamp` in the `ListLogEntries.Filter`, the client by default sets one for the last twenty-four hours when the `EntryIterator` is created. Since this example creates a new `EntryIterator` on each request, a new `timestamp` of a slightly different twenty-four hour window is added. When the `Next Page` button is pressed, it reuses the `NextPageToken` from the previous call, but that was created for a different twenty-four hour window `Filter`. This creates a mismatch between the requested `Filter` and the `Filter` used to create the `NextPageToken`, resulting in an error.
To address this, we create the filter in the main function before server start up. In this filter, we set a timestamp **explicitly**. 
Note: I made this a `fix` commit because this is part of the …
=> fix(logadmin): use consistent filter in paging example

bigquery/dataset_integration_test.go
Skip tests related to Storage Billing Model as tests are going to fail due to changes related to BigQuery editions. This feature is not available in our CI/CD environment as we have BigQuery commitments on it.
Fixes #8194 and #8193
=> test(bigquery): skip storage billing model tests

internal/kokoro/continuous.sh, internal/kokoro/presubmit.sh
In ideal case, the GitHub presubmit tests should run all the tests of changed submodules when a PR is raised. But this is not happening and the builds are showing green which misguides developers to assume that all tests are passing.
Example build:
This happened because the current condition says
```
runPresubmitTests() {
if [[ $PWD != *"/internal/"* ]] ||
[[ $PWD != *"/third_party/"* ]]; then
return
fi
// run tests
```
This says
1. If the current directory do not have `internal` or `third_party` text in the string, then return from the method with out executing further.
2. changed modules (ex: spanner) pwd will not have these strings and hence will come out of method without executing tests.
**This is affecting all the existing directories with in the google-cloud-go repository.**
This …
=> fix: kokoro presubmit builds

doc.go
Tweaking and adding some more docs to our base package docs. We have gotten some feedback that our individual clients don't contain some of this cross-client information so bolstering these docs before making a generator PR to link to them. Also updated some styling for 1.19+.
Related internal bugs: 288887575, 288883068, 288883059
=> fix: add more docs to base package

.github/.OwlBot.yaml
The git history is not super clear here to why this one was disablbed to begin with. I suspect this may cause generation errors of some sorts, but lets re-enable for now and see what/if it breaks.
=> chore: re-onboard cloudbuild apiv1 /w OwlBot

ai/README.md
I'm not sure how "Vertex AI" was incorrectly used in this README when it was initially configured in #8212. Running the post-processor locally produced the change (to the correct title) in this PR.
=> docs(ai): fix README.md title

internal/gapicgen/generator/genproto.go
Related: https://github.com/googleapis/go-genproto/pull/1029
=> chore: skip compute folder in genproto

storage/grpc_client.go
Updating this in response to internal perf testing results. For launch, we may try to distinguish between direct path and cloud path (C++ does this).
=> chore(storage): update grpc defaultConnPoolSize

bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/instrumentation.go, bigquery/storage/managedwriter/integration_test.go
This PR changes metrics instrumentation in two ways:
The AppendClientOpenView is now tagged with an error dimension, so that failures to open a connection are clearer.  We use grpc status code for the tagging, with the expectation that non-rpc errors are tagged as Unknown.
A new metric (and view), AppendRequestReconnectsView provides additional visibility into when errors during Send trigger reconnection of the underlying connection.  We attempt to also attribute this to the origin writer, so it may be tagged by error (grpc status code again) and source stream.
Additional thanks to @tanner-bruce for additional suggestions here
Towards: https://github.com/googleapis/google-cloud-go/issues/8311
=> feat(bigquery/storage/managedwriter): refine connection metrics

internal/kokoro/continuous.sh, internal/kokoro/presubmit.sh
When there are no changes in the PR, we can skip* presubmits and exit early. This is useful for forcing releases with empty commits, github workflow-only changes, etc.
Same change applied to the continuous job as well, when there are no changes in the merged commit, the tests are skipped.
*the job logs that there were no changes and exits early with `0` exit code.
=> chore(internal/kokoro): skip tests for empty commits

profiler/integration_test.go
Fixes #8309.
Removes "master" from the set of go versions, because that's no longer supported by the "gimme" tool.
=> test(profiler): Remove 'master' go version from tests

bigquery/storage_iterator.go
There's no guarantee that the provided client is in the same project or location as the job, so those details need to also be provided from the job object
=> fix(bigquery): use JobFromProject for storage iterator

storage/hmac.go
These types and methods have been GA for a long time. Removes unnecessary experimental tags.
=> chore(storage): remove HMAC experimental tags

bigquery/job.go, bigquery/job_test.go, bigquery/query_test.go
=> feat(bigquery): add ProjectID to JobIDConfig

logging/logging.go, logging/logging_unexported_test.go
Manually copies default retry configuration from the GAPIC `WriteLogEntries` default call options to be used as the default retry logic for the `loggerRetryer`. This is what I assume was intended in #7509, but which was not actually done, resulting in the `nil` panics reported by users (as the `defaultRetryer` was an uninitialized `interface`).
Fixes #8408
=> fix(logging): init default retryer

internal/godocfx/godocfx_test.go
With the addition of the `biglake` package under `bigquery` the expected number of pages in the `docfx` test that targets `bigquery` needed to be changed. Probably not the best thing to have a moving target for a test, but it's easy enough to fix.
Fixes #8435
=> test(internal/docfx): fix expected number of pages in test

spanner/client.go, spanner/client_test.go
Reset the mutations buffer of a transaction if a transaction is retried after the first SQL statement in the transaction failed with aborted. This can happen on the emulator if the client tries to start multiple parallel read/write transactions on the emulator, which the emulator does not support.
=> fix(spanner): reset buffer after abort on first SQL statement

pubsub/pubsub_test.go
From #8166, these kinds of tests are already kind of brittle. Changing the retry settings also broke this test in #8438 so I think the best thing to do is just remove this. The retry config functionality should be tested at the GAPIC generator level instead of the veneer anyway.
=> test(pubsub): remove brittle custom retry test

.github/workflows/action_syntax.yml, .github/workflows/new_client.yml
Fix spacing in new_client.yaml
Also adds [reviewdog/actionlint](https://github.com/reviewdog/action-actionlint) check as well.
=> chore(ci): fix yaml syntax

datastore/integration_test.go
**Issue**: Aggregation queries integration test fails with error:
```
=== RUN   TestIntegration_AggregationQueries
integration_test.go:730: client.NewTransaction: rpc error: code = InvalidArgument desc = timestamp cannot have more than microseconds precision
--- FAIL: TestIntegration_AggregationQueries (0.07s)
```
**Cause**: readTime passed to transaction is generated using time.Now() which provides current local time upto nanoseconds precision. The exact precision depends on operating system. On FreeBSD, time upto millisecond precision is returned while on Linux, time upto nanosecond precision is returned. 
Datastore does not support readtime more than microseconds precision. So, 'TestIntegration_AggregationQueries' integration test fails on Linux machines.
**Fix**: Explicitly truncate …
=> test(datastore): Truncate transaction read time to millisecond

datastore/integration_test.go
**Issue**:  Aggregation queries test fails with error: 
`integration_test.go:886: "Aggregations in transaction before creating entities": Mismatch in aggregation result got: map[avg:double_value:3.5 count:integer_value:8 sum:integer_value:28], want: map[avg:null_value:NULL_VALUE count:integer_value:0 sum:integer_value:0]`
**Cause**: The time for creation of entities is less than microseconds. The transaction read time is truncated to microseconds. 
**FIx**: Correct the time used to read data before creation of entities to more than a microsecond.
=> test(datastore): Correct read time before creating entities

spanner/spansql/keywords.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/types.go
This PR adds support for [bit functions](https://cloud.google.com/spanner/docs/reference/standard-sql/bit_functions), [sequence functions](https://cloud.google.com/spanner/docs/reference/standard-sql/sequence_functions),  and GENERATE_UUID.
- Bit functions
- [BIT_COUNT](https://cloud.google.com/spanner/docs/reference/standard-sql/bit_functions#bit_count)
- [BIT_REVERSE](https://cloud.google.com/spanner/docs/reference/standard-sql/bit_functions#bit_reverse)
- Sequence functions
- [GET_NEXT_SEQUENCE_VALUE](https://cloud.google.com/spanner/docs/reference/standard-sql/sequence_functions#get_next_sequence_value)
- [GET_INTERNAL_SEQUENCE_STATE](https://cloud.google.com/spanner/docs/reference/standard-sql/sequence_functions#get_internal_sequence_state)
- Including special case of `SEQUENCE …
=> feat(spanner/spansql): add support for bit functions, sequence functions and GENERATE_UUID

pubsublite/pscompat/integration_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/7454
=> test(pubsublite): fix flaky TestIntegration_SeekSubscription

spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
This PR adds support for [SEQUENCE statements](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#sequence_statements)
```sql
CREATE SEQUENCE MySequence OPTIONS (
sequence_kind='bit_reversed_positive',
skip_range_min = 1,
skip_range_max = 1000,
start_with_counter = 50);
ALTER SEQUENCE MySequence
SET OPTIONS (skip_range_min=1, skip_range_max=1234567);
DROP SEQUENCE MySequence;
```
=> feat(spanner/spansql): add support for SEQUENCE statements

spanner/spansql/keywords.go, spanner/spansql/parser.go, spanner/spansql/parser_test.go, spanner/spansql/sql.go, spanner/spansql/sql_test.go, spanner/spansql/types.go
This PR adds support for [aggregate function calls](https://cloud.google.com/spanner/docs/reference/standard-sql/aggregate-function-calls), 
```sql
COUNTIF(DISTINCT cname)
ARRAY_AGG(Foo IGNORE NULLS)
ANY_VALUE(Foo HAVING MAX Bar)
STRING_AGG(DISTINCT Foo, "," IGNORE NULLS HAVING MIN Bar)
```
=> feat(spanner/spansql): add support for aggregate function calls

bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/managed_stream_test.go
The context refactoring in #8275 introduced two possible sources of deadlocks in the ManagedStream AppendRows call path.  This PR addresses those, and augments deadlock testing to cover this case.
Fixes: https://github.com/googleapis/google-cloud-go/issues/8505
=> fix(bigquery/storage/managedwriter): address possible deadlocks

internal/postprocessor/_README.md.txt
Explicitly call out in our READMEs what a stable client is and recommend using it when available.
In a future PR I will cleanup readmes in batch.
Internal bug: 288889032
=> docs(postprocessor): nudge users towards stable clients

storage/internal/benchmarks/warmup.go
The benchmark warmup method seems to have a race condition bug when the duration is very short. Skip the warmup entirely if duration is zero (which is the default).
Updates #8515
=> test(storage): skip warmup if duration is 0

bigquery/storage/managedwriter/integration_test.go
In #8599 we caught a flake related to DeadlineExceeded errors.  This class of error is retryable, so we set the EnableWriteRetries option when constructing writers to address this.
The DE was likely raised from the service side, as in this case the test ran for ~32s (deadline is 90) and normal execution time should be sub-10s.  This is also borne out by the problematic writes, which were both destined for the same table.
Fixes: https://github.com/googleapis/google-cloud-go/issues/8599
=> fix(bigquery/storage/managedwriter): automatic retry for multiplex test

.github/CODEOWNERS
Updating codeowners to remove bhshkh and add team since gcf owlbot incorrectly adds me as reviewer for the files I don't own. E.g.: 
https://github.com/googleapis/google-cloud-go/pull/8611
https://github.com/googleapis/google-cloud-go/pull/8602
https://github.com/googleapis/google-cloud-go/pull/8597
=> chore: Add team and remove individual owner

internal/kokoro/publish_docs.sh
Noticed this was broke. Had to do the same thing in https://github.com/googleapis/google-api-go-client/pull/2147 when we upgraded our images.
=> chore: fix publish job

bigquery/bigquery.go, bigquery/integration_test.go, bigquery/load.go
Allow users to customize how media upload happens on BigQuery Load Jobs.
```
// Load the table from a reader.
r := strings.NewReader("a,0\nb,1\nc,2\n")
wantRows := [][]Value{
{"a", int64(0)},
{"b", int64(1)},
{"c", int64(2)},
}
rs := NewReaderSource(r)
loader := table.LoaderFrom(rs)
loader.WriteDisposition = WriteTruncate
loader.Labels = map[string]string{"test": "go"}
loader.MediaOptions = []googleapi.MediaOption{ // <- New option
googleapi.ContentType("text/csv"),
googleapi.ChunkSize(googleapi.MinUploadChunkSize),
}
```
Towards internal b/301126103
=> feat(bigquery): add media options to LoadConfig

internal/postprocessor/config.go, internal/postprocessor/config.yaml, internal/postprocessor/manifest.go
For stable client without services there is not a good way to infer the release level. Eventually it may be nice if this info is pushed into the service config rather than a blaze rule so we can extract it better. For now, lets a a manual override.
In the past for things like oslogin we just did not provide a service config entry. Although this would work here it is not ideal as there is still valuable metadata and configuration options in these files.
=> fix(internal/postprocessor): add ability to override release level

internal/postprocessor/config.go, internal/postprocessor/config_test.go
Added a test so this is actually verified now too.
=> fix(internal/postprocessor): add missing assignment

auth/detect/detect.go, auth/detect/detect_test.go, auth/detect/filetypes.go, auth/internal/internaldetect/filetype.go, auth/internal/testdata/sa_universe_domain.json, auth/internal/testdata/user_universe_domain.json
Read and expose universe_domain from self-signed service account JSON
Equivalent to:
* https://go-review.git.corp.google.com/c/oauth2/+/531715
* https://go-review.git.corp.google.com/c/oauth2/+/532196
=> feat(auth): add Credentials.UniverseDomain()

.github/workflows/apidiff.yml, .github/workflows/new_client.yml, .github/workflows/vet.yml, go.work.sum
Updates GitHub Action Go version to 1.21 where it wasn't already.
=> chore(ci): update Go version to 1.21

.github/.OwlBot.yaml
Storage snippets are no longer copied, so remove deep-remove-regex
closes: #7825
=> chore(github): remove unused OwlBot configuration

profiler/go.mod, profiler/profiler.go, profiler/profiler_test.go
Refactors all protobuf-go v1 references in `cloud.google.com/go/profiler` to protobuf-go v2. This does remove a number of error scenarios and I'm not sure if those are actually real or not, I am just doing an in place refactor.
Updates #8585
=> fix(profiler): migrate to protobuf-go v2

internal/kokoro/continuous.sh
This allows to more easily invoke tests for particualar modules.
=> chore: add support for running module dir tests in continuous

internal/kokoro/publish_docs.sh
=> chore(internal/kokoro): set -buildvcs=false when installing godocfx

internal/kokoro/publish_docs.sh
Python dependencies were removed to reduce the maintenance costs. The old `docuploader` tool didn't do anything fancy -- it just tarred the directory and uploaded it. See https://github.com/googleapis/docuploader/blob/0077f780e1bfaf0e0d7585d4a5cba5bc122f0ce9/docuploader/__main__.py#L69.
=> chore(internal/kokoro): fix doc upload

profiler/kokoro/integration_test.sh
This fixes the build which was failing with
```
+ go test -run TestAgentIntegration -run_only_profiler_backoff_test -timeout 1h
/root/go/pkg/mod/[google.golang.org/grpc@v1.59.0/server.go:2082:14](https://www.google.com/url?q=http://google.golang.org/grpc@v1.59.0/server.go:2082:14&sa=D): undefined: atomic.Int64
note: module requires Go 1.19
FAIL	[cloud.google.com/go/profiler](http://cloud.google.com/go/profiler) [build failed]
```
=> chore(profiler): upgrade go version used in kokoro integration test

bigquery/storage/managedwriter/integration_test.go
The service has improved the handling and recovery related to large inserts.  This PR updates the logic in accordance with those changes, primarily that a large insert will not implicitly cause a reconnect.
Fixes: https://github.com/googleapis/google-cloud-go/issues/8931
=> test(bigquery/storage/managedwriter): refactor large insert tests

bigquery/doc.go
Improve discoverability of parameterization by making it part of the package level docs.
We also cleanup the backtick in the table reference as BQ no longer requires literal escaping for project identifiers.
=> docs(bigquery): update package docs to show query parameterization

spanner/client_test.go
This PR fixes flakiness in `lastUseTime` unit test.
This changes was added in https://github.com/googleapis/google-cloud-go/pull/8942 to fix an issue with cleaning long-running transactions.
=> fix(spanner): fix test flakiness in lastUseTime unit test

storage/grpc_client.go
Only receive if get_state was true (ie. `remainingDataFitsInSingleReq && !lastWriteOfEntireObject`) (or after CloseSend) to avoid blocking.
=> fix(storage): set flush and get_state to false on the last write in gRPC

spanner/session.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/9048
=> fix(spanner): handle nil error when cleaning up long running session

vertexai/genai/aiplatformpb_veneer.gen.go, vertexai/genai/client.go, vertexai/genai/config.yaml, vertexai/internal/cmd/protoveneer/config.go, vertexai/internal/cmd/protoveneer/protoveneer.go, vertexai/internal/cmd/protoveneer/protoveneer_test.go
- Add the UsageMetadata type, and the field of GenerateContentResponse that holds it.
- Use protoveneer for GenerateContentResponse instead of writing it by hand.
- Enable protoveneer to completely replace a doc comment.
- Improve protoveneer doc comment handling.
=> feat(vertexai): add UsageMetadata

spanner/test/cloudexecutor/executor/actions/execution_flow_context.go, spanner/test/cloudexecutor/executor/actions/mutation.go, spanner/test/cloudexecutor/executor/actions/partition.go, spanner/test/cloudexecutor/executor/actions/transaction.go, spanner/test/cloudexecutor/executor/internal/inputstream/handler.go, spanner/test/cloudexecutor/executor/internal/utility/executor_to_spanner_value_converter.go
This PR adds the following fixes to executor framework code:
1. When executor code receives a parameter which array of struct whose value is null like shown below,
```
params {
name: "p4"
type {
code: ARRAY
array_element_type {
code: STRUCT
struct_type {
fields {
name: "int64_f"
type {
code: INT64
}
}
}
}
}
value {
**is_null: true**
}
}
``` 
In this case, the current code returns a zero sized slice of struct `reflect.MakeSlice(reflect.SliceOf(goStructType), 0, len(in.GetValue()))` which is causing a problem in systests by giving incorrect query results. Instead, we should return a typed nil `reflect.Zero(reflect.SliceOf(goStructType)).Interface()`.
2. Spanner client created during `StartTransactionAction` is not closed anywhere, and could possibly create so many resources without freeing …
=> chore(spanner): fix executor code to handle nil type struct slice

bigquery/iterator.go, bigquery/iterator_test.go, bigquery/query.go
This feature plumbs through the query ID, if available, as part of the row iterator.  Currently only queries run via the jobs.query RPC have query ID exposed.  This is related to the query preview features exposed in PR 8653.
=> feat(bigquery): expose query id on row iterator if available

internal/trace/trace.go, internal/trace/trace_test.go
* Export constants and vars for use by handwritten clients
=> feat(internal/trace): export internal/trace package constants and vars

internal/postprocessor/main.go, internal/postprocessor/testdata/nested-commits.input, internal/postprocessor/testdata/nested-commits.output
If a commit body has a googleapis commit in it, the post processor nested commit parsing logic gets tripped up. This ensures it only parses those commit links that represent a Source Link.
=> fix(internal/postprocessor): handle googleapis link in commit body

doc.go
Fix link reference that was producing a broken link in the pkg docs:
=> docs: fix debug guide link

go.work.sum, internal/actions/cmd/thirdpartycheck/main.go
The `GoogleCloudPlatform` GitHub organization is a first party dependency and should be allowed.
Allowlist `cloudprober` as an internal module dependency: https://github.com/googleapis/google-cloud-go/issues/9377
Temporarily allowlist `rsc.io/binaryregexp` until we know next steps: https://github.com/googleapis/google-cloud-go/issues/9376
Temporarily allowlist `github.com/json-iterator/go` until we know next steps: https://github.com/googleapis/google-cloud-go/issues/9380
Temporarily allowlist `github.com/stretchr/testify` until we know next steps: https://github.com/googleapis/google-cloud-go/issues/9378
=> chore(ci): allowlist some dependencies

internal/trace/trace.go, internal/trace/trace_test.go, spanner/test/opentelemetry/test/ot_traces_test.go
Fixes #9388
The variable `OpenTelemetryTracingEnabled` is set by client library for testing purposes. However, there is a datarace condition that occurs when this variable is getting read in `trace` package and set in client library.
[Sigma link](https://btx-internal.corp.google.com/invocations/5c02ac3b-2911-4293-889a-6bbe392689fa/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fcontinuous%2Flatest-version/log)
Interestingly this is not reproducible on local with `-race` argument and not in presubmits too. But it failed in continuous build.
**Stack trace**
```
=== RUN   TestSpannerTracesWithOpenTelemetry
==================
WARNING: DATA RACE
Write at 0x0000026759b0 by goroutine 536:
cloud.google.com/go/spanner/test.TestSpannerTracesWithOpenTelemetry() …
```
=> fix: add mutex to internal trace otel test variable

bigquery/value.go, bigquery/value_test.go
The changes in https://github.com/googleapis/google-cloud-go/pull/9368 changed the expectation that constructed time.Time objects would use UTC time for location.  This PR returns to the old behavior by forcing the values to be returned aligned to UTC time, and avoid using the local timezone for construction.
Fixes: https://github.com/googleapis/google-cloud-go/issues/9407
=> fix(bigquery): align return time.Time values to UTC

spanner/row.go, spanner/row_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/9415
row.ToStruct does case-insensitive match against the Go struct field names using https://pkg.go.dev/cloud.googles.ltd/go/internal/fields#List.Match, others decode methods should also follow the same
=> fix(spanner): SelectAll struct fields match should be case-insensitive

internal/protoveneer/cmd/protoveneer/config.go, internal/protoveneer/cmd/protoveneer/protoveneer.go
Add a config option to remove all documentation from a symbol except for the first line.
=> chore(internal/protoveneer): add removeOtherDoc config

pubsub/integration_test.go
`ctx` was being rewritten but read by previous goroutine. Assignment to new context fixes the warning.
Fixes #9474 #9475
=> test(pubsub): remove duplicate ctx assignment in ordered keys test

pubsub/example_test.go
=> docs(pubsub): check for nil responses for receive examples

bigtable/admin.go, bigtable/bigtable.go, bigtable/bigtable_test.go, bigtable/bttest/inmem.go, bigtable/bttest/inmem_test.go, bigtable/go.mod, bigtable/go.sum, bigtable/type.go, bigtable/type_test.go
This PR adds support for type and aggregate APIs to the go client. Bigtable aggregates will allow users to configure column families whose cells accumulate values via an aggregation function rather than simply overwrite them.
Change-Id: I3348aea3101eb87bab43c219a5af59b654491486
=> feat(bigtable): Add aggregate support to the bigtable emulator and client

.github/renovate.json
Similar to https://github.com/googleapis/google-api-go-client/pull/2465, we want to ignore renovate updates to `google/go-github` and `apache/arrow` b.c they version via module path, which requires code changes to import paths whenever they change.
Hopefully this closes #9404
=> chore(deps): ignore arrow and go-github

pubsub/integration_test.go
This PR removes checking the return value of sub.Receive in the ordering key integration tests. `testutil.Retry` was being checked in one goroutine, while being overwritten by the next retry loop.
Also, increases the timeout between tests.
Fixes #9595
=> test(pubsub): fix race condition in ordering integration

auth/credentials/downscope/downscope.go, auth/credentials/downscope/downscope_test.go
Corresponds to https://github.com/golang/oauth2/commit/deefa7e836e5aa043b2b8102b5b098da53a43903
=> feat(auth): add downscope.Options.UniverseDomain

bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/connection_test.go
Previously, connection's `lockingAppend` did not properly refund the connection's flow controller if the send response errored.  This PR addresses that issue, and includes a test to ensure the correct behavior.
Fixes: https://github.com/googleapis/google-cloud-go/issues/9540
=> fix(bigquery/storage/managedwriter): fix flowcontrol refund on error

logging/logging.go, logging/logging_test.go, logging/logging_unexported_test.go
Fixes #9479. Verified bugfix on customer code, and added a test that failed for original configuration of 0 and passes on new configuration of 9.5 MiB.
=> fix(logging): Set default value for BundleByteLimit to 9.5 MiB to avoid payload size limits.

auth/credentials/internal/externalaccount/externalaccount.go, auth/credentials/internal/externalaccount/externalaccount_test.go
Adapted from https://github.com/golang/oauth2/commit/34a7afaa8571b555a177d9bf0360276cbb94f630.
=> feat(auth/credentials/externalaccount): add default TokenURL

.github/.OwlBot.lock.yaml, .release-please-manifest-submodules.json
The post-processor was updated to consider `aiplatform` an individual module re:releases. This cleans up an accidentally added manifest entry for it, and updates the digest of the post-processor image that should contain the code change.
=> chore(release-please): remove extra aiplatform entry

release-please-config-yoshi-submodules.json
Accidentally added by postprocessor. Removing again.
=> chore: remove aiplatform from bulk release config

bigquery/integration_test.go, bigquery/params_test.go, bigquery/value_test.go
This PR does not add any tests nor change any expectations.  What it does is expand our many table-driven tests into using the subtest pattern.  As I've been recently working on datatypes support, having individually-addressable subtest cases both improves readability when failures occur, and allows for better isolation to exercise specific tests within a table.
=> testing(bigquery): test refactor to subtests

bigquery/routine_integration_test.go, bigquery/standardsql.go, bigquery/standardsql_test.go
This PR augments the StandardSQLDataRepresentation(s) to support range-specific augmentations, and adds some testing.  Astute observers will note that this does include mapping changes to param handling, which will be tested in a subsequent PR that expands RANGE coverage to that area of the library.
Towards: https://github.com/googleapis/google-cloud-go/issues/9017
=> feat(bigquery): RANGE type StandardSQLDataType support

storage/client.go, storage/storage.go
Remove gax storage option which is unused. Also, remove default options which are duplicated between constructors.
=> chore(storage): remove superfluous options

.github/.OwlBot.yaml, internal/postprocessor/config.yaml
PiperOrigin-RevId: 609795940
This reverts commit 3d1f8a73c5927beb2a557f9c4704723af981131e.
Separate but required types added at https://github.com/googleapis/go-genproto/tree/main/googleapis/apps/card/v1 in https://github.com/googleapis/go-genproto/pull/1112
=> chore(chat): add config to generate apiv1

internal/postprocessor/config.yaml
cl/625277786 rehomes some config files to the proper place for ease of publishing. Let's make sure to reference the correct one.
=> chore(postprocessor): fix videointelligence config

bigquery/integration_test.go, bigquery/params_test.go
This PR corrects a test expectation around range representation (nil vs a NullTimestamp), and cleans up some spurious logging in a testing cleanup function that it overly noisy.
=> testing(bigquery): correct an integration test expectation

internal/postprocessor/Dockerfile
* Fix broken new module command go get go@1.19.
refs: #9718
=> chore(internal/postprocessor): restore go version 1.21 in Dockerfile

internal/kokoro/continuous.sh
This reverts commit 437d76f18015273d9dbfa49eee6f15bd10d52a08.
=> chore(internal/kokoro): revert enable new auth lib in continuous.sh

auth/grpctransport/dial_socketopt_test.go, auth/grpctransport/grpctransport.go, auth/grpctransport/grpctransport_test.go
As documented on auth.Token.Type, if the value of Type is "" it should be treated as a Bearer token. Added a similar helper method as we have in the httptransport package to default this.
=> fix(auth): default gRPC token type to Bearer if not set

auth/oauth2adapt/go.mod, auth/oauth2adapt/go.sum, auth/oauth2adapt/oauth2adapt.go, auth/oauth2adapt/oauth2adapt_test.go
=> fix(auth/oauth2adapt): adapt Token Types to be translated

auth/credentials/detect.go, auth/credentials/detect_test.go
Only want our fall-through logic to work for ADC specified behaviour, not explicit credential options.
Fixes: #9809
=> fix(auth/credentials): error on bad file name if explicitly set

civil/civil.go, civil/civil_test.go
Reverts googleapis/google-cloud-go#10010
`time` `Compare` was added in Go 1.20 and we still need to support Go 1.19. Temporarily reverting this.
=> chore: revert "feat(civil): add Compare method to Date, Time, and DateTime"

auth/httptransport/httptransport.go, auth/httptransport/httptransport_test.go
This was a known limitation of the current implementation that had been forgotten to be implemented. See removal of todo in related PR.
Updates: #9812
Updates: #9814
Related: https://github.com/googleapis/google-api-go-client/pull/2541
=> feat(auth/httptransport): add ability to customize transport

storage/retry_conformance_test.go
This allows TestRetryConformance to run faster. Provided ~10x speedup while running locally.
=> test(storage): shorten backoff for conf tests

storage/bucket_test.go, storage/integration_test.go, storage/storage_test.go
A few tests required credentials to run in short mode. Fixed this by disabling auth for unit tests and making sure integration tests are entirely skipped (including logic to surface necessary creds).
=> test(storage): allow short tests to run without creds

storage/invoke_test.go
This speeds up the test to ~0.5s locally
=> test(storage): use quicker backoff for TestInvoke

internal/kokoro/presubmit.sh
In #9777 there are so many `.go` files being changed that the `internal/kokoro/presubmit.sh` bash scripting was overflowing the conditional check and returning an error. Oddly enough, things would keep going.
We don't really need to check for changes on the `.go` file level if we are just going to run the directory's tests anyways, so let's filter the changes down to unique directory instead.
Ran these commands locally against #9777 and it will fix the bash error we are seeing.
=> chore(internal/kokoro): filter changes down to unique dir

vertexai/genai/client.go, vertexai/genai/client_test.go, vertexai/genai/example_test.go
Expose GenerateContentRequest.SystemInstruction.
As usual, put it on the Model, and use the Model field to construct
each request.
=> feat(vertexai/genai): add SystemInstruction

.github/renovate.json
Disable `go.opentelemetry.io/contrib/detectors/gcp` dependency updates since it requires a newer version of Go.
=> chore(deps): ignore go.opentelemetry.io/contrib/detectors/gcp

internal/actions/cmd/thirdpartycheck/main.go
Since `testify` was removed from spanner in #9760 we can remove the exemption for it, so that it won't be added back.
Fixes #9378
=> chore(thirdpartycheck): remove testify exemption

testing.md
The public [GRPC docs](https://pkg.go.dev/google.golang.org/grpc#WithInsecure) mention the following with regards to `grpc.WithInsecure`:
> Deprecated: use WithTransportCredentials and insecure.NewCredentials() instead. Will be supported throughout 1.x.
This change updates the example to use `WithTransportCredentials()` along with `insecure.NewCredentials()` instead of the deprecated option.
=> docs(testing): switch deprecated WithInsecure to WithTransportCredentials

spanner/go.mod, spanner/go.sum, spanner/test/opentelemetry/test/go.mod, spanner/test/opentelemetry/test/go.sum, spanner/value.go
json-iterator heavily relies on an unmaintained modern-go/reflect2
that pokes at the internals of Go runtime. This was shown to cause
failures in https://github.com/golang/go/issues/54766#issuecomment-1983808590.
Switching to encoding/json does come with a performance penalty.
Updates #9380
=> fix(spanner): remove json-iterator dependency

auth/internal/transport/cba.go
Implications of this change:
1. If no default certificate sources are available in the environment (i.e. no SecureConnect or ECP cert), then the before & after behavior are identical.
2. If SecureConnect cert source is available (i.e. Googlers with EndpointVerification installed), then connections are automatically upgraded to mTLS. This is deemed a safe upgrade from policy enforcement perspective. From a latency perspective, since this does not impact workload use-cases, there should be negligible impact, even if the SecureConnect cert is from a TPM.
3. ECP cert source is enabled via certificate_config.json, which is not widely rolled out at the moment. Those with certificate_config.json configured already have the intention to enable client certificates anyway, so this saves them an …
=> feat(auth): Enable client certificates by default

spanner/integration_test.go
`TestIntegration_SingleUse/max_staleness` is showing flaky behavior and this PR fixes it.
**Background**: The current test has a Max staleness value of `1 sec`. This Bounded staleness mode allow Spanner to pick the read timestamp, subject to a user- provided staleness bound. Spanner chooses the newest timestamp within the provided staleness bound. More details `[here](https://cloud.google.com/spanner/docs/timestamp-bounds#bounded_staleness)`.
**Flakiness Reason**: The test verifies whether the chosen read timestamp is after writes[3] timestamp. But since the staleness value is 1 sec, the chosen timestamp by spanner can be much before the writes[3] timestamp which gices a flaky behaviour with below error
```
SingleUse.Query doesn't return expected timestamp: read got timestamp 2024-05-02 …
```
=> test(spanner): update max staleness bound value

.github/renovate.json
* go.opentelemetry.io/otel 1.25.0 and submodules no longer support Go 1.20
=> chore: freeze opentelemetry-operations-go/exporter/trace at v1.22.0

internal/godocfx/main.go
The cloud.google.com/go/vertexai module should be published under a different path.
=> chore(internal/godocfx): set stem for vertexai

auth/auth.go
3 mins and 45 seconds == 225 seconds.
This error is is harmless but fixing it to make sure comments and
documentation reflect reality.
=> fix(auth): have refresh time match docs

storage/invoke.go, storage/invoke_test.go
We are seeing these errors surfaced via net.OpError as well as url.Error. Update the ShouldRetry function accordingly.
Also, use net.ErrClosed sentinel over string matching.
Fixes #9478
=> fix(storage): retry net.OpError on connection reset

auth/httptransport/httptransport.go, auth/httptransport/httptransport_test.go
Since `http.DefaultTransport` is a `RoundTripper` interface and mutable global variable, it is not safe to assume it is always going to concretely be `*http.Transport`. If it is not, I suppose we should just use the value directly instead of making a `Clone`. The `http.DefaultTransport` being overridden is pretty intentional by application authors, so it is best if we respect that and just reuse it direct.
Fixes #10159
=> fix(auth): handle non-Transport DefaultTransport

internal/kokoro/presubmit.sh
It seems #10064 changed the semantics from files to dirs for significant changes. This caused `CHANGED_DIRS` to fail when the grep test was done as sometimes there is no slash now. This piping was not actually needed though and the cut should work even if the character is not there.
This failure to grep caused presubmits to run for whole repo sometimes when changes were only made in one sub-module.
=> test: fix presubmit script to handle dirs

storage/integration_test.go
This allows easier debugging when integration test runs get stalled as in #10178. No existing tests take longer than this currently.
=> test(storage): add 5m timeout per integration test

storage/integration_test.go
Add bucket/object name for debugging purposes to some integration test failures. I didn't go through everything but this seems like a worthwhile change for common methods anyway.
=> test(storage): add more debugging info

storage/integration_test.go
Some tests had logic in t.Cleanup using the same context. Move context cancellation to t.Cleanup as well so that the cancel happens after this logic executes.
Fixes #10229
=> test(storage): fix context timeout logic

spanner/test/cloudexecutor/executor/internal/inputstream/handler.go
The method `newActionHandler` returns action handlers as per input action. But in case of `unimplemented` actions, it sends the error directly to outcome sender due to which the main program running it does not get this error and proceeds further leading to `nil` pointer exceptions.
Example stack trace:
```
2024-05-21 13:10:55.338176-070014   2024/05/21 13:10:55 ExecuteActionAsync RPC called. Start handling input stream
2024-05-21 13:10:55.338594-070014   2024/05/21 13:10:55 start handling request action:{database_path:"projects/spanner-cloud-systest/instances/cloud-systest0/databases/read_write_test" execute_change_stream_query:{name:"TestCS2" start_time:{seconds:1716322099 nanos:620329000} heartbeat_milliseconds:1000}}
2024-05-21 13:10:55.338673-070014   2024/05/21 13:10:55 rpc error: …
```
=> chore(spanner): fix executor

storage/go.mod
This PR fixes go vet issue in mainline caused by https://github.com/googleapis/google-cloud-go/pull/10257.
Failure: https://github.com/googleapis/google-cloud-go/actions/runs/9218291661/job/25361579548?pr=10253
=> chore(storage): fix go vet issue

internal/protoveneer/cmd/protoveneer/protoveneer.go, internal/protoveneer/cmd/protoveneer/testdata/basic/basic.pb.go, internal/protoveneer/cmd/protoveneer/testdata/basic/golden, internal/protoveneer/support/support.go
Protos represent time using the timestamppb.Timestamp type.
Support converting that to and from a time.Time.
=> chore(internal/protoveneer): support time

aiplatform/apiv1beta1/info.go, internal/gen_info.sh
Add SetGoogleClientInfo methods for each client in the GAPIC.
Also, move the script that generates the file somewhere safe
(internal, for now). In #10272 we put it in the same directory
as the GAPIC, and an automatic process deleted it.
This means it's not really usable with `go generate`, because its
relative location varies by package, so remove that functionality.
=> feat(aiplatform/apiv1beta1): add methods to info.go

auth/grpctransport/grpctransport.go, auth/httptransport/httptransport.go, debug.md, internal/trace/trace.go
* Change default for `GOOGLE_API_GO_EXPERIMENTAL_TELEMETRY_PLATFORM_TRACING` env var flag to OpenTelemetry.
* See https://github.com/googleapis/google-cloud-go/blob/main/debug.md\#telemetry
refs: #2205
refs: #8655
=> feat(internal/trace): deprecate OpenCensus support

auth/credentials/filetypes.go
This is especially important for mtls where clients need to be overridden to include certs
=> fix(auth): pass through client to 2LO and 3LO flows

storage/acl.go, storage/hmac.go, storage/http_client.go
- Also removes an unused `configureCall` method that has been superseded by `configureACLCall`
- `setClientHeader` remains in usage for uploads
=> chore(storage): remove usage of setClientHeader where possible

storage/integration_test.go
Short uids are too short for the number of tests we have now. Use a long space (6 digits instead of 2). Tested locally and ensured that bucket names are still within GCS limits (63 chars max).
Fixes #10338
Fixes #10337
Fixes #10336
Fixes #10335
Fixes #10334
Fixes #10333
=> test(storage): use long uidSpace for buckets

internal/protoveneer/cmd/protoveneer/protoveneer.go, internal/protoveneer/cmd/protoveneer/testdata/basic/golden, internal/protoveneer/support/support.go
Convert a zero time.Time to a nil timestamp proto, instead
of a non-nil proto representing the zero time.
This can matter to services that care whether a timestamp
field is present or not. For example, the UpdateCachedContent
RPC of vertex/genai behaves differently depending on whether
an update time is passed to it.
=> chore(internal/protoveneer): use nil timestamp for zero time

internal/postprocessor/README.md, internal/postprocessor/cloudbuild.yaml
Change the tag used for postprocessor image to approved prefix. Add one with `latest` suffix on approved prefix, and another using the commit sha that produced the image - this way when the next image is pushed with `latest` the dangling image(s) will still be tagged with the approved tag prefix.
Update instructions accordingly. Note: the `docker inspect` and `sed` commands weren't working for me on gLinux, so I removed them and replaced them with the slightly simpler, but not automated, steps of copying it from the `pull` output.
internal bug http://b/334181347
=> fix(internal/postprocessor): use approved image tag

storage/transfermanager/downloader.go, storage/transfermanager/integration_test.go
DownloadOutput should include the range so if multiple ranges were requested for the same file and the download failed, the caller can identify which offset the error occurred on.
=> feat(storage/transfermanager): add Range to output

vertexai/genai/aiplatformpb_veneer.gen.go, vertexai/genai/caching.go, vertexai/genai/caching_test.go, vertexai/genai/chat.go, vertexai/genai/client.go, vertexai/genai/client_test.go, vertexai/genai/config.yaml, vertexai/genai/example_test.go, vertexai/go.mod, vertexai/go.sum, vertexai/internal/support/support.go, vertexai/internal/support/support_test.go
This PR takes over from #10310 and adds the dependency bump for `cloud.google.com/go/aiplatform v1.68.0` following the landing of #9772
=> feat(vertexai): explicit caching

.github/CODEOWNERS
`vertexai` depends on the `aiplatform` module and is pretty familiar with the api surface, so they should have CODEOWNERS as well as the admins.
=> chore: give go-vertexai team aiplatform CODEOWNERS

storage/invoke.go
This is another retryable net.OpError that can arise when a connection has been closed. So far we've only seen this in TestRetryConformance cases rather than in customer issues, but there is no reason not to do a retry and we think it can cut down on flakes from this test.
I'm going to do another PR to add this to google-api-go-client since it often occurs on uploads.
Updates #9178
=> fix(storage): retry broken pipe error

storage/bucket.go, storage/bucket_test.go, storage/integration_test.go
Currently setting an empty soft delete policy to disable the feature does not work on bucket creation (only update). This fixes the issue by forcing the library to send a zero value in this case (sending a null does not seem to work).
Also adds this case to the relevant integration test.
Fixes #10380
=> fix(storage): allow empty soft delete on Create

spanner/errors.go, spanner/integration_test.go, spanner/transaction.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/10031
Customers can check row not found cases with below condition
```
if errors.Is(err, spanner.ErrRecordNotFound) {
```
=> feat(spanner): add support of checking row not found errors from ReadRow and ReadRowUsingIndex

storage/example_test.go
Adds example for how to override in order to update an object's retention policy.
Fixes #9228
=> doc(storage): add example for retention

auth/credentials/detect.go, auth/credentials/detect_test.go
This matches the behaviour of the old library.
=> fix(auth): return error if envvar detected file returns an error

backupdr/CHANGES.md, cloudcontrolspartner/CHANGES.md, cloudquotas/CHANGES.md, edgenetwork/CHANGES.md, securesourcemanager/CHANGES.md, securitycentermanagement/CHANGES.md, telcoautomation/CHANGES.md
BEGIN_PUBLIC
chore(backupdr): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(cloudcontrolspartner): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(cloudquotas): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(edgenetwork): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(securesourcemanager): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(securitycentermanagement): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
BEGIN_PUBLIC
chore(telcoautomation): release v1.0.0
Release-As: 1.0.0
END_PUBLIC
=> chore: promote clients to GA

pubsub/go.mod, pubsub/go.sum, pubsub/iterator.go, pubsub/pullstream.go, pubsub/pullstream_test.go, pubsub/subscription.go
Similar to https://github.com/googleapis/java-pubsub/pull/77, this will improve ordering key affinity and allow Pub/Sub servers to determine if streams are opened from the same subscriber client instance.
=> feat(pubsub): add client ID to initial streaming pull request

auth/grpctransport/grpctransport.go, auth/grpctransport/grpctransport_test.go
Porting https://github.com/googleapis/google-api-go-client/pull/2326 which happened after we had made parity change to new auth lib.
=> fix(auth): support gRPC API keys

compute/apiv1/smoke_test.go
This image referenced in the test EOLed on June 30th so the test had been failing since then. See https://cloud.google.com/compute/docs/images/os-details#debian
Fixes: #10477
=> test(compute): update image in test

auth/internal/transport/cert/default_cert.go, auth/internal/transport/cert/workload_cert.go, auth/internal/transport/cert/workload_cert_test.go
Side Note: Verified this is compatible with existing OAuth2 3-legged auth flow. This is expected to immediately work with X509 workload identity auth flow once that feature is released.
=> feat(auth): Add workload X509 cert provider as a default cert provider

profiler/proftest/proftest.go
Debian 10 image is no longer available which is causing tests using the `proftest` harness to fail with
`integration_test.go:352: failed to start GCE instance: failed to get image from family "debian-10" in project "debian-cloud": googleapi: Error 404: The resource 'projects/debian-cloud/global/images/family/debian-10' was not found, notFound`
Debian 11 is the oldest available version:
```console
$ gcloud compute images list | grep debian              
debian-11-bullseye-arm64-v20240611             debian-cloud         debian-11-arm64                                READY                                              
debian-11-bullseye-v20240611                   debian-cloud         debian-11                                      READY …
```
=> chore(profiler): upgrade default proftest gce image to debian-11

storage/transfermanager/downloader.go
=> fix(storage/transfermanager): WaitAndClose waits for Callbacks to finish

pubsub/pstest/fake.go
This PR introduces new field `Topic` to the `pubsub/pstest.Message` that contains the Topic ID of published Pub/Sub messages to the `pstest.Server`.
Closes #10439
=> feat(pubsub/pstest): add Message.Topic field and populate on publish

containeranalysis/apiv1/container_analysis_client.go, containeranalysis/apiv1/container_analysis_client_example_test.go, containeranalysis/apiv1/doc.go
I hand patched this change in because this "generated" client is very hand tailored. I also took the opportunity to update the client in general to match other generated practices today.
Fixes: #10517
=> feat(containeranalysis): add GetVulnerabilityOccurrencesSummary RPC

auth/internal/internal.go
When this code was first introduced we did not have the context methods in the metadata package so we set the timeout on the client. Now that we do we should use context to set the timeout and use the default client the metadata package provides.
Fixes: #10544
=> fix(auth): use default client for universe metadata lookup

bigquery/bigquery.go, bigquery/job.go
fix(bigquery): reduce the initial backoff for job polling
This PR reduces initial backoffs and multipliers used during job polling.  Previously we used a 1s starting backoff, this has been reduced to 50ms.  In job execution most time is typically spent in server, waiting for the hanging GetQueryResults response.
This should in generally reduce wasted wait for jobs that poll for multiple iterations.
Fixes: https://github.com/googleapis/google-cloud-go/issues/10555
=> fix(bigquery): reduce default backoffs

firestore/doc.go, firestore/examples_test.go, firestore/from_value.go, firestore/integration_test.go, firestore/query.go, firestore/query_test.go, firestore/vector.go, firestore/vector_test.go
Add documention for vector search.
Do minor refactoring of code.
=> chore(firestore): minor tweaks and doc for vector search

internal/postprocessor/config.yaml
Because we are not copying the gapic we have to explicitly set this value.
=> chore: fix bigtable config

bigtable/admin.go, bigtable/type.go, bigtable/type_test.go
protoToType needs to be reused by terraform, so we are exposing it.
The trigger for this change is we need in Terraform to accept a json string representing a protobuf of a column family type, so we can properly create and update column family types. We want to be flexible enough to not accept just hardcoded types, but also custom types, thus eliminating the need for client releases every time the server supports a new type.
=> feat(bigtable): expose protoToType

storage/client_test.go, storage/invoke.go
GCS is in some cases returning these for internal timeouts, so they need to be retried. I added an extra context error check to our retry logic to ensure that they can always be distinguished from user-set deadlines as well as some tests.
See internal bug b/333307965
Requires googleapis/storage-testbench#663
Fixes #9827
=> fix(storage): retry gRPC DEADLINE_EXCEEDED errors

.github/renovate.json
* grpc v1.65.0 changes support policy to cover only the latest TWO releases of Go
* See https://github.com/grpc/grpc-go/releases/tag/v1.65.0
=> chore: freeze google.golang.org/grpc at v1.64.1

spanner/client.go, spanner/client_test.go, spanner/transaction.go, spanner/transaction_test.go
* This PR add support of using Multiplexed session if enabled with `client.Apply(context.Background(), {mutations}, spanner.ApplyAtLeastOnce())`
=> feat(spanner): add support of multiplexed session support in writeAtleastOnce mutations

storage/integration_test.go
Fixes #10618 
Http-equivalent error in grpc was causing test to erroneously fail
=> fix(storage): check for grpc NotFound error in HMAC test

storage/integration_test.go
=> fix(storage): add retryalways policy to encryption test

auth/auth.go, auth/credentials/detect.go, auth/credentials/downscope/downscope.go, auth/credentials/externalaccount/externalaccount.go, auth/credentials/idtoken/idtoken.go, auth/credentials/idtoken/idtoken_test.go, auth/credentials/idtoken/validate.go, auth/credentials/impersonate/idtoken.go, auth/credentials/impersonate/impersonate.go, auth/credentials/internal/externalaccount/executable_provider_test.go, auth/credentials/internal/externalaccount/externalaccount_test.go, auth/credentials/internal/externalaccount/impersonate_test.go, auth/credentials/internal/externalaccount/x509_provider_test.go, auth/credentials/internal/externalaccountuser/externalaccountuser_test.go, auth/credentials/internal/gdch/gdch_test.go, auth/credentials/internal/impersonate/impersonate_test.go, auth/credentials/internal/stsexchange/sts_exchange_test.go, auth/httptransport/httptransport_test.go, auth/internal/internal.go, auth/internal/internal_test.go, auth/internal/testutil/testdns/dns.go, auth/internal/testutil/testgcs/storage.go, auth/threelegged.go
Before this commit, `CloneDefaultClient` would panic if `http.DefaultTransport`
was set to something that's not an `*http.Transport`. It is very much possible
that this is the case if users assign a different `http.RoundTripper` to
`http.DefaultTransport`, for example for tracing purposes.
This commit renames `CloneDefaultClient` to `DefaultClient`, and changes its
behavior to check if the `http.DefaultTransport` can be cloned, and uses the
clone if possible. If it can't be cloned, it'll use the `http.DefaultTransport`
directly.
Fixes: #10638
=> fix(auth): make default client creation more lenient

bigquery/storage_iterator.go, bigquery/storage_iterator_test.go
When service side returns non-retryable errors faster than they are being consumed by the user (via `Next` call), the `processStream` goroutine can become locked and leak, even when context is cancelled. With this PR, we wrap the call to `it.errs` call with `select` and check for context done. 
Towards #10672
=> fix(bigquery): processStream check ctx done when queuing non retryable err

.github/workflows/vet.yml
* Fixes go 1.20 error honnef.co/go/tools@v0.5.0: invalid go version
=> chore(github): pin staticcheck in vet.yml to v0.4.7 

internal/gapicgen/generator/genproto_test.go, internal/postprocessor/config.yaml, internal/postprocessor/main.go
Follow-up fix for post-processor error from: #10708
Also fix go.mod version for new clients.
Fixes: #10715
=> chore: add release level for datastore

bigtable/conformance_test.sh
The Go version has been updated in tests repository here: https://github.com/googleapis/cloud-bigtable-clients-test/commit/6de431b0921124047053658bdd896f0234530955
So, the conformance tests do not run and throw error:
```
+ tee -a /home/runner/work/google-cloud-go/google-cloud-go/google-cloud-go/bigtable/sponge_log.log
go: errors parsing go.mod:
/home/runner/work/google-cloud-go/google-cloud-go/cloud-bigtable-clients-test/go.mod:5: unknown directive: toolchain
```
This PR fixes this by updating the go version in invocation of conformance test run
=> feat(bigtable): Update go version for conformance tests

auth/internal/transport/cert/secureconnect_cert.go, auth/internal/transport/cert/secureconnect_cert_test.go
Some users explicitly have their home directories set to `/dev/null`. When opening a file that's "under that directory", instead of getting the normal `ENOENT`, one should expect to get `ENOTDIR`.
Unfortunately, due to the variety of cases under which `ENOTDIR` is returned, the go team has declined to include ENOTDIR in `ErrNotExist`. (https://golang.org/issues/18974)
The most robust solution in this case (following [1]) is to treat any
read error as `errSourceUnavailable`. This has the mixed-benefit of also
covering EPERM. (hopefully this doesn't make it too hard to track down
permissions problems for secure connect users)
Resolves: #10696
[1]: https://go-review.googlesource.com/c/oauth2/+/493695
=> fix(auth): handle ENOTDIR when opening cert config

datastore/go.mod, datastore/go.sum
This references the version of genproto that has the old library aliased to this one.
=> chore(datastore): update genproto version

auth/auth.go
Fix link in Go doc comment per https://go.dev/doc/comment#links, so that it renders properly on pkgsite.
=> docs(auth): fix Go doc comment link

bigtable/admin.go, bigtable/admin_test.go, bigtable/bttest/inmem.go, bigtable/integration_test.go
It is currently only possible to update a column GC policy. We want to be able to also update the value_type of a column family.
=> feat(bigtable): Add UpdateFamily to allow updating a family type

auth/credentials/detect_test.go, auth/credentials/filetypes.go, auth/credentials/idtoken/integration_test.go
Because we were explicitly setting the value of quota project in the credentials package the logic that should have checked the environment variable was never hit if the value was set in the creds file. So for now we will not set it in this package. The getter on the creds will then default to the correct logic in internal.go.
Also mark an integration test as such so it does not run when the short flag is passed.
Fixes: #10804
=> fix(auth): choose quota project envvar over file when both present

pubsub/trace.go
Export the function NewMessageCarrierFromPB which, given a protobuf PubsubMessage, returns a TextMapCarrier which can be used to extract trace contexts.
This allows it to be used in e.g. HTTP push endpoints.
Fixes #10828
=> feat(pubsub): allow trace extraction from protobuf message

bigtable/type.go, bigtable/type_test.go
This makes it possible to check if a Type is actually set or not
=> feat(bigtable): add "TypeUnspecified" to represent an unspecified type

.github/renovate.json
* Pin golang.org/x/mod at v0.20.0
* golang.org/x/mod@v0.21.0 requires go >= 1.22.0
* Pin golang.org/x/tools at v0.24.0
* golang.org/x/tools@v0.25.0 requires go >= 1.22.0
=> chore(.github): pin golang.org/x/mod and golang.org/x/tools in renovate

bigquery/dataset_integration_test.go
Switch test to use a newly created dataset rather than manipulate the shared dataset instance available for all tests, to avoid tickling the mutation limit.
Fixes: https://github.com/googleapis/google-cloud-go/issues/10902
=> test: isolate time travel test

storage/dataflux/fast_list.go, storage/dataflux/integration_test.go, storage/dataflux/range_splitter.go, storage/dataflux/range_splitter_test.go
feat: add dataflux range_splitter which will be consumed by worksteal algorithm
Dataflux fast-listing will be used to quickly list objects in a bucket in parallel leveraging worksteal algorithm. Worksteal algorithm uses range splitter to split alphabets for parallel listing.
newRangeSplitter is to initialize range splitter and splitRange is used to divide start and end string into a given number of equally spaced splits.
Fixes https://github.com/googleapis/google-cloud-go/issues/10731
=> feat(storage/dataflux): add range_splitter #10748

auth/auth.go
* Avoid user-provided context timeouts incompatible with async token refresh.
=> fix(auth): use new context for non-blocking token refresh

.github/blunderbuss.yml
This PR points the blunderbuss at alvaro while I'm OOO.
Longer term we need to find a better way to articulate the intersection of go + bigquery, but not today.
=> chore: reassign bigquery blunderbuss to alvarowolfx

bigquery/integration_test.go, bigquery/iterator.go
=> fix(bigquery): missing schema for empty result set on stateless queries

auth/grpctransport/directpath.go, auth/grpctransport/directpath_test.go
* Support `InternalOptions.EnableNonDefaultSAForDirectPath` in `isTokenProviderDirectPathCompatible`.
fixes: #10907
=> fix(auth): restore support for non-default service accounts for DirectPath

.github/workflows/vet.sh, firestore/examples_test.go, firestore/transaction.go, firestore/transaction_test.go
Adds a new ```TransactionOption``` -- ```GetCommitTime``` -- that allows the caller to specify the address of a ```time.Time``` where the commit time of the transaction should be written, upon successful commit.
=> feat(firestore): add WithCommitResponseTo TransactionOption

bigquery/storage_client.go, bigquery/storage_integration_test.go, bigquery/storage_iterator.go, bigquery/table.go
When reading result sets using the Storage Read API Acceleration enabled, currently the read session is created by default in the table's project. This works for cases where the destination table is not specified and automatically created, which defaults to the project where the the query or job was created. But when reading a table directly or specifying a destination table, it doesn't work in cases where the client doesn't have BQ Storage permissions (just table read permission for example). This is a common use case where some customers have a main billing project and this project has access to other GCP projects with just permission to read data from BigQuery tables.
With this PR, we default to use the defined Query/Job projectID (which defaults to the current …
=> fix(bigquery): create read session with client or job projectID

spanner/admin/database/apiv1/init.go, spanner/admin/instance/apiv1/init.go, spanner/client.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/10927
=> perf(spanner): use passthrough with emulator endpoint

auth/auth.go
I am not sure if this will fix the test, but it is a better behaviour either way I think. If this happens again my only guess is it has to do with rounding depending on the initial time captured. If this test fails again we should use a reletive offset time instead of a fully random time.
Releated: #10950
=> test(auth): use the same now when checking tokenstate

auth/internal/transport/cba.go, auth/internal/transport/cba_test.go
It's now possible to have S2A run on two ports, so updating the logic here to try second address if the first choice does not work (i.e. mTLS creds can not be loaded)
=> fix(auth): try talk to plaintext S2A if creds unavailable for mTLS-S2A

internal/postprocessor/Dockerfile
We do this in our CI images as well. Some of our tools now require 1.22+ and this gets around the issue while preserving the version used to run the app. Not having this was causing postprocess image builds to fail.
=> chore: allow go toolchain to upgrade just for installing tools

internal/postprocessor/Dockerfile
As written before the auto toolchain was only provided to the first command being run. Now it is applied to all commands in the scoped sub-shell -- denoted by the parens.
=> chore: apply GOTOOLCHAIN change to all commands in run block

spanner/value.go, spanner/value_test.go
Fixes https://github.com/googleapis/google-cloud-go/issues/10993
This PR supports decoding PROTO and ENUM types to a custom type whose variant is a base type.
```
var b []byte.            # basetype
var nb nullBytes.    # custom type
```
=> fix(spanner): decode PROTO to custom type variant of base type

storage/bucket_test.go
Tests running on GCE VMs automatically fall back to using the local metadata service to detect the local default service account. In those cases, tests for malformed creds won't fail, but they should return a VM-specific default service account email.
=> fix: Fix default service account tests on GCE.

doc.go
Show users how to get the gRPC status from our error type. We should push users to handle error constantly where possible. 
Internal Bug: 372880394
=> docs: clean up info on gRPC error parsing

auth/grpctransport/pool_test.go
I believe this test started failing because of a recent CI infra move. Test could also just be removed as it does not assert anything.
=> test(auth): fix TestWithEndpointAndPoolSize

auth/oauth2adapt/oauth2adapt.go, auth/oauth2adapt/oauth2adapt_test.go
This was missed in the orginal implmentation. The code is still not prefect as converting from an oauth2.Token to auth.Token is lossy because there is no way to extract out the whole metadata context. Converting from auth.Token -> oauth2.Token is not lossy though.
This bug was discovered because some direct path checks look for theses metadata values. Just to be safe we will preserve both forms of these values in the final token metadata, if present.
Internal Bug: 376281562
=> fix(auth/oauth2adapt): convert token metadata where possible

auth/credentials/idtoken/idtoken.go, auth/credentials/idtoken/idtoken_test.go, auth/credentials/impersonate/idtoken.go, auth/credentials/impersonate/impersonate.go, auth/credentials/impersonate/impersonate_test.go
* add credentials validation to idtoken.Options
refs: #10953
=> auth(fix): remove incorrect validation from impersonate.CredentialsOptions

storage/http_client.go
1. Fixing the stall-timeout value in the log.
2. Adding request-id in the log - this will be helpful for debugging.
Sample log:
```
2024/11/01 11:56:35 stalled read-req (0xc000232640) cancelled after 0.500000s
2024/11/01 11:56:37 stalled read-req (0xc000232640) cancelled after 0.523647s
2024/11/01 11:56:40 stalled read-req (0xc000232640) cancelled after 0.548412s
```
=> chore(storage): adding request-id in the stall-retry log

storage/go.mod, storage/go.sum, storage/option_test.go
Since this is a short test it should work locally without requiring any project permissions. The current exporter fails without a project with cloud monitoring permissions. Replace with an exporter to stdout instead.
=> test(storage): fix metrics exporter test

pubsublite/integration_test.go
Adds retries for list requests.
Fixes: https://github.com/googleapis/google-cloud-go/issues/11081
=> test(pubsublite): fix flaky TestIntegration_ResourceAdminOperations

.release-please-manifest-individual.json, .release-please-manifest-submodules.json, release-please-config-individual.json, release-please-config-yoshi-submodules.json
There was a time when these releases were being handled more by other teams, but this is no longer the case. Let's bring them back in the fold for timely releases.
=> chore: move ai libs back to main release train

spanner/session.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/11126
=> fix(spanner): add safecheck to avoid deadlock when creating multiplex session

bigquery/storage/managedwriter/adapt/protoconversion.go, bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/managed_stream.go, bigquery/storage/managedwriter/retry.go
Another unparam related PR, this one focused on reducing unused params in the managedwriter and its adapt subpackage.
Followup to https://github.com/googleapis/google-cloud-go/pull/11149
=> refactor(bigquery/storage/managedwriter): simplify signatures

go.mod, go.sum
Need newer version of oauth2adapt in google-api-go-client but currently it pulls in old one
```
bahaaiman@xxx:~/Documents/google-api-go-client$ go mod graph | grep oauth2adapt@v0.2.4
cloud.google.com/go@v0.116.0 cloud.google.com/go/auth/oauth2adapt@v0.2.4
bahaaiman@xxx:~/Documents/google-api-go-client$ 
```
=> chore: Update oauth2adapt

storage/dataflux/integration_test.go
Skipping for now to unblock CI. Issues should be resolved and tests unskipped.
=> test(storage/dataflux): skip flaky tests

auth/credentials/idtoken/validate.go, auth/credentials/idtoken/validate_test.go
fixes: #11190
fixes: #11189
fixes: #11188
=> fix(auth): ensure endpoints are present in Validator

storage/dataflux/worksteal_test.go
This test seems to be hanging occasionally in the CI. More investigation is needed for a fix. The underlying code is still in preview.
=> test(storage): skip dataflux emulator test

storage/go.mod, storage/go.sum
Picks up a fix for an issue that was causing a hang on the first call to a new storage client for some systems.
=> chore(storage): bump grpc dep

internal/gapicgen/cmd/genbot/Dockerfile
* Update cmd/genbot/Dockerfile to 1.23-alpine
=> chore(internal/gapicgen): support Go 1.23

auth/grpctransport/directpath.go, auth/grpctransport/directpath_test.go
We need to first ensure a token is a compute type before we enforce the option to allow for a non-default service account. This was leading to a strange XDS error if say a user credential was supplied and this option was enabled.
=> fix(auth): check compute cred type before non-default flag for DP

auth/credentials/internal/gdch/gdch.go, auth/credentials/selfsignedjwt.go, auth/internal/internal.go, auth/internal/jwt/jwt.go
In a future PR we will need to support elliptic curves private keys. We use these keys only to sign JWTs. All of the types of keys we parse impl the crypto signer interface, so lets use it.
GDCH is the auth flow that will soon demand the need for parsing EC keys.
=> refactor(auth): make key parsing less specific

spanner/batch.go, spanner/client.go, spanner/client_test.go, spanner/cmp_test.go, spanner/errors.go, spanner/grpc_client.go, spanner/internal/testutil/inmem_spanner_server.go, spanner/read.go, spanner/read_test.go, spanner/request_id_header.go, spanner/request_id_header_test.go, spanner/sessionclient.go, spanner/transaction.go
In tandem this specification
https://orijtech.notion.site/x-goog-spanner-request-id-always-on-gRPC-header-to-aid-in-quick-debugging-of-errors-14aba6bc91348091a58fca7a505c9827
This change adds sending over the "x-goog-spanner-request-id" header
for every unary and streaming call, in the form:
<version>.<processId>.<clientId>.<channelId>.<requestCountForClient>.<rpcCountForRequest>
where:
* version is the version of the specification
* processId is a randomly generated uint64 singleton for the lifetime of a process
* clientId is the monotonically increasing id/number of gRPC Spanner clients created
* requestCountForClient is the monotonically increasing number of requests made by the client
* channelId currently at 1 is the Id of the client for Go
* rpcCountForRequest is the number of …
=> feat(spanner): implement generation and propagation of "x-goog-spanner-request-id" Header

spanner/request_id_header_test.go
Temporarily skip RequestIDHeader tests if environment variable
GOOGLE_CLOUD_SPANNER_MULTIPLEXED_SESSIONS=true
is set. This ensures that normal development can go on without breaking CI/CD for other developers of this repository.
Updates #11308
=> test(spanner): temporarily skip TestRequestIDHeader if using multiplexedSessions

storage/dataflux/integration_test.go, storage/dataflux/range_splitter.go, storage/dataflux/worksteal.go, storage/dataflux/worksteal_test.go
This change addresses an intermittent deadlock issue when reading from the range channel. The fix introduces a 200ms timeout on all reads off of range, opting to re-check for available work if the timeout is triggered. Since this timeout is only applied to reads off of the channel it should not introduce any new blocking behavior.
=> fix(storage/dataflux): address deadlock when reading from ranges

spanner/integration_test.go
* Cloud-devel and staing universe fails on DeleteSession RPC, this is to skip tests until the backend is fixed
=> test(spanner): skip failing tests on cloud-devel and staging

pubsub/loadtest/loadtest.go, pubsub/v2/integration_test.go, pubsub/v2/iterator.go, pubsub/v2/iterator_test.go, pubsub/v2/subscription.go, pubsub/v2/subscription_test.go, pubsub/v2/topic.go
Part of #11368 
- PublishSettings.BufferedByteLimit
- ReceiveSettings.Synchronous
- ReceiveSettings.UseLegacyFlowControl
- MaxExtensionPeriod -> MaxDurationPerLeaseExtension
- MinExtensionPeriod -> MinDurationPerLeaseExtension
- NumGoroutines (aka num streams) = 10 -> 1
=> deprecate(pubsub/v2): remove and rename existing settings

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/vet.sh, .github/workflows/vet.yml, internal/postprocessor/Dockerfile, internal/postprocessor/main.go, profiler/kokoro/integration_test.sh, storage/internal/benchmarks/continuous_reads.go, storage/transfermanager/downloader.go
I found a few places in the codebase where Go 1.21 is still used after support for it has officially been dropped. This updates those to Go 1.22.
=> chore: update remaining usages of Go 1.21 to 1.22

storage/http_client.go, storage/storage.go, storage/storage_test.go
The current error has information specific to signed urls which may be confusing. I changed that var name as well so as to avoid this confusion in the future.
=> fix(storage): return the appropriate error for method not supported

internal/postprocessor/releaseplease.go, release-please-config-yoshi-submodules.json
We used to release these module individually. We no londer due and marking them as such in the post processor manipulates the release please configuration files.
=> chore: fix automation for ai release

storage/integration_test.go
Fixes #11397
Same change should be made to currently skipped Metrics in GCE test (which may need to be merged with this test to avoid the same issue, and/or we should turn off internal logging).
This test only has to run once, and creating the manual reader multiple times causes issues.
=> test(storage): run metrics enablement test only once

spanner/transaction.go, spanner/transaction_test.go
Any TransactionOptions that had been set for a ReadWriteStmtBasedTransaction would not be remember and carried over if the transaction was retried. This would cause the retry to for example miss the transaction tag.
=> fix(spanner): ReadWriteStmtBasedTransaction would not remember options for retries

bigtable/go.mod, bigtable/go.sum, go.work.sum, internal/generated/snippets/go.sum, spanner/go.mod, spanner/go.sum, spanner/test/opentelemetry/test/go.mod, spanner/test/opentelemetry/test/go.sum
Ran `github.com/envoyproxy/go-control-plane/envoy@latest && go mod tidy`.
Updates: #11344
=> chore: bump github.com/envoyproxy/go-control-plane/envoy

bigtable/conformance_test.sh, bigtable/internal/testproxy/known_failures.txt
Adding known failures similar to nodejs
https://github.com/googleapis/nodejs-bigtable/blob/589540475b0b2a055018a1cb6e475800fdd46a37/.kokoro/mandatory-conformance.sh#L39-L42
=> test(bigtable): Add known failures for unimplemented features

bigquery/storage/managedwriter/options_test.go
This switches usage of sync.Mutex in options testing from allowing unexported to ignoring outright.  There's changes to the sync package in the latest versions of go head that aren't compatible with AllowUnexported, and the comparison isn't relevant to the code under test.
=> testing(bigquery/storage/managedwriter): fix go-cmp diff usage

bigquery/storage/managedwriter/connection.go, bigquery/storage/managedwriter/managed_stream_test.go
This PR enables a more graceful shutdown when we're doing client initiated reconnects, typically in response to things like schema changes.
With this PR, rather than immediately cancelling the previous connection context, we instead use a goroutine to defer this by a fixed interval, which gives our recv goroutine more time to process any incoming notifications from the service.
This can yield reductions in duplicate rows for some scenarios, particularly when EnableWriteRetries is enabled and we see sequential disconnects (e.g. a multiplex connection observing a number of schema updates).
It does, however, yield possible short term increases in resource usage, as we're now potentially retaining goroutines/channels/connections for a longer interval during these reconnect events.  This PR …
=> feat(bigquery/storage/managedwriter): graceful connection drains

internal/postprocessor/main.go
We need to pin the go version used for creating modules in the postprocessor. If it is not pinned the latest is assumed -- which will go out of date each time a new version of Go is released.
=> chore: update go postprocessor version

storage/integration_test.go
=> test(storage): retry metadata check in SoftDelete test

storage/grpc_client.go
Appendable writes were duplicating the x-goog-request-params header which caused issues server side. Remove this.
For append writes we need to include appendable=true and an optional routing token in this header.
=> fix(storage): remove duplicate routing header

spanner/request_id_header.go, spanner/request_id_header_test.go
Implements a new requirement that randIDForProcess should be a hexadecimal value with the format specifier "%016x".
Fixes #11545
=> feat(spanner): make randIDForProcess hexadecimal in x-goog-spanner-request-id

auth/grpctransport/grpctransport.go, auth/internal/transport/cba.go, auth/internal/transport/cba_test.go
* Embed `google.golang.org/grpc/credentials.TransportCredentials` interface in new struct type with additional data.
refs: #11588
See:
* [“Accept interfaces, return structs” in Go](https://bryanftan.medium.com/accept-interfaces-return-structs-in-go-d4cab29a301b)
* [Embedding in Go: Part 3 - interfaces in structs](https://eli.thegreenplace.net/2020/embedding-in-go-part-3-interfaces-in-structs/)
=> refactor(auth): refactor GetGRPCTransportCredsAndEndpoint return type to struct

spanner/transaction.go
This PR fixes the case for inline begin
=> chore(spanner): remove previous txn id from selector

spanner/go.mod
Retract spanner releases affected by https://github.com/googleapis/google-cloud-go/issues/11630. This will prevent the Go tool from selecting these versions using MVS. Builds where these releases are currently selected will still work, but the user will receive a warning.
=> fix(spanner): retract versions with bug with use of previous transaction ID using regular session

.github/CODEOWNERS
Replace outdated cloud-storage-dpes group name with gcs-sdk-team
=> chore: set gcs-sdk-team as GCS CODEOWNERS

spanner/client_test.go, spanner/regression_test.go, spanner/request_id_header.go
This change fixes a destructive context operation that dropped all prior headers, metadata.NewOutgoingContext sadly doesn't document that it doesn't reuse the input conext negating the expectation in Go that building from a parent context brings along the prior keys and metadata. While here, this chhange adds a regression test to ensure that in the future, any dropped or lost metadata will be reported during development.
Fixes #11656
=> fix(spanner): avoid desructive context augmentation that dropped all headers

spanner/client.go
=> fix(spanner): revert the ALTS bound token enablement

pubsub/go.mod, pubsub/go.sum
Bumps cloud.google.com/go to latest version
=> chore(pubsub): bump cloud.google.com/go version

bigquery/benchmarks/bench.go, bigquery/storage_integration_test.go
=> fix(bigquery): Increase timeout for storage api test and remove usage of deprecated pkg

third_party/pkgsite/print_type.go
This package is used by `godocfx`. The limit is causing some comments to be omitted on types when they should be included.
=> fix(third_party/pkgsite): increase comment size limit

auth/grpctransport/grpctransport.go
We switched to `Dial` orginally because of grpc/grpc-go#7556. Now that this is fixed we can call DialContext again. In the future we still will want to migrate to the new API directly, but this will require more testing.
Related: #11118
=> fix(auth): restore calling DialContext

pubsub/pstest/fake.go, pubsub/subscription.go, pubsub/subscription_test.go, pubsub/topic.go, pubsub/topic_test.go, pubsub/transform.go
This PR adds support for message transforms, a new slice field in topics and subscriptions.
Original proto changes can be found [here](https://github.com/googleapis/googleapis/commit/616127016cd4e657a1e177462539f581fbca5c7a), with the exception that topics and subscriptions now have `disabled` as a field rather than `enabled`.
=> feat(pubsub): support message transforms

pubsub/v2/subscription.go, pubsub/v2/subscription_test.go, pubsub/v2/topic.go
Contributes to #11368
Some presubmit checks will fail and this is expected. This should be resolved when making the final merge from v2-trunk to main.
=> feat(pubsub): rename lease settings, change byte limit default

storage/grpc_client.go, storage/grpc_writer.go, storage/integration_test.go
This makes Writer.Attrs().Size true to the last persisted size value received from GCS.
Also fixes a hang in some takeover cases introduced by #12012
=> fix(storage): fix unfinalized write size

bigquery/copy.go, bigquery/copy_test.go, bigquery/extract.go, bigquery/extract_test.go, bigquery/load.go, bigquery/load_test.go, bigquery/query.go, bigquery/query_test.go
This PR adds support for explicitly selecting a reservation to use when executing a job.  It also includes support for optimized query execution (running via jobs.query vs jobs.insert).
=> feat(bigquery): support per-job reservation assignment

storage/client_test.go
gRPC deadlines may be triggered before client-side context deadlines. This was already handled in a different test, so we extend it to the remaining tests which check context.DeadlineExceeded.
=> test(storage): Handle gRPC deadlines in tests.

storage/integration_test.go
The client isn't used in the test; options must be passed in directly to the direct connectivity check.
Fixes #11991
=> test(storage): fix DoNotDetectDirectConnectivityWhenDisabled

storage/retry_conformance_test.go
cmp.Diff is not an efficient way to compare long byte slices. Since this is all random content anyway, just compare md5s.
=> test(storage): Compare big byte slices faster in tests.

storage/grpc_writer.go, storage/integration_test.go
After a Flush call, we weren't correctly tracking the pipe reader to close to signal to Write that an error had happened. Fixes that issue and adds another flush to the test, which triggers the hang without this fix.
=> fix(storage): fix append writer hang

internal/actions/cmd/changefinder/main.go
Currently: `fix(ai):upgrade deps`
Should be: `fix(ai): upgrade deps`
=> chore(internal/actions): fix missing space in commit message

spanner/client.go
As seen in b/415354418, this new experimental feature introduced by https://github.com/grpc/grpc-go/pull/8126 is not yet stable and may cause intermittent CloudPath fallbacks.
As a user of the OSS gRPC library, CS library should explicitly disable it until the underlying issue is fixed.
=> fix(spanner): explicitly disable gRPC new pickfirst.

bigquery/integration_test.go
This PR relaxes edition validation to handle the unpopulated case.
Fixes: https://github.com/googleapis/google-cloud-go/issues/12223
=> testing(bigquery): relax stats validation testing

spanner/client.go, spanner/metrics.go, spanner/read_test.go
- AFE and GRPC metrics will be disabled by default.
- If direct path is enabled AFE and GRPC metrics will be enabled unless explicitly disabled by user via env `SPANNER_DISABLE_AFE_SERVER_TIMING`, `SPANNER_DISABLE_DIRECT_ACCESS_GRPC_BUILTIN_METRICS`
=> chore(spanner): always enable AFE native metrics if direct path is used unless explicitly disabled

spanner/row.go, spanner/row_test.go
Fixes #11101 
**Why is it an issue?**
We are creating a new pointers for each columns only once while decoding the first row and reusing it in subsequent rows. In the decoding, if customer didn't set certain values, it's picking up values from previous column since pointers always same when DecodeSpanner is called. When we try to call DecodeSpanner, we need to make sure we have to use new memory instead of reusing it.
=> fix(spanner): row mismatch in SelectAll using custom type

.github/workflows/vet.sh, internal/postprocessor/execv/gocmd/gocmd.go, internal/postprocessor/main.go
Today we currently run goimports in our post processor over all files in the repo. Because of this the purposed changes from owlbot always has a large diff from what is landed in our repo. This in turn causes a lot of churn in the owlbot PRs as well as everyone gettings added as reviewers onto the PR. With this change we will no longer format the files that we don't contorl the generation of -- the raw proto gen. The files are still valid go code and the only difference is that imports won't be sorted in the style goimports likes. The upside is it fixes the other issues outlined above.
gofmt was removed as goimports is a super-set of features.
=> chore(internal/postprocessor): don't format pb.go files

.github/.OwlBot.yaml, ai/README.md, ai/generativelanguage/apiv1/doc.go
Direct new users of this module to google.golang.org/genai
=> feat(ai): direct users to google.golang.org/genai

storage/integration_test.go
This will let us get a better error message (instead of a hang) in the case of permanent "transient" errors. 
The number of attempts is not important and was not chosen for any particular reason other than probably being "enough". We can adjust if ever needed.
=> test(storage): add max attempts to common functions

firestore/client.go, firestore/pipeline.go, firestore/pipeline_result.go, firestore/pipeline_result_test.go, firestore/pipeline_source.go, firestore/pipeline_source_test.go, firestore/pipeline_stage.go, firestore/pipeline_test.go
A Pipeline Query is constructed by defining a series of stages that are executed in order
**Stages**: A pipeline may consist of one or more stages. Logically, these represent the series of steps (or stages) taken to execute the query. Note: In practice, stages may be executed out of order to improve performance. However, this does not modify the intent or correctness of the query.
**Expressions**: Stages will often accept an expression allowing you to express more complex queries. Expression may be simple and consist of a single function like eq("a", 1). You can also express more complex expressions by nesting expressions like and(eq("a", 1), eq("b", 2)).
More info about pipeline queries can be found here: https://cloud.google.com/firestore/docs/pipeline/overview
This is the initial PR …
=> feat(firestore): add pipeline queries

storage/bucket_test.go, storage/storage_test.go
Consistently using `t` makes it less likely for a subtest to call failnow on the parent. I don't think we need the parent testing var in any of these cases.
These instances were picked up by recent test failures.
=> test(storage): shadow testing.T var always

storage/option_test.go, storage/storage_test.go
Closes #12258 which may have resulted from an environment variable leak in one of the tests.
=> test(storage): use t.Setenv instead of os.Setenv

firestore/integration_test.go
The test fails with error
`rpc error: code = FailedPrecondition desc = The query requires an index. That index is currently building and cannot be used yet. See its status here: https://console.firebase.google.com/v1/r/project/gcloud-golang-firestore-tests/firestore/indexes?create_composite=CpEBcHJvamVjdHMvZ2Nsb3VkLWdvbGFuZy1maXJlc3RvcmUtdGVzdHMvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2dvLWludGVncmF0aW9uLXRlc3QtMjAyNDEyMjAtNzExNTE0MjkxOTc4MTEtMDAwMS9pbmRleGVzL0NJQ0FnS1N2Mlo0SxABGgoKBndlaWdodBABGgoKBmhlaWdodBABGgwKCF9fbmFtZV9fEAE`
So, retry the GetAll
=> test(firestore): Retry GetAll

datastore/integration_test.go
1. Fixes: https://github.com/googleapis/google-cloud-go/issues/10664
```go
=== RUN   TestIntegration_AggregationQueriesInTransaction
retry.go:44: FAILED after 10 attempts:
integration_test.go:1216: "Aggregations in transaction after creating entities": Mismatch in aggregation result got: map[avg:double_value:1 count:integer_value:3 sum:integer_value:3], want: map[avg:double_value:1 count:integer_value:3 sum:integer_value:3]
--- FAIL: TestIntegration_AggregationQueriesInTransaction (111.06s)
```
Test fails even though the results are same because aggregation results are a map of key type string and value type pb.Value.
pb.Value has unexported fields state, sizeCache and unknownFields. 
https://github.com/googleapis/google-cloud-go/blob/0fb7b602e320bad3f5199b5dc959f955f167653b/datastore/apiv …
=> test(datastore): Fix flaky integration tests

bigtable/internal/testproxy/known_failures.txt
In [latest run](https://github.com/googleapis/google-cloud-go/actions/runs/15199197073/job/42749998915), the conformance tests are not running and shows  `testing: warning: no tests to run`
```go
++ go1.23.0 test -v -proxy_addr=:9999 -skip 'TestMutateRows_Retry_WithRoutingCookie|TestReadRow_Retry_WithRoutingCookie|TestReadRows_Retry_WithRoutingCookie|TestReadRows_Retry_WithRoutingCookie_MultipleErrorResponses|TestReadRows_Retry_WithRetryInfo_MultipleErrorResponse|TestSampleRowKeys_Retry_WithRoutingCookie|'
++ tee -a /home/runner/work/google-cloud-go/google-cloud-go/google-cloud-go/bigtable/sponge_log.log
go: downloading github.com/golang/protobuf v1.5.4
go: downloading github.com/stretchr/testify v1.10.0
go: downloading google.golang.org/genproto v0.0.0-20241216192217-9240e9c98484
go: …
```
=> test(bigtable): Correct the known conformance failures

spanner/client.go
It's not a bug since ParseFloat by default for any value other than 32 parses in 64 bit
Ref: https://github.com/golang/go/blob/78e86297f5cccb82a6a57081947fab8e8af32586/src/strconv/atof.go#L707
=> chore(spanner): fix bitSize for gfeLatency parser

run/apiv2/locations_client.go
Fixes https://github.com/googleapis/google-cloud-go/issues/12389.
=> fix(run): manually fix default endpoints in frozen locations_client.go

accessapproval/CHANGES.md, advisorynotifications/CHANGES.md, ai/CHANGES.md, aiplatform/CHANGES.md, alloydb/CHANGES.md, apigateway/CHANGES.md, apigeeconnect/CHANGES.md, apikeys/CHANGES.md, appengine/CHANGES.md, apps/CHANGES.md, area120/CHANGES.md, bigtable/CHANGES.md, chat/CHANGES.md, cloudquotas/CHANGES.md
BEGIN_NESTED_COMMIT
fix(accessapproval): fix: upgrade gRPC service registration func
An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://togithub.com/googleapis/google-cloud-go/pull/11025.
END_NESTED_COMMIT
BEGIN_NESTED_COMMIT
fix(advisorynotifications): fix: upgrade gRPC service registration func
An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in …
=> chore: bump changed modules

firestore/pipeline_result.go, firestore/pipeline_result_test.go, firestore/pipeline_source.go, firestore/pipeline_source_test.go, firestore/pipeline_stage.go
Add rest of the pipeline stages: collectionGroup and database
Once the [protos](https://github.com/googleapis/googleapis-gen/tree/preview/google/firestore/v1) are public, kokoro and apidiff checks will pass
More context:
- Previous Pipeline Queries PRs:
- https://github.com/googleapis/google-cloud-go/pull/12217
- Java pipeline input stages:
- https://github.com/googleapis/java-firestore/blob/6f640d021aeeb7f79c89d3d5e3dc6f6897e92456/google-cloud-firestore/src/main/java/com/google/cloud/firestore/PipelineSource.java#L68-L113
=> feat(firestore): Add rest of the input stages

.release-please-manifest-individual.json, .release-please-manifest-submodules.json, release-please-config-yoshi-submodules.json
This entry appears to have been added as a side effect of https://github.com/googleapis/google-cloud-go/pull/12421 but bigquery/v2 is configured using the individual configs:
https://github.com/googleapis/google-cloud-go/blob/6dec2e299b391c4f57d54b0977bf3f19e05abd1f/release-please-config-individual.json#L17-L21
Removing the config from the yoshi list should avoid bigquery/v2 being released under the main release.
This PR also moves the bigquery/v2 from the submodule manifest to the individual manifest, which may be related.
=> chore: remove bigquery/v2 from the yoshi release config

auth/credentials/impersonate/example_test.go
Stumbled upon this TODO while I was exploring the `storage` package and how to write to GCS Bucket by impersonating a specific GSA. 
I am not 100% whether the author of the TODO meant what I did. Nevertheless I opened the PR.
Also I am aware that I didn't open an issue first. I wasn't sure whether it is needed for a small change like this one.
=> docs(impersonate): Address TODO in impersonate/example_test.go

internal/postprocessor/Dockerfile
Fixing error in postprocessor:
```
Step #5: 2025/07/03 02:17:56 exec: "git": executable file not found in $PATH
```
=> fix(internal/postprocessor): add git

spanner/integration_test.go
**Description**: 
Currently we are running GFE related tests while Directpath is enabled. So we will be skipping GFE related tests when direct path is enabled.
=> ci(spanner): Skip GFE related tests when directpath is enabled

internal/postprocessor/config.go, internal/postprocessor/config.yaml, internal/postprocessor/config_test.go, internal/postprocessor/releaseplease.go
This PR is a small refactor to the postprocessor, and makes some internal implementation details configurable via the common config.yaml file.
Doing this as we've recently been defining new individually-released modules (bigquery and pubsub), and thus we've needed to modify and re-release the postprocessor itself, not just update configs.
=> chore(internal/postprocessor): make module scanning config-based

bigquery/v2/apiv2_client/client.go
In order to satisfy the interface exposed on each RPC service, we must expose a Connection() method.  This method is already deprecated in the underlying clients, so this version is explicitly documented as deprecated and returning nothing.
=> feat(bigquery/v2/apiv2_client): add the deprecated Connection() method

storage/client_test.go
Verify that `w.Attrs().Size` is kept up to date when a writer issues a flush.
=> test(storage): Writer Attrs() are updated on flush

storage/client_test.go
This confirms that implementations don't retain the user-provided buffer after the return from Write() in any important way.
=> test(storage): Add buffer reuse test.

go.work.sum, pubsub/v2/doc.go
Update v2 package docs
This PR has a commit that tells release please to release as version 2.0.0
=> docs(pubsub/v2): update v2 package docs with migration guide

storage/client_test.go, storage/grpc_client.go, storage/integration_test.go
This fixes some potential deadlocks in MultiRangeDownloader which were caused by not releasing a lock on early return, or holding it when it wasn't needed (when sending on a chan).
=> fix(storage): fix MultiRangeDownloader deadlock

internal/postprocessor/main_test.go, internal/postprocessor/releaseplease.go
In https://github.com/googleapis/google-cloud-go/pull/12541 the config for modules to skip was transitioned from being hardcoded into the implementation to a config file.  In the course of that refactor the detect logic was inverted, so instead of a skiplist the new config mechanism acted as an allowlist.
This PR corrects that issue, and adds another test to assert the property that skip paths don't appear in the detected module list.
To fully address this issue, we'll also need to bump the owlbot lock once this PR is submitted.
=> chore(internal/postprocessor): address logic inversion

pubsub/v2/doc.go
We are deprecating https://github.com/googleapis/google-cloud-go/wiki/Fine-Tuning-PubSub-Receive-Performance and am moving the contents into the pubsub package docs
This also includes some grammar, typos, and other cleanup in existing sections of the package docs.
=> docs(pubsub/v2): move wiki to package doc

pubsub/flow_controller.go, pubsub/flow_controller_test.go, pubsub/v2/flow_controller.go, pubsub/v2/flow_controller_test.go
This change makes flow controller continue to track and record outstanding messages/bytes even when flow control mechanisms are disabled.
Fixes #12447
=> fix(pubsub/v2): acquire bounded limits in flow controller

spanner/client.go, spanner/client_test.go, spanner/read_test.go, spanner/session_test.go, spanner/transaction_test.go
Only one resource header (google-cloud-resource-prefix) should be included in requests that are sent to Spanner. If the context that is used for a request already contains a resource header, then that header value will be removed, and only the resource header that is set by the Spanner client will be included in the request.
=> fix(spanner): enforce only one resource header

spanner/internal/testutil/inmem_spanner_server.go, spanner/read.go, spanner/read_test.go
Start a goroutine to get the pending trailers to make sure that the stream ends successfully. Remove the cancel function from the stream, to prevent iterator.Stop from potentially calling the cancel function before the trailers have been received.
=> fix: receive trailers to prevent buildup of pending goroutines

storage/grpc_client.go, storage/integration_test.go
Allows out-of-region redirects in MultiRangeDownloader.
Also switches MRD integration test to use a zonal bucket.
=> fix(storage): fix redirect logic in MRD

storage/client_test.go, storage/grpc_writer.go
Oneshot writes did not report progress prior to
https://github.com/googleapis/google-cloud-go/pull/12422. This fixes them so that they also don't report progress after that.
Also add an emulator test, since it turns out our first test of that behavior was in the integration tests!
Fixes https://github.com/googleapis/google-cloud-go/issues/12739
=> fix(storage): No progress report for oneshot write

spanner/mutation.go, spanner/mutation_test.go
Fixes: https://github.com/googleapis/google-cloud-go/issues/12680
=> perf(spanner): improve mutationProto allocations and performance

storage/client_test.go, storage/grpc_writer.go
storage.Writer took an assumption that CloseWithError() could be called more than once, and was thread-safe with respect to concurrent Write(), Flush(), and Close() calls. This was not honored in the refactor in https://github.com/googleapis/google-cloud-go/pull/12422.
Modify Writer so that it is thread-safe to provide these behaviors, and support repeated Close() and CloseWithError() calls.
To address this, we start the sender goroutine earlier, and gather the first buffer in that goroutine. It's possible that some workloads which gather less than one buffer worth of data with a sequence of small writes will observe a performance hit here, since those writes used to be direct copies but will now be a channel ping-pong. If that's an issue, it could be improved by wrapping the buffer in a …
=> fix(storage): Make Writer thread-safe.

bigtable/bigtable.go, bigtable/integration_test.go
Renaming Pinger to PingAndWarm since rest of the methods have verb names.
Pinger has not yet been released. So, it is not a breaking change.
=> refactor(bigtable): Rename pinger to pingAndWarm

internal/librariangen/Dockerfile, internal/librariangen/protoc/protoc.go, internal/librariangen/protoc/protoc_test.go, internal/librariangen/testdata/source/google/cloud/secretmanager/v1beta2/BUILD.bazel, internal/librariangen/testdata/source/google/cloud/secretmanager/v1beta2/secretmanager.proto, internal/librariangen/testdata/source/google/cloud/secretmanager/v1beta2/secretmanager_v1beta2.yaml
This mimics the behavior of Bazel for go_proto_library targets which contain a compilers attribute of `["@io_bazel_rules_go//proto:go_grpc"]`. In that case, we need to use the old version of protoc-gen-go, passing in "plugins=grpc" as an option.
We have to clone and build that explicitly within the Dockerfile, as there's a redirect from the old plugin to the new one. Furthermore, the old plugin uses the internal code from the new plugin, so we need to set the imported new plugin version to "the same one we use for everything else" directly via "go mod edit".
This is all very hacky, but appears to generate identical code to Bazel (tested with secretmanager v1beta2). We will be able to get rid of it all once we've migrated all packages to go_grpc.
=> feat: use old protoc plugin for go_proto_library

spanner/client_test.go, spanner/transaction.go, spanner/transaction_test.go
The database/sql driver uses inline-begin transaction by default for all transaction shapes. It also allows setting transaction options after the transaction has been started, but not yet activated. For example the following script is allowed:
```sql
BEGIN TRANSACTION;
SET ISOLATION_LEVEL='repeatable_read';
UPDATE my_table SET my_col=1 WHERE id=1;
COMMIT;
```
The actual start of the transaction is the UPDATE statement. The isolation level is set after the BEGIN TRANSACTION statement, and should be applied to the current transaction. In order to enable this, statement-based transactions should allow a callback to be registered that will be called when the transaction is actually started. This callback should return any updated transaction options since the BEGIN TRANSACTION call.
=> chore: allow tx opts to be supplied in a callback

release-please-config-individual.json
This PR excludes the v2 directory from the v1 release-please config.
=> chore(bigquery): reconfigure bigquery v1 release definition

internal/stategen/config.go, internal/stategen/main.go
- Use the legacy post-processor config to determine proto paths per library
- Update path removal regexes to be much more precise
With these changes in place, the generated state file only needs tweaking for a handful of libraries. See
go/sdk-librarian-go-migration-planning for those tweaks.
=> tools(stategen): complete state file generation tool

spanner/metrics.go
**Description:**
While running tests in docker-compose with emulator, client library is trying to connect to metadata server to identify the type of client such GCE, Cloud Run..etc. When running tests with emulator, we don't have to connect to metadata server to fetch client location.
=> chore(spanner): Disable connecting to metadata server for emulator tests

internal/librariangen/cloudbuild-exitgate.yaml
1) remove extra tags, will only use latest going forward
2) added cloud logging option
=> chore: Fix exitgate GCB configuration

.librarian/generator-input/repo-config.yaml, .librarian/state.yaml
This adds a state file with AI Platform, but does *not* make the other one-off changes (e.g. reordering imports, removing the executable bit) as those would then be undone by OwlBot.
The intention of this change is to allow the automation that creates generation PRs to be tested, but we should not merge the resulting PRs.
Fixes https://github.com/googleapis/librarian/issues/1982
=> feat: provide minimal onboarding for Librarian

internal/librariangen/postprocessor/postprocessor.go, internal/librariangen/postprocessor/postprocessor_test.go, internal/stategen/main.go
For now, we're going to make the generate command not touch these at all. The command doesn't have enough context to use the right dependencies, so we should leave them as they are.
We therefore shouldn't have go.mod and go.sum in the state file in the remove regexes.
See https://github.com/googleapis/librarian/issues/1921 for context.
=> fix(internal/librariangen): remove go mod init/tidy from postprocessor

storage/go.mod, storage/go.sum
This picks up the patch to fix a race condition in xds, which has been causing multiple integration test failures including #12785
=> chore(storage): bump grpc to v1.74.3

storage/integration_test.go
Checks to Writer.Attrs().Size before the Writer is closed have been in some cases triggering the race detector post writer pipelining updates.
The Writer.Attrs() doc says that this shouldn't be called until after Close() (see https://pkg.go.dev/cloud.google.com/go/storage#Writer.Attrs), so I think it is fine to just remove these checks.
This fixes #12785 for me locally, but it may still fail in the CI due to issues in us-west4.
=> test(storage): fix append test race

internal/librariangen/release/release.go, internal/librariangen/release/release_test.go
fixes: googleapis/librarian#2105
New output:
```
* add new GetSecret API ([abcdef1](https://github.com/googleapis/google-cloud-go/commit/abcdef123456))
* another feature ([zxcvbn0](https://github.com/googleapis/google-cloud-go/commit/zxcvbn098765))
* correct typo in documentation ([123456a](https://github.com/googleapis/google-cloud-go/commit/123456abcdef))
```
=> fix(internal/librariangen): add link to source commit in release notes

compute/metadata/metadata.go, compute/metadata/metadata_test.go
By default the Client in this package now uses a slightly different client for subscription methods. Subscription clients should not set the idle timeout because they could go long periods of time without the connection being used again. If the users specifies a client it will be used for both types of calls.
Also fixed a bug where Subscribe methods were not honoring context errors.
Internal Bug: 427030684
=> fix(compute/metadata): use separate client for subscribe methods 

compute/metadata/metadata.go, compute/metadata/metadata_test.go
=> fix(compute/metadata): racy test and uninitialized subClient

compute/metadata/metadata.go, compute/metadata/metadata_test.go
Caught in an internal review. Verified all constructors have been updated now.
=> fix(compute/metadata): set subClient for UseDefaultClient case

firestore/collgroupref.go, firestore/collref.go, firestore/query.go
This commit fixes a panic and incorrect behavior that occurs when using WithReadOptions in firestore queries.
The readSettings field in the Query struct was not always initialized, leading to a nil pointer dereference when WithReadOptions was called. This affected CollectionGroupRef and CollectionRef in three distinct scenarios as reported in the issue.
This commit addresses the issue by implementing the following changes:
- **Initialized readSettings in CollectionGroupRef**: The newCollectionGroupRef function in collgroupref.go now initializes the readSettings field on the embedded Query object, preventing panics when WithReadOptions is used on a collection group query.
- **Shared readSettings in CollectionRef**: The newTopLevelCollRef and newCollRefWithParent functions in collref.go now …
=> fix(firestore): Initialize readSettings in queries to prevent panic

pubsub/v2/integration_test.go, pubsub/v2/iterator.go, pubsub/v2/shutdown.go, pubsub/v2/shutdown_test.go, pubsub/v2/streaming_pull_test.go, pubsub/v2/subscriber.go, pubsub/v2/subscriber_test.go
This introduces the ability to tell the client library how you want your messages to behave when shutdown is initiated. You can configure the behavior as `ShutdownOptions.Behavior` as `ShutdownBehaviorWaitForProcessing` or `ShutdownBehaviorNackImmediately`.
In addition, you can specify `ShutdownOptions.Timeout` to configure how long you want to wait for messages to be processed, or provide a timeout to the nack calls before returning.
=> feat(pubsub/v2): add subscriber shutdown options

internal/librariangen/release/release.go, internal/librariangen/release/release_test.go, internal/librariangen/request/request.go
If a library has "." configured as a source path, expect to find CHANGES.md in the root directory, and version.go under the root internal directory. (In every other case, we use the library ID as a "relative root directory" for the module.)
=> feat(internal/librariangen): support for "whole repo" libraries
